<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Onestepcheckout
 * @version     0.1.9
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2014 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 * */
?>
<?php 
$apikey = Mage::getStoreConfig('onestepcheckout/general/Apply_apptha_licensekey');
$onestepapikey = $this->helper('onestepcheckout')->onestepApiKey();
$shippingmethod = Mage::getStoreConfig('onestepcheckout/general/default_shipping_method');
$_shippingRateGroups = $this->getShippingRates();
$shipping = Mage::helper('checkout/cart')->getQuote()->getShippingAddress();

$base_amount = 1500;
$baseCurrencyCode = Mage::app()->getStore()->getBaseCurrencyCode();
$currentCurrencyCode = Mage::app()->getStore()->getCurrentCurrencyCode();
$disp_base_amount = Mage::helper('directory')->currencyConvert($base_amount, $baseCurrencyCode, $currentCurrencyCode); 
?>
<!---Title  of the page -->
<!---Start of Shipping Methods -->
 <?php if (!($_shippingRateGroups)): ?>
    <strong><?php echo $this->__('Sorry, no quotes are available for this order at this time.') ?></strong>
<?php else: ?>
<dl class="shipment-methods">
        <?php $fedex = 0;
        $dhl = 0;
        $flatrate = 0;
        foreach ($_shippingRateGroups as $code => $_rates){
          if($code == 'fedex' && $_rates['0']['code'] != 'fedex_error') $fedex = 1;
          if($code == 'dhlint') $dhl = 1;
          if($code=='tablerate' && ($fedex != 1 || $dhl != 1) ) { $tablerate =1 ;}
          if($code=='flatrate' && (Mage::helper('checkout/cart')->getQuote()->getBaseSubtotal() < $base_amount)) { $flatrate = 1; }
        }
        $_sole = count($_shippingRateGroups) == 1;
        foreach ($_shippingRateGroups as $code => $_rates): ?>
          <?php if($code == 'fedex') {
            foreach ($_rates as $_rate):
              if(strpos($_rate->getCode(), 'fedex_error')!==false) continue(2);
            endforeach;
          } ?>

          <?php if($code!='freeshipping' && $code != 'collectinstore') {
            if($code=='flatrate' && (Mage::helper('checkout/cart')->getQuote()->getBaseSubtotal() > $base_amount)) { continue;  }
            if($code=='tablerate' && ($fedex == 1 || $dhl == 1) ) { continue;} ?>
                <dd><?php echo $this->getCarrierName($code) ?></dd>
                <?php foreach ($_rates as $_rate): ?>
                    <dt>
                       <?php if ($_rate->getErrorMessage()): ?>
                        <ul class="messages"><li class="error-msg"><ul><li><?php echo $_rate->getErrorMessage() ?></li></ul></li></ul>
                       <?php else: ?>
                            <input name="shipping_method" type="radio" class="validate-one-required-by-name" value="<?php echo $_rate->getCode() ?>" id="s_method_<?php echo $_rate->getCode() ?>"<?php if($_rate->getCode()===$shippingmethod) echo ' checked="checked"' ?>')" />
                            <label for="s_method_<?php echo $_rate->getCode() ?>"><!--<b><?php echo $this->getCarrierName($code) ?>:</b>--> <?php echo $_rate->getMethodTitle() ?>
                            <strong>
                            <?php $_excl = $this->getShippingPrice($_rate->getPrice(), $this->helper('tax')->displayShippingPriceIncludingTax()); ?>
                            <?php $_incl = $this->getShippingPrice($_rate->getPrice(), true); ?>

                            <?php echo $_excl; ?>
                            <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                                (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                            <?php endif; ?>
                            </strong>
                            </label>
                       <?php endif ?>
                    </dt>
                    <?php if($_rate->getCode() == 'tablerate_bestway'){ ?>
                      <p class="note_import_duties_and_taxes1">Address may be in-complete, Re-check now!</p>
                    <?php } ?>
                <?php endforeach; ?>
            <?php } ?>

                <?php if($code=='freeshipping' && $flatrate != 1) { ?>
                  <?php foreach ($_rates as $_rate): ?>
                    <dd><?php echo $this->getCarrierName($code) ?></dd>
                    <dt>
                       <?php if ($_rate->getErrorMessage()): ?>
                        <ul class="messages"><li class="error-msg"><ul><li><?php echo $_rate->getErrorMessage() ?></li></ul></li></ul>
                       <?php else: ?>
                            <input name="shipping_method" type="radio" class="validate-one-required-by-name" value="<?php echo $_rate->getCode() ?>" id="s_method_<?php echo $_rate->getCode() ?>"<?php if($_rate->getCode()===$shippingmethod) echo ' checked="checked"' ?>')" />
                            <label for="s_method_<?php echo $_rate->getCode() ?>"><!--<b><?php echo $this->getCarrierName($code) ?>:</b>--> <?php echo $_rate->getMethodTitle() ?>
                            <strong>
                            <?php $_excl = $this->getShippingPrice($_rate->getPrice(), $this->helper('tax')->displayShippingPriceIncludingTax()); ?>
                            <?php $_incl = $this->getShippingPrice($_rate->getPrice(), true); ?>

                            <?php echo $_excl; ?>
                            <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                                (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                            <?php endif; ?>
                            </strong>
                            </label>
                       <?php endif ?>
                    </dt>
                  <?php endforeach; ?>
                <?php } ?>

                <?php if($code=='collectinstore') {?>
                  <?php foreach ($_rates as $_rate): ?>
                    <dd><?php echo $this->getCarrierName($code) ?></dd>
                    <dt>
                       <?php if ($_rate->getErrorMessage()): ?>
                        <ul class="messages"><li class="error-msg"><ul><li><?php echo $_rate->getErrorMessage() ?></li></ul></li></ul>
                       <?php else: ?>
                            <input name="shipping_method" type="radio" class="validate-one-required-by-name" value="<?php echo $_rate->getCode() ?>" id="s_method_<?php echo $_rate->getCode() ?>"<?php if($_rate->getCode()===$shippingmethod) echo ' checked="checked"' ?>')" />
                            <label for="s_method_<?php echo $_rate->getCode() ?>"><!--<b><?php echo $this->getCarrierName($code) ?>:</b>--> <?php echo $_rate->getMethodTitle() ?>
                            <strong>
                            <?php $_excl = $this->getShippingPrice($_rate->getPrice(), $this->helper('tax')->displayShippingPriceIncludingTax()); ?>
                            <?php $_incl = $this->getShippingPrice($_rate->getPrice(), true); ?>

                            <?php echo $_excl; ?>
                            <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                                (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                            <?php endif; ?>
                            </strong>
                            </label>
                       <?php endif ?>
                    </dt>
                  <?php endforeach; ?>
                <?php } ?>
        <?php endforeach; ?>
    </dl>

<?php endif; ?> 
 <!---End of Shipping Methods -->
           <script type="text/javascript" >
           <?php if($apikey != $onestepapikey)
           {
           ?>           
           $('title-text').identify();
           <?php }?>
           $$('dl.shipment-methods input').invoke('observe', 'click', function() {
            shipping.reloadReviewBlock();
            var payment_methods = $('ajax-payment-methods');
            payment_methods.update('<div class="loading-ajax">&nbsp;</div>');
            payment.reloadPaymentBlock();
            //payment.switchMethod(paymentMethod);
        });
       
           </script>

<div class="clear"></div>
<div><p class="note_import_duties_and_taxes1">Ship for free within India for order value over Rs.1500.</p></div>
<?php 
      $moduleName = 'Naresh_Taxrate';
      $countrycode = $shipping->getCountryId();
      unset($_SESSION['ddp']);
      if(Mage::getConfig()->getModuleConfig($moduleName)->is('active', 'true')){
        $current_currency =  Mage::app()->getStore()->getCurrentCurrencyCode();
        $base_currency = Mage::app()->getStore()->getBaseCurrencyCode();
        $quote = Mage::getModel('checkout/session')->getQuote()->getData();
        $subtotal = $quote['subtotal'];
        $taxrate = Mage::getSingleton('taxrate/taxrate')
                      ->getCollection()
                      ->addFieldToFilter('status',1)
                      ->addFieldToFilter('cat_id', array('like' => '%'.$countrycode.'%'))
                      ->getFirstItem();
        $gst_perc = ($subtotal*$taxrate->getGstPerc())/100;
          $handling_fee = Mage::helper('directory')->currencyConvert($taxrate->getHandlingFee(), $base_currency, $current_currency);
            $tax_default_perc = ($subtotal*$taxrate->getTaxDefaultPerc())/100;
            $Total_Custom_Duties_and_Taxes = $gst_perc + $handling_fee + $tax_default_perc;
          if (round($Total_Custom_Duties_and_Taxes,2) > 0 || $countrycode == 'UA' || $countrycode == 'AE' || $countrycode == 'HK') { ?>
            <div class="import_duties_taxes">
              <div class="page-title">
                <h1><?php echo $this->__('Import Duties and Taxes') ?></h1>
              </div>
              <?php if (round($Total_Custom_Duties_and_Taxes,2) > 0) { ?>
                <dl class="shipment-methods sp-methods" id="checkout-payment-method-load">
                    <input type="checkbox" class="add_custom_duties_taxes" id="add_custom_duties_taxes" name="shipping_method_1" />
                    <input id="ddp_val_calculation" class="ddp_val_calculation" type="hidden" value="0" name="ddpval">
                    <label class="ddp_label"> Incl. Import Duties and Taxes : <?php echo '<span class="ddp_amount" >'.Mage::helper('checkout')->formatPrice(round($Total_Custom_Duties_and_Taxes,2)).'</span>'; ?> </label><label class="show_importance" style="display:none;">&nbsp;***</label>
                    <label class="ddp_label">(Import Duty : <?php echo $taxrate->getTaxDefaultPerc(); ?>%, GST : <?php echo $taxrate->getGstPerc(); ?>% Per Product,<br> Fixed Import Handling Charges <?php echo Mage::helper('checkout')->formatPrice($handling_fee); ?> Per Order.)</label>
                    <p class="note_import_duties_and_taxes"><b>DELIVERED DUTY PAID (DDP)</b><br>
                Import Duties and Taxes at destination will be Fully Paid by Yourself (Customer).<br>No Import Duties & Taxes if shipped to an Indian Address.</p>
                </dl>
              <?php }else {
                echo '<p class="note_import_duties_and_taxes"><b>DELIVERED DUTY PAID (DDP)</b><br>
                Import Duties and Taxes at destination will be Fully Paid by Yourself (Customer).</p>';
              } ?>
            </div>
          <?php } elseif($countrycode != 'IN'){ ?>

            <div class="import_duties_taxes"><div class="page-title">
              <h1>Import Duties and Taxes</h1>
            </div>
          <p class="note_import_duties_and_taxes"><b>DELIVERED DUTY PAID (DDP)</b><br>Import Duties and Taxes at destination will be Fully Paid by <?php if($countrycode == 'US' || $countrycode == 'HK'){ ?> Mysore Saree Udyog <?php } else{?> Yourself (Customer) <?php } ?>.<br>No Import Duties & Taxes if shipped to an Indian Address.</p></div>
        <?php }
      }
?>


 <!---Start of Gift Message  -->
  <div id="onepage-checkout-shipping-method-additional-load">
       <?php if (!$this->getQuote()->isVirtual()): ?>

    <?php echo $this->helper('giftmessage/message')->getInline('onepage_checkout', $this->getQuote(), $this->getDontDisplayContainer()) ?>
<?php endif; ?>
    </div>
  <!---End of Gift Message  -->
 
  <!---End of Gift Message  -->
<script type="text/javascript">
  // jQuery(document).ready(function(){
  //   if(jQuery('#add_custom_duties_taxes').is(':visible')) {
  //     var val1 = 0;
  //     jQuery('.ddp_val_calculation').val(val1);
  //     jQuery.ajax({
  //           url: 'https://Mysore Saree Udyog.com/storecardholdername/index/ddpsessionval',
  //           type : 'POST',
  //           data: {
  //               txt: val1,
  //           },
  //           success: function(response){ 
  //           }
  //     });
  //   }
  // });
  jQuery(".add_custom_duties_taxes").click(function(){
      if(jQuery(this).is(":checked")) {
        jQuery('.show_importance').hide();
        jQuery('.note_import_duties_and_taxes').empty();
        jQuery('.note_import_duties_and_taxes').append('<b>DELIVERED DUTY PAID (DDP) </b><br>Import Duties and Taxes at destination will be Fully Paid by Mysore Saree Udyog.<br>No Import Duties & Taxes if shipped to an Indian Address.');
      }else {
        jQuery('.show_importance').show();
        jQuery('.note_import_duties_and_taxes').empty();
        jQuery('.note_import_duties_and_taxes').append('<b>DELIVERED DUTY PAID (DDP)</b><br>Import Duties and Taxes at destination will be Fully Paid by Yourself (Customer). <br>*** The above is only an estimated value.<br>No Import Duties & Taxes if shipped to an Indian Address.');
      }
   });
</script>