<?php
/**
 * This file is part of The Official Amazon Payments Magento Extension
 * (c) Pay with Amazon
 * All rights reserved
 *
 * Reuse or modification of this source code is not allowed
 * without written permission from Pwatech
 *
 * @category   Pwa
 * @package    Pwa_PaywithAmazon
 * @copyright  Pay with Amazon
 * @author     Pay with Amazon
 */
?>
<div id="ProgressAmazonWalletWidget"></div>
<script type="text/javascript">//<![CDATA[
    new CBA.Widgets.WalletWidget({
        merchantId: '<?php echo $this->getMerchantId(); ?>',
        displayMode: 'Read',
<?php if ($this->getPurchaseContractId()): ?>
        purchaseContractId: '<?php echo $this->getPurchaseContractId(); ?>',
<?php endif; ?>
        design: {size: {width: '<?php echo $this->getWidgetWidth(); ?>', height: '<?php echo $this->getWidgetHeight(); ?>'}}
    }).render('ProgressAmazonWalletWidget') ;
//]]></script>
