<?php
    $url= $_SERVER['REQUEST_URI'];
    $urlarr=explode('/id/',$url);
    $myid= explode('/',$urlarr[1]);
    echo $attrid = $myid[0];
    $measurement = Mage::getModel('measurement/measurement')->getCollection()->addFieldToFilter('measurement_id',$attrid)->getFirstItem();
    $read = Mage::getSingleton('core/resource')->getConnection('core_read');
    $cat = array();
    if(!empty($attrid)){
    	$customtitles = Mage::getResourceModel('measurement/customtitles_collection')->addFieldToFilter('measurement_id',$attrid);
    }
?>
<table cellspacing="0" class="form-list">
	<tbody id="measurement_attr_attr">
		<?php if($measurement->getDropdownType() != 'custom'){ ?>
			<tr class="field_value" id="field_value"><td class="label"><label for="min_val">Min Value <span class="required">*</span></label></td><td class="value"><input type="text" class="required-entry input-text required-entry" value="<?php echo $measurement->getMinVal(); ?>" name="min_val" id="min_val"></td></tr>
			<tr class="field_value" id="field_value"><td class="label"><label for="max_val">Max Value <span class="required">*</span></label></td><td class="value"><input type="text" class="required-entry input-text required-entry" value="<?php echo $measurement->getMaxVal(); ?>" name="max_val" id="max_val"></td></tr>
			<tr class="field_value" id="field_value"><td class="label"><label for="difference">Difference <span class="required">*</span></label></td><td class="value"><input type="text" class="required-entry input-text required-entry" value="<?php echo $measurement->getDifference(); ?>" name="difference" id="difference"></td></tr>
		<?php } ?>
	</tbody>
</table>
<div class="show_custom_titles" style="display:<?php if($measurement->getDropdownType() == 'custom'){echo 'block';}else{echo 'none';} ?>;">
<table class="attribute-label-table">
	<tr>
		<td>
			<?php echo $this->getElement()->getLabel() ?>
		</td>
	</tr>
</table>
<table id="attribute-options-table" style="margin-top: 30px;">
<tbody>
<tr>
	<th class="th">Custom Option Title</th>
	<th class="th">
		<button id="add_new_option_button" title="Add Values" type="button" class="scalable add">
			<span><?php echo $this->__('Add Option') ?></span>
		</button>
	</th>
</tr>
</tbody>
</table>
<br><br><br><br>
	<table class="attribute-label-table"><tr><td></td></tr></table>
	<table id="attribute-options-table1">
		<tbody> 
			<?php $maincount=0;
				if (sizeof($customtitles) > 0) {
				foreach ($customtitles as $field) { ?>
					<tr id='<?php echo $maincount ?>' class="mytr"> 
						<td class="mytd"><input type="text" name='custom_title<?php echo $maincount ?>' value="<?php echo $field['title']; ?>" class="required-entry "/>
						</td>
						<td class='a-left' id='delete_button_container_option_<?php echo $maincount ?>'>
							<button onclick='SomeDeleteRowFunction(this,<?php echo $field['custom_title_id']; ?>);' title='Delete' type='button' class='scalable delete delete-option'>
								<span>Delete</span>
							</button>
							<?php //echo $field['custom_title_id']; ?>
						</td>
						<td class="mytd"><input type="hidden" name='custom_title_id<?php echo $maincount ?>' value="<?php echo $field['custom_title_id']; ?>" class="required-entry "/></td>
					</tr>
			<?php $maincount++; }
			} ?>                
			<input type="hidden" class="validate-autofill" id="count" name="counts" value="<?php echo $maincount ?>"/>
		</tbody>
	</table>
</div>
<script type="text/javascript">
			var _form_html_row = "<tr id='{{id}}' class='mytr'><td><input type='text' name='custom_title{{id}}' class='required-entry' value='' /></td><td class='a-left' id='delete_button_container_option_{{id}}'><button onclick='deleteRow({{id}});' title='Delete' type='button' class='scalable delete delete-option'><span>Delete</span></button><input type='hidden' name='count' value='{{id}}'/></td></tr>";
			$('add_new_option_button').observe('click', function(){
				var count=document.getElementById('count').value++  ;
				$('attribute-options-table').insert(_form_html_row.replace(/\{\{id\}\}/ig, count));
			});
			function deleteRow(rowid) {
				var row = document.getElementById(rowid);
				row.parentNode.remove();
				document.getElementById('count').value--  ;
			}
			function SomeDeleteRowFunction(o,custom_title_id) {
				var p=o.parentNode.parentNode;
				p.parentNode.removeChild(p);
				document.getElementById('count').value--  ;
			}
		</script>
<script>
	var index = 0;
	function myFunction() {
		var a1 = index++;
		var d1 = document.getElementById('one');
		d1.insertAdjacentHTML('beforeend', '<tr id=tr"'+a1+'"><td><input type="text" /></td><td><input type="text" /></td><td><select><option id=1 >Fixed</option><option id=2 >Percentage</option></select></td><td><input type="text" /></td><td><button onclick="myfunremove(this.id);" class="delete" type="button" title="Remove" id="'+a1+'"><span></span></button></td></tr>');
	}
	function myfunremove(a) {
		var val = document.getElementById(a).parentNode;
		val.remove();
	}
</script>
<script src="http://code.jquery.com/jquery-latest.min.js" type="text/javascript"></script>
<script type="text/javascript">
	var jQuery = jQuery.noConflict();
	jQuery(function(){
		jQuery('#field_type').change(function() {
			if(this.value == 'text_area'){
				jQuery("#dropdown_type").prop("disabled", true);
				jQuery('#measurement_attr_attr').find('tr#field_value').each(function(){
					jQuery(this).remove();
				});
			} else if(this.value == 'dropdown'){
				jQuery("#dropdown_type").prop("disabled", false);
				if(jQuery('#measurement_attr_attr').find('tr#field_value').length == 0){
					jQuery('#measurement_attr_attr').append("<tr id=field_value><td class=label><label for=min_val> Min Value <span class=required>*</span></label></td><td class=value><input type=text class=required-entry name=min_val id=min_val></td></tr><tr id=field_value><td class=label><label for=max_val>Max Value <span class=required>*</span></label></td><td class=value><input type=text class=required-entry name=max_val id=max_val></td></tr><tr id=field_value><td class=label><label for=difference>Difference <span class=required>*</span></label></td><td class=value><input type=text class=required-entry name=difference id=difference></td></tr>");
				}
			} else if(this.value == 'radio'){
				jQuery("#dropdown_type").prop("disabled", false);
				jQuery('#dropdown_type').val('custom');
				jQuery('.show_custom_titles').show();
				jQuery('#dropdown_type').find('option:first').prop('disabled', true);
				jQuery('#measurement_attr_attr').find('tr#field_value').each(function(){
					jQuery(this).remove();
				});
			} else if(this.value == 'text_field'){
				jQuery("#dropdown_type").prop("disabled", true);
				if(jQuery('#measurement_attr_attr').find('tr#field_value').length == 0){
					jQuery('#measurement_attr_attr').append("<tr id=field_value><td class=label><label for=min_val> Min Value <span class=required>*</span></label></td><td class=value><input type=text class=required-entry name=min_val id=min_val></td></tr><tr id=field_value><td class=label><label for=max_val>Max Value <span class=required>*</span></label></td><td class=value><input type=text class=required-entry name=max_val id=max_val></td></tr><tr id=field_value><td class=label><label for=difference>Difference <span class=required>*</span></label></td><td class=value><input type=text class=required-entry name=difference id=difference></td></tr>");
				}
			}
		});

		jQuery('select#dropdown_type').change(function() {
			if(this.value == 'custom'){
				jQuery('#measurement_attr_attr').find('tr#field_value').each(function(){
					jQuery(this).remove();
				});
				jQuery('.show_custom_titles').show();
			}else if (this.value == 'standard') {
				jQuery('#measurement_attr_attr').find('tr#field_value').each(function(){
					jQuery(this).remove();
				});
				jQuery('.show_custom_titles').hide();
				jQuery('#measurement_attr_attr').append("<tr id=field_value><td class=label><label for=min_val> Min Value <span class=required>*</span></label></td><td class=value><input type=text class=required-entry name=min_val id=min_val></td></tr><tr id=field_value><td class=label><label for=max_val>Max Value <span class=required>*</span></label></td><td class=value><input type=text class=required-entry name=max_val id=max_val ></td></tr><tr id=field_value><td class=label><label for=difference>Difference <span class=required>*</span></label></td><td class=value><input type=text class=required-entry name=difference id=difference></td></tr>");
			}
		});
	});
</script>
<style>
.attribute-label-table { float: left;
    margin-top: 30px;
    width: 210px; }
#attribute-options-table { width: 750px; float: left; }
#attribute-options-table1 { width: 475px; }
.th{ width: 280px; }
.required-entry { width: 50%;min-width: 275px; }
.myinput-text.required-entry.widthinput { height: 250px; width: 280px; }
#category > option { height: 20px; padding-left: 10px; }
</style>