<div class="finalamountaftersale">
<?php
	$query = "select type,percentage from measurementmember_flatrates where cat_id =".$_REQUEST["category"]." and ".$_REQUEST["price"]." between price_from and price_to";
	$read = Mage::getSingleton('core/resource')->getConnection('core_read');
	$results = $read->fetchAll($query);
	if (sizeof($results) == 0) {
		unset($results);
		$query = "select type,percentage from measurementmember_flatrates where cat_id = 0 and ".$_REQUEST["price"]." between price_from and price_to";
		$results = $read->fetchAll($query);
	}
	if($results[0]['type'] == 'Fixed'){
		$measurementmember = $_REQUEST["price"]-$results[0]['percentage'];
		echo "<div class=after_measurementmember>";
		echo "You will get $".$measurementmember." (per product after sale)";
		echo "</div>";
	}else{
		$percentage = ($_REQUEST["price"]/100)*$results[0]['percentage'];
		$measurementmember = $_REQUEST["price"]-$percentage;
		echo "<div class=after_measurementmember>";
		echo "You will get $".$measurementmember." (per product after sale)";
		echo "</div>";
	}
?>
</div>