<script>
	jQuery('document').ready(function(){
		var count = 0;
		jQuery(window).bind('scroll', function() {
			if(jQuery(window).scrollTop() >= jQuery('.col-main').offset().top + jQuery('.col-main').outerHeight() - window.innerHeight) {
				var numitems = jQuery("div.shop_by_collection1 > div.collection_items").length;
				if(count == 0 && numitems > 0) {
					jQuery('#inifiniteLoader').toggle();
					count += 1;
					var data1 = "&page="+numitems;
					var url1 = '<?php echo Mage::getBaseUrl(); ?>mycategory/index/loadnextpage';
					try {
						jQuery.ajax({
							url: url1,
							type : 'post',
							data: data1,
							success: function(response){
								if (response) {
									jQuery('#inifiniteLoader').toggle();
									jQuery(".shop_by_collection1").append(response);
									setTimeout(function(){ count = 0; }, 2000);
								}else{
									jQuery('#inifiniteLoader').toggle();
								}
							}
						});
					} catch(e){ }
				}
			}
		});
	});
</script>