<?php
/**
 * This file is part of The Official Amazon Payments Magento Extension
 * (c) Pwatech
 * All rights reserved
 *
 * Reuse or modification of this source code is not allowed
 * without written permission from pwa  
 *
 * @category   Pwa
 * @package    Pwa_PaywithAmazon
  * @copyright  Copyright (c) Pay with Amazon
 * @author     Pay with Amazon
 */
?>
<?php 
$currencyCode = Mage::app()->getStore()->getCurrentCurrencyCode(); 
$isVirtual = Mage::getSingleton('checkout/session')->getQuote()->isVirtual();
if($currencyCode=='INR' && !$isVirtual)
{
?>
<div id="cbaxmlButton">
<img style="cursor:pointer;" src="<?php echo $this->getButtonWidgetUrl(); ?>"/><br></div>
    <script>
    RenderCBAButtonById = function(ordervalue, buttonid) {
    var standard1 = new CBA.Widgets.StandardCheckoutWidget({
    merchantId: "<?php echo $this->getMerchantId(); ?>",
    orderInput: {
    format: "XML",
    value: ordervalue}
    }).render(buttonid);
    }
    </script>
    <script language="javascript" type="text/javascript">
    RenderCBAButtonById("<?php echo $this->createOrderInputValue(); ?>", "cbaxmlButton");
</script>


<?php } ?>