<?php
    $url= $_SERVER['REQUEST_URI'];
    $urlarr=explode('/id/',$url);
    $myid= explode('/',$urlarr[1]);
    $attrid = $myid[0];
    if(!empty($attrid)){
    	$collection = Mage::getModel('salwar/salwar')->getCollection()->addFieldToFilter('salwar_id',$attrid)->getFirstItem();
    }
?>
<table class="form-list" cellspacing="0">
	<tr>
		<td class="label"><label for="<?php echo $this->getElement()->getName() ?>"><?php echo $this->getElement()->getLabel() ?> <span class="required">*</span></label></td>
		<td class="value">
        <select multiple="multiple" size="10" class="required-entry required-entry select multiselect" name="stitching_service[]" id="stitching_service">
        	<?php if (isset($collection)) {
				$stit_service = explode(',', $collection->getStitchingService());
				$stitching_types = Mage::getModel('stitchingservices/stitchingservices')->getCollection()->addFieldToFilter('stitching_service_id',$collection->getStitchingServiceId())->addFieldToFilter('status',1)->addFieldToFilter('stitching_service_price', array('gt' => '0.00'));
				foreach ($stitching_types as $_type) { ?>
					<option <?php if(in_array($_type->getStitchingservicesId(), $stit_service)){ echo 'selected'; } ?> value="<?php echo $_type->getStitchingservicesId(); ?>"><?php echo $_type->getTitle(); ?></option>
				<?php }
			}else{ ?>
				<option>--- Select Multiple Options ---</option>
			<?php } ?>
        </select>
        <p id="note_<?php echo $this->getElement()->getName() ?>" class="note"><span><?php echo $this->getElement()->getNote() ?></span></p>
            </td>
	</tr>
</table>
<script src="http://code.jquery.com/jquery-latest.min.js" type="text/javascript"></script>
<script type="text/javascript">
	var jQuery = jQuery.noConflict();
	jQuery(function(){
		jQuery('#stitching_service_id').change(function() {
			var data1 = "&service="+this.value;
			var url1 = '<?php echo Mage::getBaseUrl(); ?>styles/index/availstittypes';
			try {
				jQuery.ajax({
					url: url1,
					type : 'post',
					data: data1,
					success: function(response){
						if (response) {
							var string = response;
						} else{
							var string = '<select multiple="multiple" size="10" class="required-entry required-entry select multiselect" name="stitching_service[]" id="stitching_service"><option>--- Select Multiple Options ---</option></select>';
						}
						jQuery('#stitching_service').replaceWith(string);
					}
				});
			} catch(e){ }
		});
	});
</script>