<?php
/**
 * This file is part of The Official Amazon Payments Magento Extension
 * (c) Pay with Amazon
 * All rights reserved
 *
 * Reuse or modification of this source code is not allowed
 * without written permission from Pwatech
 *
 * @category   Pwa
 * @package    Pwa_PaywithAmazon
 * @copyright  Pay with Amazon
 * @author     Pay with Amazon
 */
?>
<div class="content-header">
    <table cellspacing="0">
        <tbody><tr>
            <td style="width:50%;"><h3 class="icon-head"><?php echo Mage::helper('paywithamazon')->__('Debug data') ?></h3></td>
            <td class="form-buttons"><button style="" onclick="setLocation('<?php echo $this->getUrl('paywithamazon/adminhtml_debug/download'); ?>')" class="scalable" type="button"><span>Download as file</span></button></td>
        </tr>
    </tbody></table>
</div>
<div>
    <?php echo $this->getChildHtml('debug_info'); ?>
</div>
