<?php
/**
 * This file is part of The Official Amazon Payments Magento Extension
 * (c) Pwatech
 * All rights reserved
 *
 * Reuse or modification of this source code is not allowed
 * without written permission from pwa  
 *
 * @category   Pwa
 * @package    Pwa_PaywithAmazon
 * @copyright  Copyright (c) 2011 - 2014 pwa   (http://www.pwatech.com)
 * @author     Milind Desai / Pwatech
 */
?>
<div class="pwa-info">
    <a class="pwa-logo" href="#" target="_blank">
         <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB).'skin/frontend/base/default/pwa/images/paywithamazon.png'; ?>" alt="pay with amazon" /> 
    </a>
</div>
