<div class="edit_measurements">
	<div class="page-title">
        <h1>Add Stored Measurement</h1>
    </div>
    <div class="add_measurement">
            <form action="<?php echo Mage::getBaseUrl(); ?>measurement/stored/save" method="post" id="measurement">
                    <?php $all_stitching_services = Mage::getSingleton('eav/config')->getAttribute('catalog_product', 'a27');
                      if ($all_stitching_services->usesSource()) {
                        $avail_stitching_services = $all_stitching_services->getSource()->getAllOptions(false);
                      }
                      if (sizeof($avail_stitching_services) > 0) { ?>
                        <div class="m_attr">
                            <label class="label">Stitching Services</label>
                            <label class="value">
                                <select class="add_avail_stitching_services" name="service"><option>--- Please Select ---</option>
                                    <?php foreach ($avail_stitching_services as $_stitching_service) { ?>
                                        <option value="<?php echo $_stitching_service['value']; ?>"><?php echo $_stitching_service['label']; ?></option>
                                    <?php } ?>
                                </select>
                        </div>
                      <?php } ?>
                    <input type="hidden" name="customer_id" class="customer_id" value="<?php echo Mage::getSingleton('customer/session')->getId(); ?>" />
                    <div class="add_stitching_services_types"></div>
                    <div class="add_measure_details"></div>
            </form>
    </div>
</div>
<style type="text/css">
.add_measurewments_save > input {
    background: #dd3d3d none repeat scroll 0 0;
    border: medium none;
    color: #fff;
    float: right;
    font-size: 14px;
    font-weight: bold;
    padding: 5px 30px;
}
.m_attr .image {
    display: none;
    float: right;
}
.m_attr .content {
    border: 1px solid #a2a2a2;
    border-radius: 5px;
    display: none;
    float: right;
    margin-right: 10px;
    padding: 10px;
    width: 150px;
}
.m_attr > #label {
    float: left;
    min-height: 35px;
    width: 25% !important;
}
.add_measuring_units, .measurement_attributes {
    line-height: 25px;
    padding: 5px 10px;
}
.m_attr {
    margin-bottom: 5px;
}
.m_attr .label {
    float: left;
    line-height: 30px;
    min-width: 40%;
}
.m_attr .value select {
    height: 30px;
    padding: 5px;
    width: 30%;
}
.m_attr .value {
    line-height: 30px;
}
.m_attr .value input.measurement_textfield {
    height: 20px;
    padding: 5px;
    min-width: 25%;
}
.label_title {
    background: #cfcfcf none repeat scroll 0 0;
    font-size: 16px;
    margin-bottom: 1%;
    padding: 1%;
}
.label_title1 {
    background: #e3e3e3 none repeat scroll 0 0;
    font-size: 15px;
    font-weight: bold;
    margin-bottom: 5px;
    padding: 3px;
    text-align: center;
}
#style_details {
    height: 240px !important;
    padding: 15px;
}
/*.back_style_li {
    float: left;
    height: 220px;
    list-style: outside none none;
    margin-right: 1%;
    padding: 1%;
    text-align: center;
    width: 17%;
}
.sleeve_style_li {
    float: left;
    height: 220px;
    list-style: outside none none;
    margin-right: 1%;
    padding: 1%;
    text-align: center;
    width: 17%;
}*/
/*.front_style_li {
    float: left;
    height: 275px;
    list-style: outside none none;
    margin-right: 1%;
    padding: 1%;
    text-align: center;
    width: 17%;
}*/
</style>
<script type="text/javascript">
    var jQuery = jQuery.noConflict();
    jQuery(function(){
        jQuery('select.add_avail_stitching_services').change(function() {
            var data1 = "&stitching_service="+this.value;
            var url1 = '<?php echo Mage::getBaseUrl(); ?>measurement/stored/getservicetypes';
            try {
                jQuery.ajax({
                    url: url1,
                    type : 'post',
                    data: data1,
                    success: function(response){
                        if (response) {
                            var string = response;
                        } else{
                            var string = '<div class="add_stitching_services_types"></div>';
                        }
                        jQuery('.add_stitching_services_types').replaceWith(string);
                    }
                });
            } catch(e){ }
        });
    });
</script>