<div class="my_measurements">
	<div class="page-title">
        <h1>My Measurements</h1>
    </div>
    <div class="pending_measurements_to_submit"></div>
    <div class="add_new_measurements"><a class="add_new" href="<?php echo Mage::getBaseUrl(); ?>measurement/stored/add">Add New Measurements</a></div>
    <div class="pstored_measurements">
    	<?php $customer = Mage::getSingleton('customer/session')->getCustomer();
    	$storedCollection = Mage::getModel('measurementremember/measurementremember')->getCollection()
    													->addFieldToFilter('c_id', $customer->getId())
    													->addFieldToFilter('account', 1)
    													->setOrder('created_time', DESC);
        if (sizeof($storedCollection) > 0) { ?>
            <table id="my-measurements-table" class="data-table">
                <thead>
                    <tr class="first last">
                        <th>Name</th>
                        <th>Created/Modified On</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    <?php $i = 1;
                    foreach ($storedCollection as $_measurement) { ?>
                        <tr class="<?php if ($i == 1) {echo 'first'; } ?> <?php if ($i == sizeof($storedCollection)) {echo 'last'; } ?> <?php if($i % 2 == 0){ echo 'even'; } else{ echo 'odd'; } ?>" ><td><?php echo $_measurement->getTitle(); ?></td><td><?php echo $_measurement->getUpdateTime(); ?></td><td><label class="left"><a href="<?php echo Mage::getBaseUrl(); ?>measurement/stored/edit?id=<?php echo $_measurement->getMeasurementrememberId(); ?>">Edit</a></label><label class="right"><a href="<?php echo Mage::getBaseUrl(); ?>measurement/stored/delete?id=<?php echo $_measurement->getMeasurementrememberId(); ?>">Delete</a></label></td></tr>
                    <?php $i++; } ?>
                </tbody>
            </table>
        <?php } else{ ?>
            <p>There no measurements stored in your account</p>
        <?php } ?>
    </div>
</div>
<style type="text/css">
.data-table .right {
    float: right;
    padding: 0 5%;
    width: 40%;
}
.data-table .left {
    float: left;
    padding: 0 5%;
    width: 40%;
}
.add_new {
    background: gray none repeat scroll 0 0;
    border: medium none;
    color: #fff;
    float: right;
    font-size: 14px;
    font-weight: bold;
    line-height: 25px;
    padding: 0 10px;
}
.add_new:hover {
    color: #fff;
}
.add_new_measurements {
    height: 25px !important;
    padding: 5px;
}
</style>