<?php
	if (is_ajax()) {
		if (isset($_POST["stitching_service_id"]) && !empty($_POST["stitching_service_id"])) { //Checks if action value exists
			$read = Mage::getSingleton('core/resource')->getConnection('core_read');
			$response = $read->fetchAll('SELECT `style_id`,`title` FROM `measurement_front_styles` WHERE `stitching_service_id` = '.$_POST['stitching_service_id']); ?>
			<select id="front_id" name="front_id" class="required-entry select">
				<option>--- Please Select ---</option>
				<?php foreach ($response as $key => $value) { ?>
					<option value="<?php echo $value['style_id']; ?>"><?php echo $value['title']; ?></option>
				<?php } ?>
			</select>
		<?php }
	}

	function is_ajax() {
		return isset($_SERVER['HTTP_X_REQUESTED_WITH']) && strtolower($_SERVER['HTTP_X_REQUESTED_WITH']) == 'xmlhttprequest';
	}	
?>
<script type="text/javascript">
	var jQuery = jQuery.noConflict();
	jQuery("#front_id").change(function () {
		var data = "front="+this.value;
		jQuery.ajax({
			url: '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB);?>sleeves/index/index',
			type : 'post',
			data: data,
			success: function(data){
					jQuery('select#back_id').replaceWith(data);
			}
		});
	});
</script>