<div class="options_submitting_measurement">
	<?php 
		$front = Mage::getModel('styles/styles')->getCollection()->addFieldToSelect('measurement_attr')->addFieldToFilter('style_id',$_REQUEST['front_id'])->addFieldToFilter('status',1)->getFirstItem();
		$back = Mage::getModel('back/back')->getCollection()->addFieldToSelect('measurement_attr')->addFieldToFilter('back_id',$_REQUEST['back_id'])->addFieldToFilter('status',1)->getFirstItem();
		$sleeve = Mage::getModel('sleeves/sleeves')->getCollection()->addFieldToSelect('measurement_attr')->addFieldToFilter('sleeves_id',$_REQUEST['sleeve_id'])->addFieldToFilter('status',1)->getFirstItem();
		if(strlen($front['measurement_attr']) > 0) {
			$front_attr = explode(',', $front['measurement_attr']); ?>
			<div class="front_measurements">
				<div class="title">Front Measurements</div>
				<div class="front_measurement_details">
					<?php foreach ($front_attr as $key => $_front) {
						$_front1 = Mage::getModel('measurement/measurement')->load($_front);
						$min = $_front1->getMinVal();
						$max = $_front1->getMaxVal();
						$difference = $_front1->getDifference(); ?>
						<div><label><?php echo $_front1->getTitle(); ?></label>
							<?php if($_front1->getFieldType() == 'radio') { ?>
								<!-- <input type="<?php echo $_front1->getFieldType(); ?>" name="<?php echo $_front1->getMeasurementId(); ?>" > -->
							<?php } elseif($_front1->getFieldType() == 'text_area') {
								// echo 'Text Area';
							}elseif($_front1->getFieldType() == 'text_field') { ?>
								<input class="measurement_textfield" type="number" step="<?php echo $difference; ?>" name="<?php echo $_front1->getMeasurementId(); ?>" min="<?php echo $min; ?>" max="<?php echo $max; ?>" >
							<?php }elseif($_front1->getFieldType() == 'dropdown') { ?>
								<select name="<?php echo $_front1->getMeasurementId(); ?>">
									<option>--- Select ---</option>
									<?php while($min <= $max) { ?>
										<option><?php echo $min; ?></option>
										<?php $min += $difference;
									} ?>
								</select>
							<?php } ?>
						</div>

					<?php } ?>
				</div>
			</div>

		<?php }
		if(strlen($back['measurement_attr']) > 0) {
			// print_r($back['measurement_attr']);
			$back_attr = explode(',', $back['measurement_attr']); ?>
			<div class="back_measurements">
				<div class="title">Back Measurements</div>
				<div class="back_measurement_details">
					<?php foreach ($back_attr as $key => $_back) {
						$_back1 = Mage::getModel('measurement/measurement')->load($_back);
						$min = $_back1->getMinVal();
						$max = $_back1->getMaxVal();
						$difference = $_back1->getDifference(); ?>
						<div><label><?php echo $_back1->getTitle(); ?></label>
							<?php if($_back1->getFieldType() == 'radio') { ?>
								<!-- <input type="<?php echo $_back1->getFieldType(); ?>" name="<?php echo $_back1->getMeasurementId(); ?>" > -->
							<?php } elseif($_back1->getFieldType() == 'text_area') {
								// echo 'Text Area';
							}elseif($_back1->getFieldType() == 'text_field') { ?>
								<input class="measurement_textfield" type="number" step="<?php echo $difference; ?>" name="<?php echo $_back1->getMeasurementId(); ?>" min="<?php echo $min; ?>" max="<?php echo $max; ?>" >
							<?php }elseif($_back1->getFieldType() == 'dropdown') { ?>
								<select name="<?php echo $_back1->getMeasurementId(); ?>">
									<option>--- Select ---</option>
									<?php while($min <= $max) { ?>
										<option><?php echo $min; ?></option>
										<?php $min += $difference;
									} ?>
								</select>
							<?php } ?>
						</div>

					<?php } ?>
				</div>
			</div>
		<?php }
		if(strlen($sleeve['measurement_attr']) > 0) {
			// print_r($sleeve['measurement_attr']);
			$sleeve_attr = explode(',', $sleeve['measurement_attr']); ?>
			<div class="sleeve_measurements">
				<div class="title">Sleeve Measurements</div>
				<div class="sleeve_measurement_details">
					<?php foreach ($sleeve_attr as $key => $_sleeve) {
						$_sleeve1 = Mage::getModel('measurement/measurement')->load($_sleeve);
						$min = $_sleeve1->getMinVal();
						$max = $_sleeve1->getMaxVal();
						$difference = $_sleeve1->getDifference(); ?>
						<div><label><?php echo $_sleeve1->getTitle(); ?></label>
							<?php if($_sleeve1->getFieldType() == 'radio') { ?>
								<!-- <input type="<?php echo $_sleeve1->getFieldType(); ?>" name="<?php echo $_sleeve1->getMeasurementId(); ?>" > -->
							<?php } elseif($_sleeve1->getFieldType() == 'text_area') {
								// echo 'Text Area';
							}elseif($_sleeve1->getFieldType() == 'text_field') { ?>
								<input class="measurement_textfield" type="number" step="<?php echo $difference; ?>" name="<?php echo $_sleeve1->getMeasurementId(); ?>" min="<?php echo $min; ?>" max="<?php echo $max; ?>" >
							<?php }elseif($_sleeve1->getFieldType() == 'dropdown') { ?>
								<select name="<?php echo $_sleeve1->getMeasurementId(); ?>">
									<option>--- Select ---</option>
									<?php while($min <= $max) { ?>
										<option><?php echo $min; ?></option>
										<?php $min += $difference;
									} ?>
								</select>
							<?php } ?>
						</div>

					<?php } ?>
				</div>
			</div>
		<?php }
	?>
</div>