<div class="measure_details">
	<div id="review" class="measure_detail">
		<div class="label_title"><label> Review</label></div>
		<div id="measurement_step" class="measurement_review">
		<?php 
		// $_REQUEST['existing_measurement_id'] = 23;
		// $_REQUEST['product_id'] = 5;
		// $_REQUEST['service'] = 3;
		// $_REQUEST['stitching_type'] = 9;
		$measurementremember = Mage::getModel('measurementremember/measurementremember')->load($_REQUEST['existing_measurement_id']);
		$measurementremember1 = Mage::getModel('measurementremember/flatrates')->getCollection()->addFieldToFilter('measurementremember_id',$measurementremember->getMeasurementrememberId())->getFirstItem();
			echo '<div class=review_selected_style><ul class=ul_review_selected_style>';
					if($measurementremember1->getBackId() > 0) {
						$front = Mage::getModel('styles/styles')->getCollection()->addFieldToSelect('*')->addFieldToFilter('style_id',$measurementremember1->getFrontId())->addFieldToFilter('status',1)->getFirstItem(); ?>
						<li class=li_review_selected_style>
							<div class="selected_style_image"><img width=200 height=300 alt="<?php echo $front->getTitle(); ?>" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$front->getImage(); ?>"></div>
							<div class="selected_style_measurements">
								<?php $front_smeasurements = explode(',', $front->getMeasurementAttr());
								foreach ($front_smeasurements as $value) {
									$measurement = Mage::getModel('measurement/measurement')->getCollection()->addFieldToSelect('*')->addFieldToFilter('measurement_id',$value)->addFieldToFilter('status',1)->getFirstItem(); ?>
									<div class="review_your_measurements1">
										<label class="label"><b><?php echo $measurement->getTitle().' : '; ?></b></label>
										<?php if($measurement->getDropdownType() == 'custom'){
											$customtitles = Mage::getModel('measurement/customtitles')->load($measurementremember1->{'get' . $value}());
											$final_value = $customtitles->getTitle();
										}else{
											if($measurement->getFieldType() == 'text_area'){
												$final_value = $measurementremember1->{'get' . $value}();
											}else{
												$final_value = $measurementremember1->{'get' . $value}().' '.$measurementremember1->getMeasurmentUnits();
											}
										} ?>
										<label class="value"><?php echo $final_value; ?></label>
									</div>
								<?php } ?>
							</div>
						</li>
					<?php } ?>
					<?php if($measurementremember1->getBackId() > 0) {
						$back = Mage::getModel('back/back')->getCollection()->addFieldToSelect('*')->addFieldToFilter('back_id',$measurementremember1->getBackId())->addFieldToFilter('status',1)->getFirstItem(); ?>
						<li class=li_review_selected_style>
							<div class="selected_style_image"><img width=200 height=300 alt="<?php echo $back->getTitle(); ?>" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$back->getImage(); ?>"></div>
								<div class="selected_style_measurements">
									<?php $back_smeasurements = explode(',', $back->getMeasurementAttr());
									foreach ($back_smeasurements as $value) {
										$measurement = Mage::getModel('measurement/measurement')->getCollection()->addFieldToSelect('*')->addFieldToFilter('measurement_id',$value)->addFieldToFilter('status',1)->getFirstItem(); ?>
										<div class="review_your_measurements1">
											<label class="label"><b><?php echo $measurement->getTitle().' : '; ?></b></label>
											<?php if($measurement->getDropdownType() == 'custom'){
												$customtitles = Mage::getModel('measurement/customtitles')->load($measurementremember1->{'get' . $value}());
												$final_value = $customtitles->getTitle();
											}else{
												if($measurement->getFieldType() == 'text_area'){
													$final_value = $measurementremember1->{'get' . $value}();
												}else{
													$final_value = $measurementremember1->{'get' . $value}().' '.$measurementremember1->getMeasurmentUnits();
												}
											} ?>
											<label class="value"><?php echo $final_value; ?></label>
										</div>
									<?php } ?>
								</div>
						</li>
					<?php } ?>
					<?php if($measurementremember1->getSleeveId() > 0) {
						$sleeve = Mage::getModel('sleeves/sleeves')->getCollection()->addFieldToSelect('*')->addFieldToFilter('sleeves_id',$measurementremember1->getSleeveId())->addFieldToFilter('status',1)->getFirstItem(); ?>
						<li class=li_review_selected_style>
							<div class="selected_style_image"><img width=200 height=300 alt="<?php echo $sleeve->getTitle(); ?>" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$sleeve->getImage(); ?>"></div>
								<div class="selected_style_measurements">
									<?php $sleeve_smeasurements = explode(',', $sleeve->getMeasurementAttr());
									foreach ($sleeve_smeasurements as $value) {
										$measurement = Mage::getModel('measurement/measurement')->getCollection()->addFieldToSelect('*')->addFieldToFilter('measurement_id',$value)->addFieldToFilter('status',1)->getFirstItem(); ?>
										<div class="review_your_measurements1">
											<label class="label"><b><?php echo $measurement->getTitle().' : '; ?></b></label>
											<?php if($measurement->getDropdownType() == 'custom'){
												$customtitles = Mage::getModel('measurement/customtitles')->load($measurementremember1->{'get' . $value}());
												$final_value = $customtitles->getTitle();
											}else{
												if($measurement->getFieldType() == 'text_area'){
													$final_value = $measurementremember1->{'get' . $value}();
												}else{
													$final_value = $measurementremember1->{'get' . $value}().' '.$measurementremember1->getMeasurmentUnits();
												}
											} ?>
											<label class="value"><?php echo $final_value; ?></label>
										</div>
									<?php } ?>
							</div>
						</li>
					<?php } ?>
					<?php if($measurementremember1->getLehangaId() > 0) {
						$lehanga = Mage::getModel('lehanga/lehanga')->getCollection()->addFieldToSelect('*')->addFieldToFilter('lehanga_id',$measurementremember1->getLehangaId())->addFieldToFilter('status',1)->getFirstItem(); ?>
						<li class=li_review_selected_style>
							<div class="selected_style_image"><img width=200 height=300 alt="<?php echo $lehanga->getTitle(); ?>" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$lehanga->getImage(); ?>"></div>
								<div class="selected_style_measurements">
									<?php $lehanga_smeasurements = explode(',', $lehanga->getMeasurementAttr());
									foreach ($lehanga_smeasurements as $value) {
										$measurement = Mage::getModel('measurement/measurement')->getCollection()->addFieldToSelect('*')->addFieldToFilter('measurement_id',$value)->addFieldToFilter('status',1)->getFirstItem(); ?>
										<div class="review_your_measurements1">
											<label class="label"><b><?php echo $measurement->getTitle().' : '; ?></b></label>
											<?php if($measurement->getDropdownType() == 'custom'){
												$customtitles = Mage::getModel('measurement/customtitles')->load($measurementremember1->{'get' . $value}());
												$final_value = $customtitles->getTitle();
											}else{
												if($measurement->getFieldType() == 'text_area'){
													$final_value = $measurementremember1->{'get' . $value}();
												}else{
													$final_value = $measurementremember1->{'get' . $value}().' '.$measurementremember1->getMeasurmentUnits();
												}
											} ?>
											<label class="value"><?php echo $final_value; ?></label>
										</div>
									<?php } ?>
								</div>
						</li>
					<?php } ?>
					<?php if($measurementremember1->getSalwarId() > 0) {
						$salwar = Mage::getModel('salwar/salwar')->getCollection()->addFieldToSelect('*')->addFieldToFilter('salwar_id',$measurementremember1->getSalwarId())->addFieldToFilter('status',1)->getFirstItem(); ?>
						<li class=li_review_selected_style>
							<div class="selected_style_image"><img width=200 height=300 alt="<?php echo $salwar->getTitle(); ?>" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$salwar->getImage(); ?>"></div>
								<div class="selected_style_measurements">
									<?php $salwar_smeasurements = explode(',', $salwar->getMeasurementAttr());
									foreach ($salwar_smeasurements as $value) {
										$measurement = Mage::getModel('measurement/measurement')->getCollection()->addFieldToSelect('*')->addFieldToFilter('measurement_id',$value)->addFieldToFilter('status',1)->getFirstItem(); ?>
										<div class="review_your_measurements1">
											<label class="label"><b><?php echo $measurement->getTitle().' : '; ?></b></label>
											<?php if($measurement->getDropdownType() == 'custom'){
												$customtitles = Mage::getModel('measurement/customtitles')->load($measurementremember1->{'get' . $value}());
												$final_value = $customtitles->getTitle();
											}else{
												if($measurement->getFieldType() == 'text_area'){
													$final_value = $measurementremember1->{'get' . $value}();
												}else{
													$final_value = $measurementremember1->{'get' . $value}().' '.$measurementremember1->getMeasurmentUnits();
												}
											} ?>
											<label class="value"><?php echo $final_value; ?></label>
										</div>
									<?php } ?>
								</div>
						</li>
					<?php } ?>
					<?php if($measurementremember1->getTasselId() > 0) {
						$tassel = Mage::getModel('tassel/tassel')->getCollection()->addFieldToSelect('*')->addFieldToFilter('tassel_id',$measurementremember1->getTasselId())->addFieldToFilter('status',1)->getFirstItem(); ?>
						<li class=li_review_selected_style>
							<div class="selected_style_image"><img width=200 height=300 alt="<?php echo $tassel->getTitle(); ?>" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$tassel->getImage(); ?>"></div>
							<div class="selected_style_measurements">
								<?php $tassel_smeasurements = explode(',', $tassel->getMeasurementAttr());
								foreach ($tassel_smeasurements as $value) {
									$measurement = Mage::getModel('measurement/measurement')->getCollection()->addFieldToSelect('*')->addFieldToFilter('measurement_id',$value)->addFieldToFilter('status',1)->getFirstItem(); ?>
									<div class="review_your_measurements1">
										<label class="label"><b><?php echo $measurement->getTitle().' : '; ?></b></label>
										<?php if($measurement->getDropdownType() == 'custom'){
											$customtitles = Mage::getModel('measurement/customtitles')->load($measurementremember1->{'get' . $value}());
											$final_value = $customtitles->getTitle();
										}else{
											if($measurement->getFieldType() == 'text_area'){
												$final_value = $measurementremember1->{'get' . $value}();
											}else{
												$final_value = $measurementremember1->{'get' . $value}().' '.$measurementremember1->getMeasurmentUnits();
											}
										} ?>
										<label class="value"><?php echo $final_value; ?></label>
									</div>
								<?php } ?>
							</div>
						</li>
					<?php } ?>
				</ul>
			</div>
		<div class="goto_nextstep" style="display: block;"><a  class="edit_measurements" href="<?php echo Mage::getBaseUrl().'measurement?product_id='.$_REQUEST['product_id'].'&measurement_id='.$_REQUEST['existing_measurement_id'].'&stitching_type='.$_REQUEST['stitching_type']; ?>" >Edit & Submit</a><button id="submit_measurements" class="take_measurement" type="submit">Submit</button></div>
		</div>
	</div>
</div>
<script type="text/javascript">
    var jQuery = jQuery.noConflict();
    jQuery(function(){
    	responsive();
		jQuery(window).resize(function() {
			responsive();
		});
		function responsive(){
			var windowWidth = jQuery(window).width();
			var count = jQuery(".measurement_review ul.ul_review_selected_style").children('.li_review_selected_style').length;
			if(windowWidth >= 960){
				if(count == 5){
					jQuery('.measurement_review ul.ul_review_selected_style').find('li.li_review_selected_style').each(function(){
						jQuery(this).find('img:first').attr('style','');
						jQuery(this).find('div.selected_style_measurements:first').attr('style','');
						jQuery(this).css("width","20%");
					});
				}else  if(count == 4){
					jQuery('.measurement_review ul.ul_review_selected_style').find('li.li_review_selected_style').each(function(){
						jQuery(this).find('img:first').attr('style','');
						jQuery(this).find('div.selected_style_measurements:first').attr('style','');
						jQuery(this).css("width","25%");
					});
				} else if(count == 3){
					jQuery('.measurement_review ul.ul_review_selected_style').find('li.li_review_selected_style').each(function(){
						jQuery(this).find('img:first').attr('style','');
						jQuery(this).find('div.selected_style_measurements:first').attr('style','');
						jQuery(this).css("width","33.33%");
					});
				} else if(count == 2){
					jQuery('.measurement_review ul.ul_review_selected_style').find('li.li_review_selected_style').each(function(){
						jQuery(this).find('img:first').attr('style','');
						jQuery(this).find('div.selected_style_measurements:first').attr('style','');
						jQuery(this).css("width","50%");
					});
				} else if(count == 1){
					jQuery('.measurement_review ul.ul_review_selected_style').find('li.li_review_selected_style').each(function(){
						jQuery(this).find('img:first').attr('style','');
						jQuery(this).find('div.selected_style_measurements:first').attr('style','');
						jQuery(this).css("width","100%");
					});
				}
			}else if(windowWidth < 960 && windowWidth >= 480){
				var i = 1;
				jQuery('.measurement_review ul.ul_review_selected_style').find('li.li_review_selected_style').each(function(){
					if (count % 2 != 0 && count == i) {
						jQuery(this).find('img:first').attr('style','');
						jQuery(this).find('div.selected_style_measurements:first').attr('style','');
						jQuery(this).css("width","100%");
						jQuery(this).find('img:first').css('float','left');
						jQuery(this).find('img:first').css('width','40%');
						jQuery(this).find('img:first').css('margin-right','5%');
						jQuery(this).find('div.selected_style_measurements:first').css('float','left');
					}else{
						i++;
						jQuery(this).find('img:first').attr('style','');
						jQuery(this).find('div.selected_style_measurements:first').attr('style','');
						jQuery(this).css("width","50%");
					}
				});
			}else if(windowWidth < 480){
				jQuery('.measurement_review ul.ul_review_selected_style').find('li.li_review_selected_style').each(function(){
					jQuery(this).find('img:first').attr('style','');
					jQuery(this).find('div.selected_style_measurements:first').attr('style','');
					jQuery(this).css("width","100%");
				});
			}
		}
    });
</script>