<?php
    $url= $_SERVER['REQUEST_URI'];
    $urlarr=explode('/id/',$url);
    $myid= explode('/',$urlarr[1]);
	$attrid = $myid[0];
    $measurement = Mage::getSingleton('measurementremember/measurementremember')->getCollection()->addFieldToFilter('measurementremember_id',$attrid)->getFirstItem();
    if(!empty($attrid)){
    	$flatrates = Mage::getSingleton('measurementremember/flatrates')->getCollection()->addFieldToFilter('measurementremember_id',$attrid)->getFirstItem();
    	$flatrates1 = $flatrates->getData();
    	$cat_id_val = Mage::getResourceModel('measurementremember/measurementremember_collection')->addFieldToFilter('measurementremember_id',$attrid)->getFirstItem();
    	$collection = Mage::getModel('stitchingservices/stitchingservices')->getCollection()->addFieldToFilter('stitching_service_id',$measurement->getStitchingServiceId())->addFieldToFilter('status',1)->addFieldToFilter('stitching_service_price', array('gt' => '0.00'));
    }
    $attribute = Mage::getSingleton('eav/config')->getAttribute('catalog_product', 'a27');
	if ($attribute->usesSource()) {
		$stitchings = $attribute->getSource()->getAllOptions(false);
	}
?>
<table cellspacing="0" class="form-list">
	<tbody>
		<?php if(!empty($attrid)){ ?>
			<tr>
				<td class="label"><label for="title">Preview </label></td>
				<td class="value">
					<button class="scalable" type="button" title="Preview" id="preview" onclick="popup('<?php echo Mage::getBaseUrl(); ?>measurementremember/index/preview?id=<?php echo $attrid; ?>')"><span><span><span>Preview</span></span></span></button>
				</td>
			</tr>
		<?php } ?>
		<tr>
			<td class="label"><label for="title">Title <span class="required">*</span></label></td>
			<td class="value">
				<input type="text" class="required-entry input-text required-entry" value="<?php echo $measurement->getTitle(); ?>" name="title" id="title">
			</td>
		</tr>
		<tr>
			<td class="label"><label for="quote_id">Quote ID <span class="required">*</span></label></td>
			<td class="value">
				<input type="text" class="required-entry input-text required-entry" value="<?php echo $measurement->getQuoteId(); ?>" name="quote_id" id="quote_id">
			</td>
		</tr>
		<tr>
			<td class="label"><label for="increment_id">Order ID <span class="required">*</span></label></td>
			<td class="value">
				<input type="text" class="required-entry input-text required-entry" value="<?php echo $measurement->getIncrementId(); ?>" name="increment_id" id="increment_id">
			</td>
		</tr>
		<tr>
			<td class="label"><label for="sku">SKU <span class="required">*</span></label></td>
			<td class="value">
				<input type="text" class="required-entry input-text required-entry" value="<?php echo $measurement->getSku(); ?>" name="sku" id="sku">
			</td>
		</tr>
		<tr>
			<td class="label"><label for="product_id">Product ID <span class="required">*</span></label></td>
			<td class="value">
				<input type="text" class="required-entry input-text required-entry" value="<?php echo $measurement->getProductId(); ?>" name="product_id" id="product_id">
				<p id="note_product_id" class="note"><span>Catalog->Manage Products and search for Product by SKU, copy ID value and paste it here</span></p>
			</td>
		</tr>
		<tr>
			<td class="label"><label for="email">Email <span class="required">*</span></label></td>
			<td class="value">
				<input type="text" class="required-entry input-text required-entry" value="<?php echo $measurement->getEmail(); ?>" name="email" id="email">
			</td>
		</tr>
		<tr>
			<td class="label"><label for="c_id">Customer ID <span class="required">*</span></label></td>
			<td class="value">
				<input type="text" class="required-entry input-text required-entry" value="<?php echo $measurement->getCId(); ?>" name="c_id" id="c_id">
				<p id="note_c_id" class="note"><span>Customers->Manage Customers and search for Customer by Email ID, copy ID value and paste it here</span></p>
			</td>
		</tr>
		<tr>
			<td class="label"><label for="account">Customer Account</label></td>
			<td class="value">
				<select class="required-entry select" name="account" id="account">
					<option value="0">Do not Display in MyAccount</option>
					<option <?php if($measurement->getAccount() == 1){ echo 'selected'; } ?> value="1">Display in MyAccount</option>
				</select>
			</td>
		</tr>
		<tr>
			<td class="label"><label for="stitching_service_id">Stitching Service <span class="required">*</span></label></td>
			<td class="value">
				<select class="required-entry select" name="stitching_service_id" id="stitching_service_id">
					<option>--- Please Select Option ---</option>
					<?php foreach ($stitchings as $key => $value) { ?>
						<option value="<?php echo $value['value']; ?>" <?php if($measurement->getStitchingServiceId() == $value['value']){ echo 'selected'; }?> ><?php echo $value['label']; ?></option>
					<?php } ?>
				</select>
			</td>
		</tr>
		<tr>
			<td class="label"><label for="stitching_type">Stitching Service Type <span class="required">*</span></label></td>
			<td class="value">
				<select class="required-entry select" name="stitching_type" id="stitching_type">
					<?php if (sizeof($collection) > 0) {
						echo '<option>--- Select Option ---</option>';
						foreach ($collection as $key => $value) { ?>
							<option value="<?php echo $value->getStitchingservicesId(); ?>" <?php if($measurement->getStitchingType() == $value->getStitchingservicesId()){ echo 'selected'; }?> ><?php echo $value->getTitle().' - Rs '.$value->getStitchingServicePrice(); ?></option>
						<?php }
					} else{ ?>
						<option>--- Please Select Option from above Dropdown ---</option>
					<?php } ?>
				</select>
			</td>
		</tr>
		<?php if(sizeof($flatrates1) > 0){ ?>
			<tr>
				<td class="label"><label for="measurment_units">Measurement Units</label></td>
				<td class="value">
					<input type="text" class="required-entry input-text required-entry" value="<?php echo $flatrates1['measurment_units']; ?>" name="attr[measurment_units]" id="measurment_units">
					<p id="note_measurment_units" class="note"><span>Case censitive (Please enter <b style="font-size:14px;">in</b> for <b style="font-size:12px;">Inchs</b> (or) <b style="font-size:14px;">cm</b> for <b style="font-size:12px;">Centemeters</b>)</span></p>
				</td>
			</tr>
		<?php } ?>
		<?php foreach ($flatrates1 as $key => $value) {
    		if (strlen($value) > 0 && $key > 0) {
    			$measurement_attr = Mage::getSingleton('measurement/measurement')->getCollection()->addFieldToFilter('measurement_id',$key)->getFirstItem();
    			$customtitles = Mage::getModel('measurement/customtitles')->getCollection()->addFieldToFilter('measurement_id',$measurement_attr->getMeasurementId());
				$min = $measurement_attr->getMinVal();
				$max = $measurement_attr->getMaxVal();
				if($flatrates1['measurment_units'] == 'cm'){ 
					$unit = 2.54;
					$min = round( ($min*$unit), 2);
					$min = 5 * round($min / 5, 2);
					$max = round( ($max*$unit), 2);
					$max = 5 * round($max / 5, 2);
				}
				$difference = $measurement_attr->getDifference(); ?>
    			<tr>
    				<td class="label"><label for="stitching_type"><?php echo $measurement_attr->getTitle(); ?> <?php if($measurement_attr->getIsRequired() == 1){echo '<span class="required">*</span>'; } ?></label></td>
    				<td class="value">
    					<?php if($measurement_attr->getFieldType() == 'radio') { ?>
							<?php foreach ($customtitles as $key => $_customtitle) { ?>
								<label class="radio_button"><input name="attr[<?php echo $measurement_attr->getMeasurementId(); ?>]" type="radio" value="<?php echo $_customtitle->getCustomTitleId(); ?>" /><?php echo $_customtitle->getTitle(); ?></label>
							<?php } ?>
						<?php } elseif($measurement_attr->getFieldType() == 'text_area') { ?>
							<label class="value">
								<textarea class="<?php if($measurement_attr->getIsRequired() == 1){ echo "required-entry"; } ?>" name="attr[<?php echo $measurement_attr->getMeasurementId(); ?>]" class="" cols="45" rows="3" style="resize: none;"></textarea>
							</label>
						<?php }elseif($measurement_attr->getFieldType() == 'text_field') { ?>
							<input class="input-text <?php if($measurement_attr->getIsRequired() == 1){ echo "required-entry"; } ?>" type="number" value="<?php echo $value; ?>" step="<?php echo $difference; ?>" name="attr[<?php echo $measurement_attr->getMeasurementId(); ?>]" min="<?php echo $min; ?>" max="<?php echo $max; ?>" >
						<?php }elseif($measurement_attr->getFieldType() == 'dropdown') {
							if($measurement_attr->getDropdownType() == 'standard') { ?>
							 	<select class="<?php if($measurement_attr->getIsRequired() == 1){ echo "required-entry"; } ?>" name="attr[<?php echo $measurement_attr->getMeasurementId(); ?>]">
									<option></option>
									<?php while($min <= $max) { ?>
										<option <?php if($value == $min){ echo 'selected'; } ?>><?php echo $min; ?></option>
										<?php $min += $difference;
									} ?>
								</select>
							 <?php }else if($measurement_attr->getDropdownType() == 'custom'){ ?>
							 	<select class="<?php if($measurement_attr->getIsRequired() == 1){ echo "required-entry"; } ?>" name="attr[<?php echo $measurement_attr->getMeasurementId(); ?>]">
									<option></option>
									<?php foreach ($customtitles as $key => $_customtitle) { ?>
										<option value="<?php echo $_customtitle->getCustomTitleId(); ?>" <?php if($value == $_customtitle->getCustomTitleId()){ echo 'selected'; } ?>><?php echo $_customtitle->getTitle(); ?></option>
									<?php } ?>
								</select>
							 <?php } ?>
						<?php } ?>

						<!-- <input type="text" class="required-entry input-text required-entry" value="<?php echo $value; ?>" name="attr[<?php echo $key; ?>]" id="<?php echo $key; ?>"> -->
					</td>
    			</tr>
    		<?php }
		} ?>
	</tbody>
</table>
<script src="http://code.jquery.com/jquery-latest.min.js" type="text/javascript"></script>
<script type="text/javascript">
	var jQuery = jQuery.noConflict();
	jQuery(function(){
		jQuery('#stitching_service_id').change(function() {
			var data1 = "&service="+this.value;
			var url1 = '<?php echo Mage::getBaseUrl(); ?>measurementremember/index/availstittypes';
			try {
				jQuery.ajax({
					url: url1,
					type : 'post',
					data: data1,
					success: function(response){
						if (response) {
							var string = response;
						} else{
							var string = '<select class="required-entry select" name="stitching_type" id="stitching_type"><option>--- Select Option ---</option></select>';
						}
						jQuery('#stitching_type').replaceWith(string);
					}
				});
			} catch(e){ }
		});
	});
</script>
<script>
	function popup(url) {
	    window.open(url, "_blank", "toolbar=no, scrollbars=yes, resizable=no, top=50, left=50, width=900");
	}
</script>