<?php
    $url= $_SERVER['REQUEST_URI'];
    $urlarr=explode('/id/',$url);
    $myid= explode('/',$urlarr[1]);
    $attrid = $myid[0];
    $fieldvalue = Mage::getModel('stitchingservices/stitchingservices')->getCollection()->addFieldToFilter('style_id',$attrid);
    $read = Mage::getSingleton('core/resource')->getConnection('core_read');
    if(!empty($attrid)){
    	$cat_id_val = Mage::getResourceModel('stitchingservices/stitchingservices_collection')->addFieldToFilter('style_id',$attrid)->getFirstItem();
    }
?>
<div>
	<div style="float:left;"><label>Category </label></div>
	<div style="padding-left: 210px;" class="category_dropdown">
		<select id="category" class="myinput-text required-entry widthinput" name="cat_id" >
			<option>--- Please Select ---</option>
			<?php if( (sizeof($cat_id_val["cat_id"]) > 0) && ($cat_id_val["cat_id"] == 0) ){ ?>
				<option value="0" selected>Default stitchingservices</option>
			<?php }else { ?>
				<option value="0">Default stitchingservices</option>
			<?php } 
			$rootcategories = Mage::getModel('catalog/category')->getCategories(Mage::getModel('core/store')->load(Mage_Core_Model_App::DISTRO_STORE_ID)->getRootCategoryId());
			foreach($rootcategories as $category){
				if($cat_id_val["cat_id"] == $category->getId()){ 
					echo "<option value =".$category->getId()." selected>".$category->getName()."</option>";
				}else {
					echo "<option value =".$category->getId()." >".$category->getName()."</option>";
				}
				$sub1rootcategories = Mage::getModel('catalog/category')->getCategories($category->getId());
				foreach ($sub1rootcategories as $category1) {
					if($cat_id_val["cat_id"] == $category1->getId()){ 
						echo "<option value =".$category1->getId()." selected> - ".$category1->getName()."</option>";
					}else {
						echo "<option value =".$category1->getId()." > - ".$category1->getName()."</option>";
					}
					$sub2rootcategories = Mage::getModel('catalog/category')->getCategories($category1->getId());
					foreach ($sub2rootcategories as $category2) {
						if($cat_id_val["cat_id"] == $category2->getId()){ 
							echo "<option value =".$category2->getId()." selected> - - ".$category2->getName()."</option>";
						}else {
							echo "<option value =".$category2->getId()." > - - ".$category2->getName()."</option>";
						}
						$sub3rootcategories = Mage::getModel('catalog/category')->getCategories($category2->getId());
						foreach ($sub3rootcategories as $category3) {
							if($cat_id_val["cat_id"] == $category3->getId()){ 
								echo "<option value =".$category3->getId()." selected> - - - ".$category3->getName()."</option>";
							}else {
								echo "<option value =".$category3->getId()." > - - - ".$category3->getName()."</option>";
							}							
						}
					}
				}
			} ?>								
		</select>
	</div>
</div>