<?php
    $url= $_SERVER['REQUEST_URI'];
    $urlarr=explode('/id/',$url);
    $myid= explode('/',$urlarr[1]);
    $attrid = $myid[0];
    $fieldvalue = Mage::getModel('taxrate/taxrate')->getCollection()->addFieldToFilter('taxrate_id',$attrid);
    $read = Mage::getSingleton('core/resource')->getConnection('core_read');
    $cat = array();
    if(!empty($attrid)){
    	$resource = Mage::getResourceModel('taxrate/flatrates_collection')->addFieldToFilter('taxrate_id',$attrid);
    	$cat_id_val = Mage::getResourceModel('taxrate/taxrate_collection')->addFieldToFilter('taxrate_id',$attrid)->getFirstItem();
    	$cat = explode(",",$cat_id_val["cat_id"]);
    }
    $catids1 = $read->fetchAll("SELECT cat_id FROM taxrate");
    foreach ($catids1 as $key => $value) {
    	$catids[] = $value['cat_id'];
    }
?>
<div>
	<div style="float:left;"><label>Country <span class="required">*</span></label></div>
	<div style="padding-left: 210px;" class="category_dropdown">
		<select  multiple id="category" class="myinput-text required-entry widthinput" name="cat_id[]" >
				<option value="AF" <?php if (in_array("AF", $cat)) { echo "selected"; } ?> >Afghanistan</option>
				<option value="AL" <?php if (in_array("AL", $cat)) { echo "selected"; } ?> >Albania</option>
				<option value="DZ" <?php if (in_array("DZ", $cat)) { echo "selected"; } ?> >Algeria</option>
				<option value="AS" <?php if (in_array("AS", $cat)) { echo "selected"; } ?> >American Samoa</option>
				<option value="AD" <?php if (in_array("AD", $cat)) { echo "selected"; } ?> >Andorra</option>
				<option value="AO" <?php if (in_array("AO", $cat)) { echo "selected"; } ?> >Angola</option>
				<option value="AI" <?php if (in_array("AI", $cat)) { echo "selected"; } ?> >Anguilla</option>
				<option value="AQ" <?php if (in_array("AQ", $cat)) { echo "selected"; } ?> >Antarctica</option>
				<option value="AG" <?php if (in_array("AG", $cat)) { echo "selected"; } ?> >Antigua and Barbuda</option>
				<option value="AR" <?php if (in_array("AR", $cat)) { echo "selected"; } ?> >Argentina</option>
				<option value="AM" <?php if (in_array("AM", $cat)) { echo "selected"; } ?> >Armenia</option>
				<option value="AW" <?php if (in_array("AW", $cat)) { echo "selected"; } ?> >Aruba</option>
				<option value="AU" <?php if (in_array("AU", $cat)) { echo "selected"; } ?> >Australia</option>
				<option value="AT" <?php if (in_array("AT", $cat)) { echo "selected"; } ?> >Austria</option>
				<option value="AZ" <?php if (in_array("AZ", $cat)) { echo "selected"; } ?> >Azerbaijan</option>
				<option value="BS" <?php if (in_array("BS", $cat)) { echo "selected"; } ?> >Bahamas</option>
				<option value="BH" <?php if (in_array("BH", $cat)) { echo "selected"; } ?> >Bahrain</option>
				<option value="BD" <?php if (in_array("BD", $cat)) { echo "selected"; } ?> >Bangladesh</option>
				<option value="BB" <?php if (in_array("BB", $cat)) { echo "selected"; } ?> >Barbados</option>
				<option value="BY" <?php if (in_array("BY", $cat)) { echo "selected"; } ?> >Belarus</option>
				<option value="BE" <?php if (in_array("BE", $cat)) { echo "selected"; } ?> >Belgium</option>
				<option value="BZ" <?php if (in_array("BZ", $cat)) { echo "selected"; } ?> >Belize</option>
				<option value="BJ" <?php if (in_array("BJ", $cat)) { echo "selected"; } ?> >Benin</option>
				<option value="BM" <?php if (in_array("BM", $cat)) { echo "selected"; } ?> >Bermuda</option>
				<option value="BT" <?php if (in_array("BT", $cat)) { echo "selected"; } ?> >Bhutan</option>
				<option value="BO" <?php if (in_array("BO", $cat)) { echo "selected"; } ?> >Bolivia</option>
				<option value="BA" <?php if (in_array("BA", $cat)) { echo "selected"; } ?> >Bosnia and Herzegovina</option>
				<option value="BW" <?php if (in_array("BW", $cat)) { echo "selected"; } ?> >Botswana</option>
				<option value="BV" <?php if (in_array("BV", $cat)) { echo "selected"; } ?> >Bouvet Island</option>
				<option value="BR" <?php if (in_array("BR", $cat)) { echo "selected"; } ?> >Brazil</option>
				<option value="IO" <?php if (in_array("IO", $cat)) { echo "selected"; } ?> >British Indian Ocean Territory</option>
				<option value="VG" <?php if (in_array("VG", $cat)) { echo "selected"; } ?> >British Virgin Islands</option>
				<option value="BN" <?php if (in_array("BN", $cat)) { echo "selected"; } ?> >Brunei</option>
				<option value="BG" <?php if (in_array("BG", $cat)) { echo "selected"; } ?> >Bulgaria</option>
				<option value="BF" <?php if (in_array("BF", $cat)) { echo "selected"; } ?> >Burkina Faso</option>
				<option value="BI" <?php if (in_array("BI", $cat)) { echo "selected"; } ?> >Burundi</option>
				<option value="KH" <?php if (in_array("KH", $cat)) { echo "selected"; } ?> >Cambodia</option>
				<option value="CM" <?php if (in_array("CM", $cat)) { echo "selected"; } ?> >Cameroon</option>
				<option value="CA" <?php if (in_array("CA", $cat)) { echo "selected"; } ?> >Canada</option>
				<option value="CV" <?php if (in_array("CV", $cat)) { echo "selected"; } ?> >Cape Verde</option>
				<option value="KY" <?php if (in_array("KY", $cat)) { echo "selected"; } ?> >Cayman Islands</option>
				<option value="CF" <?php if (in_array("CF", $cat)) { echo "selected"; } ?> >Central African Republic</option>
				<option value="TD" <?php if (in_array("TD", $cat)) { echo "selected"; } ?> >Chad</option>
				<option value="CL" <?php if (in_array("CL", $cat)) { echo "selected"; } ?> >Chile</option>
				<option value="CN" <?php if (in_array("CN", $cat)) { echo "selected"; } ?> >China</option>
				<option value="CX" <?php if (in_array("CX", $cat)) { echo "selected"; } ?> >Christmas Island</option>
				<option value="CC" <?php if (in_array("CC", $cat)) { echo "selected"; } ?> >Cocos [Keeling] Islands</option>
				<option value="CO" <?php if (in_array("CO", $cat)) { echo "selected"; } ?> >Colombia</option>
				<option value="KM" <?php if (in_array("KM", $cat)) { echo "selected"; } ?> >Comoros</option>
				<option value="CG" <?php if (in_array("CG", $cat)) { echo "selected"; } ?> >Congo - Brazzaville</option>
				<option value="CD" <?php if (in_array("CD", $cat)) { echo "selected"; } ?> >Congo - Kinshasa</option>
				<option value="CK" <?php if (in_array("CK", $cat)) { echo "selected"; } ?> >Cook Islands</option>
				<option value="CR" <?php if (in_array("CR", $cat)) { echo "selected"; } ?> >Costa Rica</option>
				<option value="HR" <?php if (in_array("HR", $cat)) { echo "selected"; } ?> >Croatia</option>
				<option value="CU" <?php if (in_array("CU", $cat)) { echo "selected"; } ?> >Cuba</option>
				<option value="CY" <?php if (in_array("CY", $cat)) { echo "selected"; } ?> >Cyprus</option>
				<option value="CZ" <?php if (in_array("CZ", $cat)) { echo "selected"; } ?> >Czech Republic</option>
				<option value="CI" <?php if (in_array("CI", $cat)) { echo "selected"; } ?> >Côte d’Ivoire</option>
				<option value="DK" <?php if (in_array("DK", $cat)) { echo "selected"; } ?> >Denmark</option>
				<option value="DJ" <?php if (in_array("DJ", $cat)) { echo "selected"; } ?> >Djibouti</option>
				<option value="DM" <?php if (in_array("DM", $cat)) { echo "selected"; } ?> >Dominica</option>
				<option value="DO" <?php if (in_array("DO", $cat)) { echo "selected"; } ?> >Dominican Republic</option>
				<option value="EC" <?php if (in_array("EC", $cat)) { echo "selected"; } ?> >Ecuador</option>
				<option value="EG" <?php if (in_array("EG", $cat)) { echo "selected"; } ?> >Egypt</option>
				<option value="SV" <?php if (in_array("SV", $cat)) { echo "selected"; } ?> >El Salvador</option>
				<option value="GQ" <?php if (in_array("GQ", $cat)) { echo "selected"; } ?> >Equatorial Guinea</option>
				<option value="ER" <?php if (in_array("ER", $cat)) { echo "selected"; } ?> >Eritrea</option>
				<option value="EE" <?php if (in_array("EE", $cat)) { echo "selected"; } ?> >Estonia</option>
				<option value="ET" <?php if (in_array("ET", $cat)) { echo "selected"; } ?> >Ethiopia</option>
				<option value="FK" <?php if (in_array("FK", $cat)) { echo "selected"; } ?> >Falkland Islands</option>
				<option value="FO" <?php if (in_array("FO", $cat)) { echo "selected"; } ?> >Faroe Islands</option>
				<option value="FJ" <?php if (in_array("FJ", $cat)) { echo "selected"; } ?> >Fiji</option>
				<option value="FI" <?php if (in_array("FI", $cat)) { echo "selected"; } ?> >Finland</option>
				<option value="FR" <?php if (in_array("FR", $cat)) { echo "selected"; } ?> >France</option>
				<option value="GF" <?php if (in_array("GF", $cat)) { echo "selected"; } ?> >French Guiana</option>
				<option value="PF" <?php if (in_array("PF", $cat)) { echo "selected"; } ?> >French Polynesia</option>
				<option value="TF" <?php if (in_array("TF", $cat)) { echo "selected"; } ?> >French Southern Territories</option>
				<option value="GA" <?php if (in_array("GA", $cat)) { echo "selected"; } ?> >Gabon</option>
				<option value="GM" <?php if (in_array("GM", $cat)) { echo "selected"; } ?> >Gambia</option>
				<option value="GE" <?php if (in_array("GE", $cat)) { echo "selected"; } ?> >Georgia</option>
				<option value="DE" <?php if (in_array("DE", $cat)) { echo "selected"; } ?> >Germany</option>
				<option value="GH" <?php if (in_array("GH", $cat)) { echo "selected"; } ?> >Ghana</option>
				<option value="GI" <?php if (in_array("GI", $cat)) { echo "selected"; } ?> >Gibraltar</option>
				<option value="GR" <?php if (in_array("GR", $cat)) { echo "selected"; } ?> >Greece</option>
				<option value="GL" <?php if (in_array("GL", $cat)) { echo "selected"; } ?> >Greenland</option>
				<option value="GD" <?php if (in_array("GD", $cat)) { echo "selected"; } ?> >Grenada</option>
				<option value="GP" <?php if (in_array("GP", $cat)) { echo "selected"; } ?> >Guadeloupe</option>
				<option value="GU" <?php if (in_array("GU", $cat)) { echo "selected"; } ?> >Guam</option>
				<option value="GT" <?php if (in_array("GT", $cat)) { echo "selected"; } ?> >Guatemala</option>
				<option value="GG" <?php if (in_array("GG", $cat)) { echo "selected"; } ?> >Guernsey</option>
				<option value="GN" <?php if (in_array("GN", $cat)) { echo "selected"; } ?> >Guinea</option>
				<option value="GW" <?php if (in_array("GW", $cat)) { echo "selected"; } ?> >Guinea-Bissau</option>
				<option value="GY" <?php if (in_array("GY", $cat)) { echo "selected"; } ?> >Guyana</option>
				<option value="HT" <?php if (in_array("HT", $cat)) { echo "selected"; } ?> >Haiti</option>
				<option value="HM" <?php if (in_array("HM", $cat)) { echo "selected"; } ?> >Heard Island and McDonald Islands</option>
				<option value="HN" <?php if (in_array("HN", $cat)) { echo "selected"; } ?> >Honduras</option>
				<option value="HK" <?php if (in_array("HK", $cat)) { echo "selected"; } ?> >Hong Kong SAR China</option>
				<option value="HU" <?php if (in_array("HU", $cat)) { echo "selected"; } ?> >Hungary</option>
				<option value="IS" <?php if (in_array("IS", $cat)) { echo "selected"; } ?> >Iceland</option>
				<option value="IN" <?php if (in_array("IN", $cat)) { echo "selected"; } ?> >India</option>
				<option value="ID" <?php if (in_array("ID", $cat)) { echo "selected"; } ?> >Indonesia</option>
				<option value="IR" <?php if (in_array("IR", $cat)) { echo "selected"; } ?> >Iran</option>
				<option value="IQ" <?php if (in_array("IQ", $cat)) { echo "selected"; } ?> >Iraq</option>
				<option value="IE" <?php if (in_array("IE", $cat)) { echo "selected"; } ?> >Ireland</option>
				<option value="IM" <?php if (in_array("IM", $cat)) { echo "selected"; } ?> >Isle of Man</option>
				<option value="IL" <?php if (in_array("IL", $cat)) { echo "selected"; } ?> >Israel</option>
				<option value="IT" <?php if (in_array("IT", $cat)) { echo "selected"; } ?> >Italy</option>
				<option value="JM" <?php if (in_array("JM", $cat)) { echo "selected"; } ?> >Jamaica</option>
				<option value="JP" <?php if (in_array("JP", $cat)) { echo "selected"; } ?> >Japan</option>
				<option value="JE" <?php if (in_array("JE", $cat)) { echo "selected"; } ?> >Jersey</option>
				<option value="JO" <?php if (in_array("JO", $cat)) { echo "selected"; } ?> >Jordan</option>
				<option value="KZ" <?php if (in_array("KZ", $cat)) { echo "selected"; } ?> >Kazakhstan</option>
				<option value="KE" <?php if (in_array("KE", $cat)) { echo "selected"; } ?> >Kenya</option>
				<option value="KI" <?php if (in_array("KI", $cat)) { echo "selected"; } ?> >Kiribati</option>
				<option value="KW" <?php if (in_array("KW", $cat)) { echo "selected"; } ?> >Kuwait</option>
				<option value="KG" <?php if (in_array("KG", $cat)) { echo "selected"; } ?> >Kyrgyzstan</option>
				<option value="LA" <?php if (in_array("LA", $cat)) { echo "selected"; } ?> >Laos</option>
				<option value="LV" <?php if (in_array("LV", $cat)) { echo "selected"; } ?> >Latvia</option>
				<option value="LB" <?php if (in_array("LB", $cat)) { echo "selected"; } ?> >Lebanon</option>
				<option value="LS" <?php if (in_array("LS", $cat)) { echo "selected"; } ?> >Lesotho</option>
				<option value="LR" <?php if (in_array("LR", $cat)) { echo "selected"; } ?> >Liberia</option>
				<option value="LY" <?php if (in_array("LY", $cat)) { echo "selected"; } ?> >Libya</option>
				<option value="LI" <?php if (in_array("LI", $cat)) { echo "selected"; } ?> >Liechtenstein</option>
				<option value="LT" <?php if (in_array("LT", $cat)) { echo "selected"; } ?> >Lithuania</option>
				<option value="LU" <?php if (in_array("LU", $cat)) { echo "selected"; } ?> >Luxembourg</option>
				<option value="MO" <?php if (in_array("MO", $cat)) { echo "selected"; } ?> >Macau SAR China</option>
				<option value="MK" <?php if (in_array("MK", $cat)) { echo "selected"; } ?> >Macedonia</option>
				<option value="MG" <?php if (in_array("MG", $cat)) { echo "selected"; } ?> >Madagascar</option>
				<option value="MW" <?php if (in_array("MW", $cat)) { echo "selected"; } ?> >Malawi</option>
				<option value="MY" <?php if (in_array("MY", $cat)) { echo "selected"; } ?> >Malaysia</option>
				<option value="MV" <?php if (in_array("MV", $cat)) { echo "selected"; } ?> >Maldives</option>
				<option value="ML" <?php if (in_array("ML", $cat)) { echo "selected"; } ?> >Mali</option>
				<option value="MT" <?php if (in_array("MT", $cat)) { echo "selected"; } ?> >Malta</option>
				<option value="MH" <?php if (in_array("MH", $cat)) { echo "selected"; } ?> >Marshall Islands</option>
				<option value="MQ" <?php if (in_array("MQ", $cat)) { echo "selected"; } ?> >Martinique</option>
				<option value="MR" <?php if (in_array("MR", $cat)) { echo "selected"; } ?> >Mauritania</option>
				<option value="MU" <?php if (in_array("MU", $cat)) { echo "selected"; } ?> >Mauritius</option>
				<option value="YT" <?php if (in_array("YT", $cat)) { echo "selected"; } ?> >Mayotte</option>
				<option value="MX" <?php if (in_array("MX", $cat)) { echo "selected"; } ?> >Mexico</option>
				<option value="FM" <?php if (in_array("FM", $cat)) { echo "selected"; } ?> >Micronesia</option>
				<option value="MD" <?php if (in_array("MD", $cat)) { echo "selected"; } ?> >Moldova</option>
				<option value="MC" <?php if (in_array("MC", $cat)) { echo "selected"; } ?> >Monaco</option>
				<option value="MN" <?php if (in_array("MN", $cat)) { echo "selected"; } ?> >Mongolia</option>
				<option value="ME" <?php if (in_array("ME", $cat)) { echo "selected"; } ?> >Montenegro</option>
				<option value="MS" <?php if (in_array("MS", $cat)) { echo "selected"; } ?> >Montserrat</option>
				<option value="MA" <?php if (in_array("MA", $cat)) { echo "selected"; } ?> >Morocco</option>
				<option value="MZ" <?php if (in_array("MZ", $cat)) { echo "selected"; } ?> >Mozambique</option>
				<option value="MM" <?php if (in_array("MM", $cat)) { echo "selected"; } ?> >Myanmar [Burma]</option>
				<option value="NA" <?php if (in_array("NA", $cat)) { echo "selected"; } ?> >Namibia</option>
				<option value="NR" <?php if (in_array("NR", $cat)) { echo "selected"; } ?> >Nauru</option>
				<option value="NP" <?php if (in_array("NP", $cat)) { echo "selected"; } ?> >Nepal</option>
				<option value="NL" <?php if (in_array("NL", $cat)) { echo "selected"; } ?> >Netherlands</option>
				<option value="AN" <?php if (in_array("AN", $cat)) { echo "selected"; } ?> >Netherlands Antilles</option>
				<option value="NC" <?php if (in_array("NC", $cat)) { echo "selected"; } ?> >New Caledonia</option>
				<option value="NZ" <?php if (in_array("NZ", $cat)) { echo "selected"; } ?> >New Zealand</option>
				<option value="NI" <?php if (in_array("NI", $cat)) { echo "selected"; } ?> >Nicaragua</option>
				<option value="NE" <?php if (in_array("NE", $cat)) { echo "selected"; } ?> >Niger</option>
				<option value="NG" <?php if (in_array("NG", $cat)) { echo "selected"; } ?> >Nigeria</option>
				<option value="NU" <?php if (in_array("NU", $cat)) { echo "selected"; } ?> >Niue</option>
				<option value="NF" <?php if (in_array("NF", $cat)) { echo "selected"; } ?> >Norfolk Island</option>
				<option value="KP" <?php if (in_array("KP", $cat)) { echo "selected"; } ?> >North Korea</option>
				<option value="MP" <?php if (in_array("MP", $cat)) { echo "selected"; } ?> >Northern Mariana Islands</option>
				<option value="NO" <?php if (in_array("NO", $cat)) { echo "selected"; } ?> >Norway</option>
				<option value="OM" <?php if (in_array("OM", $cat)) { echo "selected"; } ?> >Oman</option>
				<option value="PK" <?php if (in_array("PK", $cat)) { echo "selected"; } ?> >Pakistan</option>
				<option value="PW" <?php if (in_array("PW", $cat)) { echo "selected"; } ?> >Palau</option>
				<option value="PS" <?php if (in_array("PS", $cat)) { echo "selected"; } ?> >Palestinian Territories</option>
				<option value="PA" <?php if (in_array("PA", $cat)) { echo "selected"; } ?> >Panama</option>
				<option value="PG" <?php if (in_array("PG", $cat)) { echo "selected"; } ?> >Papua New Guinea</option>
				<option value="PY" <?php if (in_array("PY", $cat)) { echo "selected"; } ?> >Paraguay</option>
				<option value="PE" <?php if (in_array("PE", $cat)) { echo "selected"; } ?> >Peru</option>
				<option value="PH" <?php if (in_array("PH", $cat)) { echo "selected"; } ?> >Philippines</option>
				<option value="PN" <?php if (in_array("PN", $cat)) { echo "selected"; } ?> >Pitcairn Islands</option>
				<option value="PL" <?php if (in_array("PL", $cat)) { echo "selected"; } ?> >Poland</option>
				<option value="PT" <?php if (in_array("PT", $cat)) { echo "selected"; } ?> >Portugal</option>
				<option value="PR" <?php if (in_array("PR", $cat)) { echo "selected"; } ?> >Puerto Rico</option>
				<option value="QA" <?php if (in_array("QA", $cat)) { echo "selected"; } ?> >Qatar</option>
				<option value="RO" <?php if (in_array("RO", $cat)) { echo "selected"; } ?> >Romania</option>
				<option value="RU" <?php if (in_array("RU", $cat)) { echo "selected"; } ?> >Russia</option>
				<option value="RW" <?php if (in_array("RW", $cat)) { echo "selected"; } ?> >Rwanda</option>
				<option value="RE" <?php if (in_array("RE", $cat)) { echo "selected"; } ?> >Réunion</option>
				<option value="BL" <?php if (in_array("BL", $cat)) { echo "selected"; } ?> >Saint Barthélemy</option>
				<option value="SH" <?php if (in_array("SH", $cat)) { echo "selected"; } ?> >Saint Helena</option>
				<option value="KN" <?php if (in_array("KN", $cat)) { echo "selected"; } ?> >Saint Kitts and Nevis</option>
				<option value="LC" <?php if (in_array("LC", $cat)) { echo "selected"; } ?> >Saint Lucia</option>
				<option value="MF" <?php if (in_array("MF", $cat)) { echo "selected"; } ?> >Saint Martin</option>
				<option value="PM" <?php if (in_array("PM", $cat)) { echo "selected"; } ?> >Saint Pierre and Miquelon</option>
				<option value="VC" <?php if (in_array("VC", $cat)) { echo "selected"; } ?> >Saint Vincent and the Grenadines</option>
				<option value="WS" <?php if (in_array("WS", $cat)) { echo "selected"; } ?> >Samoa</option>
				<option value="SM" <?php if (in_array("SM", $cat)) { echo "selected"; } ?> >San Marino</option>
				<option value="SA" <?php if (in_array("SA", $cat)) { echo "selected"; } ?> >Saudi Arabia</option>
				<option value="SN" <?php if (in_array("SN", $cat)) { echo "selected"; } ?> >Senegal</option>
				<option value="RS" <?php if (in_array("RS", $cat)) { echo "selected"; } ?> >Serbia</option>
				<option value="SC" <?php if (in_array("SC", $cat)) { echo "selected"; } ?> >Seychelles</option>
				<option value="SL" <?php if (in_array("SL", $cat)) { echo "selected"; } ?> >Sierra Leone</option>
				<option value="SG" <?php if (in_array("SG", $cat)) { echo "selected"; } ?> >Singapore</option>
				<option value="SK" <?php if (in_array("SK", $cat)) { echo "selected"; } ?> >Slovakia</option>
				<option value="SI" <?php if (in_array("SI", $cat)) { echo "selected"; } ?> >Slovenia</option>
				<option value="SB" <?php if (in_array("SB", $cat)) { echo "selected"; } ?> >Solomon Islands</option>
				<option value="SO" <?php if (in_array("SO", $cat)) { echo "selected"; } ?> >Somalia</option>
				<option value="ZA" <?php if (in_array("ZA", $cat)) { echo "selected"; } ?> >South Africa</option>
				<option value="GS" <?php if (in_array("GS", $cat)) { echo "selected"; } ?> >South Georgia and the South Sandwich Islands</option>
				<option value="KR" <?php if (in_array("KR", $cat)) { echo "selected"; } ?> >South Korea</option>
				<option value="ES" <?php if (in_array("ES", $cat)) { echo "selected"; } ?> >Spain</option>
				<option value="LK" <?php if (in_array("LK", $cat)) { echo "selected"; } ?> >Sri Lanka</option>
				<option value="SD" <?php if (in_array("SD", $cat)) { echo "selected"; } ?> >Sudan</option>
				<option value="SR" <?php if (in_array("SR", $cat)) { echo "selected"; } ?> >Suriname</option>
				<option value="SJ" <?php if (in_array("SJ", $cat)) { echo "selected"; } ?> >Svalbard and Jan Mayen</option>
				<option value="SZ" <?php if (in_array("SZ", $cat)) { echo "selected"; } ?> >Swaziland</option>
				<option value="SE" <?php if (in_array("SE", $cat)) { echo "selected"; } ?> >Sweden</option>
				<option value="CH" <?php if (in_array("CH", $cat)) { echo "selected"; } ?> >Switzerland</option>
				<option value="SY" <?php if (in_array("SY", $cat)) { echo "selected"; } ?> >Syria</option>
				<option value="ST" <?php if (in_array("ST", $cat)) { echo "selected"; } ?> >São Tomé and Príncipe</option>
				<option value="TW" <?php if (in_array("TW", $cat)) { echo "selected"; } ?> >Taiwan</option>
				<option value="TJ" <?php if (in_array("TJ", $cat)) { echo "selected"; } ?> >Tajikistan</option>
				<option value="TZ" <?php if (in_array("TZ", $cat)) { echo "selected"; } ?> >Tanzania</option>
				<option value="TH" <?php if (in_array("TH", $cat)) { echo "selected"; } ?> >Thailand</option>
				<option value="TL" <?php if (in_array("TL", $cat)) { echo "selected"; } ?> >Timor-Leste</option>
				<option value="TG" <?php if (in_array("TG", $cat)) { echo "selected"; } ?> >Togo</option>
				<option value="TK" <?php if (in_array("TK", $cat)) { echo "selected"; } ?> >Tokelau</option>
				<option value="TO" <?php if (in_array("TO", $cat)) { echo "selected"; } ?> >Tonga</option>
				<option value="TT" <?php if (in_array("TT", $cat)) { echo "selected"; } ?> >Trinidad and Tobago</option>
				<option value="TN" <?php if (in_array("TN", $cat)) { echo "selected"; } ?> >Tunisia</option>
				<option value="TR" <?php if (in_array("TR", $cat)) { echo "selected"; } ?> >Turkey</option>
				<option value="TM" <?php if (in_array("TM", $cat)) { echo "selected"; } ?> >Turkmenistan</option>
				<option value="TC" <?php if (in_array("TC", $cat)) { echo "selected"; } ?> >Turks and Caicos Islands</option>
				<option value="TV" <?php if (in_array("TV", $cat)) { echo "selected"; } ?> >Tuvalu</option>
				<option value="UM" <?php if (in_array("UM", $cat)) { echo "selected"; } ?> >U.S. Minor Outlying Islands</option>
				<option value="VI" <?php if (in_array("VI", $cat)) { echo "selected"; } ?> >U.S. Virgin Islands</option>
				<option value="UG" <?php if (in_array("UG", $cat)) { echo "selected"; } ?> >Uganda</option>
				<option value="UA" <?php if (in_array("UA", $cat)) { echo "selected"; } ?> >Ukraine</option>
				<option value="AE" <?php if (in_array("AE", $cat)) { echo "selected"; } ?> >United Arab Emirates</option>
				<option value="GB" <?php if (in_array("GB", $cat)) { echo "selected"; } ?> >United Kingdom</option>
				<option value="US" <?php if (in_array("US", $cat)) { echo "selected"; } ?> >United States</option>
				<option value="UY" <?php if (in_array("UY", $cat)) { echo "selected"; } ?> >Uruguay</option>
				<option value="UZ" <?php if (in_array("UZ", $cat)) { echo "selected"; } ?> >Uzbekistan</option>
				<option value="VU" <?php if (in_array("VU", $cat)) { echo "selected"; } ?> >Vanuatu</option>
				<option value="VA" <?php if (in_array("VA", $cat)) { echo "selected"; } ?> >Vatican City</option>
				<option value="VE" <?php if (in_array("VE", $cat)) { echo "selected"; } ?> >Venezuela</option>
				<option value="VN" <?php if (in_array("VN", $cat)) { echo "selected"; } ?> >Vietnam</option>
				<option value="WF" <?php if (in_array("WF", $cat)) { echo "selected"; } ?> >Wallis and Futuna</option>
				<option value="EH" <?php if (in_array("EH", $cat)) { echo "selected"; } ?> >Western Sahara</option>
				<option value="YE" <?php if (in_array("YE", $cat)) { echo "selected"; } ?> >Yemen</option>
				<option value="ZM" <?php if (in_array("ZM", $cat)) { echo "selected"; } ?> >Zambia</option>
				<option value="ZW" <?php if (in_array("ZW", $cat)) { echo "selected"; } ?> >Zimbabwe</option>
				<option value="AX" <?php if (in_array("AX", $cat)) { echo "selected"; } ?> >Åland Islands</option>
		</select>
	</div>
</div>
<table class="attribute-label-table">
	<tr>
		<td>
			<?php echo $this->getElement()->getLabel() ?>
		</td>
	</tr>
</table>
<!-- <table id="attribute-options-table">
<tbody>
<tr>
	<th class="th">Total Cart Price From</th>
	<th class="th">Total Cart Price To</th>
	<th class="th">Choose Type</th>
	<th class="th">Value</th>
	<th class="th">
		<button id="add_new_option_button" title="Add Values" type="button" class="scalable add">
			<span><?php echo $this->__('Add Option') ?></span>
		</button>
	</th>
</tr>
<tr>
	<table class="attribute-label-table"><tr><td></td></tr></table>
	<table id="attribute-options-table1">
		<tbody> 
			<?php $maincount=0;
				foreach ($resource as $field) { ?>
					<tr id='<?php echo $maincount ?>' class="mytr"> 
						<td class="mytd"><input type="text" name='price_from<?php echo $maincount ?>' value="<?php echo $field['price_from']; ?>" class="required-entry "/></td>
						<td class="mytd"><input type="text" name='price_to<?php echo $maincount ?>' value="<?php echo $field['price_to']; ?>" class="required-entry "/></td>
						<td class="mytd"><select class='required-entry' name='type<?php echo $maincount ?>' value="<?php echo $field['type']; ?>" id="selectedval">
							<?php if($field['type'] == 'Fixed'): ?>
								<option id="1" selected="selected" value="Fixed">Fixed</option>
								<option id="2" value="Percentage" >Percentage</option>
							<?php endif; ?>
							<?php if($field['type'] == 'Percentage'): ?>
								<option id="1" value="Fixed">Fixed</option>
								<option id="2" selected="selected" value="Percentage" >Percentage</option>
							<?php endif; ?>
						</select>
						</td>
						<td class="mytd"><input type="text" name='percentage<?php echo $maincount ?>' value="<?php echo $field['percentage']; ?>" class="required-entry "/></td>
						<td class='a-left' id='delete_button_container_option_<?php echo $maincount ?>'>
							<button onclick='SomeDeleteRowFunction(this,<?php echo $field['autotaxrate_id']; ?>);' title='Delete' type='button' class='scalable delete delete-option'>
								<span>Delete</span>
							</button>
							<?php //echo $field['autotaxrate_id']; ?>
						</td>
						<td class="mytd"><input type="hidden" name='autotaxrate_id<?php echo $maincount ?>' value="<?php echo $field['autotaxrate_id']; ?>" class="required-entry "/></td>
					</tr>
			<?php $maincount++; } ?>                
			<input type="hidden" class="validate-autofill" id="count" name="counts" value="<?php echo $maincount ?>"/>
		</tbody>
	</table>
</tr>
</tbody>
</table> -->
<script type="text/javascript">
			var _form_html_row = "<tr id='{{id}}' class='mytr'><td><input type='text' name='price_from{{id}}' class='required-entry' value='' /></td><td><input type='text' name='price_to{{id}}' class='required-entry' value='' /></td><td><select class=' required-entry ' name='type{{id}}'><option id=1 >Fixed</option><option id=2 >Percentage</option></select></td><td><input type='text' name='percentage{{id}}' class='required-entry' value='' /></td><td class='a-left' id='delete_button_container_option_{{id}}'><button onclick='deleteRow({{id}});' title='Delete' type='button' class='scalable delete delete-option'><span>Delete</span></button><input type='hidden' name='count' value='{{id}}'/></td></tr>";
			$('add_new_option_button').observe('click', function(){
				var count=document.getElementById('count').value++  ;
				$('attribute-options-table').insert(_form_html_row.replace(/\{\{id\}\}/ig, count));
			});
			function deleteRow(rowid) {
				var row = document.getElementById(rowid);
				row.parentNode.remove();
				document.getElementById('count').value--  ;
			}
			function SomeDeleteRowFunction(o,autotaxrate_id) {
				var p=o.parentNode.parentNode;
				p.parentNode.removeChild(p);
				document.getElementById('count').value--  ;
			}
		</script>
<script>
	var index = 0;
	function myFunction() {
		var a1 = index++;
		var d1 = document.getElementById('one');
		d1.insertAdjacentHTML('beforeend', '<tr id=tr"'+a1+'"><td><input type="text" /></td><td><input type="text" /></td><td><select><option id=1 >Fixed</option><option id=2 >Percentage</option></select></td><td><input type="text" /></td><td><button onclick="myfunremove(this.id);" class="delete" type="button" title="Remove" id="'+a1+'"><span></span></button></td></tr>');
	}
	function myfunremove(a) {
		var val = document.getElementById(a).parentNode;
		val.remove();
	}
</script>
<style>
.attribute-label-table { width: 150px; float: left; }
#attribute-options-table { width: 750px; float: left; }
#attribute-options-table1 { width: 702px; }
.th{ width: 120px; }
.required-entry { width: 100px; }
.myinput-text.required-entry.widthinput { height: 250px; width: 280px; }
#category > option { height: 20px; padding-left: 10px; }
</style>