<?php
/**
* PHXSolution Mergeinfo
*
* NOTICE OF LICENSE
*
* This source file is subject to the Open Software License (OSL 3.0)
* that is bundled with this package in the file LICENSE.txt.
* It is also available through the world-wide-web at this URL:
* http://opensource.org/licenses/osl-3.0.php
* If you did not receive a copy of the license and are unable to
* obtain it through the world-wide-web, please send an email
* to license@magentocommerce.com so you can be sent a copy immediately.
*
* Original code copyright (c) 2008 Irubin Consulting Inc. DBA Varien
*
* @category   design
* @package    Phxsolution_Mergeinfo
* @author     Prakash Vaniya
* @contact    contact@phxsolution.com
* @site       www.phxsolution.com
* @copyright  Copyright (c) 2014 PHXSolution Mergeinfo
* @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
*/
?>

<style type="text/css">
.form-list .fields {
  margin-bottom: 10px;
}
.form-list .field {
  margin-bottom: 10px;
}
.form-list li.wide .input-box {
    width: 315px;
}
.form-list li.wide select {
    width: 315px;        
}
</style>
<form id="co-billing-form" action="">
<div class="col2-set">
    <div class="col-1">
        <h3><?php echo $this->__('Billing Info')?></h3>
        <fieldset>
            <ul class="form-list">
            <?php if ($this->customerHasAddresses()): ?>
                <li class="wide">
                    <div class="select_billing_address_title"><label for="billing-address-select"><?php echo $this->__('Select a billing address from your address book or enter a new address.') ?></label></div>
                    <div class="input-box" style="display: none;">
                        <?php echo $this->getAddressesHtmlSelect('billing') ?>
                    </div>
                    <div id="custAddress">
                        <?php $customerId = Mage::getSingleton('customer/session')->getCustomer();?>    
                        <?php $customer = Mage::getModel('customer/customer')->load($customerId->getId()); ?>
                        <?php $data = array();?>
                        <?php $i=0; foreach ($customer->getAddresses() as $address):?>
                            <?php $data = $address->toArray();?>
                            <div id="addresseList">
                                <a href="javaScript:void(0);" onclick="setBillingAddress(this.id)" id="<?php echo $i;?>">
                                   <address> 
                                      <div id="billing_selected_<?php echo $i;?>" class="billingselectedImage" style="float: right; margin: -6px; display: <?php if($customer->getPrimaryBillingAddress()->getId() == $data['entity_id']){ echo 'block'; } else{ echo 'none'; } ?>;"><img src="<?php echo $this->getSkinURl()?>images/right.jpg" /></div>
                                     <?php echo $data['firstname'].' '.$data['lastname'].'<br />';?>
                                     <?php echo $data['street'].'<br />';?>
                                     <?php echo $data['city'].','.$data['region'].','.$data['postcode'].'<br />';?>
                                     <?php $country_name = Mage::app()->getLocale()->getCountryTranslation($data['country_id']);?>
                                     <?php echo $country_name.'<br />';?>
                                      <?php echo 'T: '.$data['telephone'];?>
                                   </address>
                                   <?php if($customer->getPrimaryBillingAddress()->getId() != $data['entity_id']){ ?>
                                    <div id="addresseList1"><p>Use This</p></div>
                                   <?php } ?>
                                </a>
                             </div>
                         <?php $i++; endforeach; ?>  
                     </div>


                    <li id="addNewBillingAddress" class="new_address"><a href="javaScript:void(0);" onclick="setNewBillingAddress()"><?php echo $this->__('Click to Add New Address') ?></a></li>
                </li>
            <?php endif; ?>
            <li id="billing-new-address-form"<?php if ($this->customerHasAddresses()): ?> style="display:none;"<?php endif; ?>>
                <fieldset>
                    <input type="hidden" name="billing[address_id]" value="<?php echo $this->getAddress()->getId() ?>" id="billing:address_id" />
                    <ul>
                        <li class="fields"><?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getAddress()->getFirstname() ? $this->getAddress() : $this->getQuote()->getCustomer())->setForceUseCustomerRequiredAttributes(!$this->isCustomerLoggedIn())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
                            <?php if(!$this->isCustomerLoggedIn()): ?>
                                <div class="field">
                                    <label for="billing:email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                                    <div class="input-box">
                                        <input type="text" name="billing[email]" id="billing:email" value="<?php echo $this->escapeHtml($this->getAddress()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" />
                                    </div>
                                </div>
                            <?php endif; ?>
                        </li>
                <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
                        <li class="fields">
                            <div class="field">
                                <label for="billing:street1" class="required"><em>*</em><?php echo $this->__('Address') ?></label>
                                <div class="input-box">
                                    <input type="text" title="<?php echo $this->__('Street Address') ?>" name="billing[street][]" id="billing:street1" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>" class="input-text <?php echo $_streetValidationClass ?>" />
                                </div>
                            </div>
                            <div class="field">
                                <label for="billing:telephone" class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>
                                <div class="input-box">
                                    <input type="text" name="billing[telephone]" value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" id="billing:telephone" />
                                </div>
                            </div>
                        </li>
                <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                        <li class="fields">
                            <div class="input-box">
                                <input type="text" title="<?php echo $this->__('Street Address %s', $_i) ?>" name="billing[street][]" id="billing:street<?php echo $_i ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet($_i)) ?>" class="input-text <?php echo $_streetValidationClass ?>" />
                            </div>
                        </li>
                <?php endfor; ?>
                        <?php if ($this->helper('customer/address')->isVatAttributeVisible()) : ?>
                        <li class="fields">
                            <label for="billing:vat_id"><?php echo $this->__('VAT Number') ?></label>
                            <div class="input-box">
                                <input type="text" id="billing:vat_id" name="billing[vat_id]" value="<?php echo $this->escapeHtml($this->getAddress()->getVatId()) ?>" title="<?php echo $this->__('VAT Number') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('vat_id') ?>" />
                            </div>
                        </li>
                        <?php endif; ?>
                        <li class="fields">
                            <div class="field">
                                <label for="billing:postcode" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
                                <div class="input-box">
                                    <input type="text" title="<?php echo $this->__('Zip/Postal Code') ?>" name="billing[postcode]" id="billing:postcode" value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>" class="input-text validate-zip-international billing_zip <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" />
                                </div>
                            </div>
                            <div class="field" id="autofill_billing_city">
                                <label for="billing:city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
                                <div class="input-box">
                                    <input type="text" title="<?php echo $this->__('City') ?>" name="billing[city]" value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="billing:city" />
                                </div>
                            </div>
                        </li>
                        <li class="fields">
                            <div class="field" id="autofill_billing_state">
                                <label for="billing:region_id" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
                                <div class="input-box">
                                    <select id="billing:region_id1" name="billing[region_id]" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">
                                        <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                                    </select>
                                    <script type="text/javascript">
                                    //<![CDATA[
                                        $('billing:region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
                                    //]]>
                                    </script>
                                    <input type="text" id="billing:region" name="billing[region]" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>"  title="<?php echo $this->__('State/Province') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" />
                                    <input type="hidden" id="billing:region_id1" name="billing[region_id]" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>" title="<?php echo $this->__('State/Province') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" />
                                </div>
                            </div>
                            <div class="field" id="autofill_billing_country">
                                <label for="billing:country_id" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
                                <div class="input-box">
                                    <?php echo $this->getCountryHtmlSelect('billing') ?>
                                </div>
                            </div>
                        </li>
                        <?php if(!$this->isCustomerLoggedIn()): ?>
        
                <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
                <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
                    <?php if ($_dob->isEnabled() || $_gender->isEnabled()): ?>
                        <li class="fields">
                        <?php if ($_dob->isEnabled()): ?>
                            <div class="field">
                                <?php echo $_dob->setDate($this->getQuote()->getCustomerDob())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
                            </div>
                        <?php endif; ?>
                        <?php if ($_gender->isEnabled()): ?>
                            <div class="field">
                                <?php echo $_gender->setGender($this->getQuote()->getCustomerGender())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
                            </div>
                        <?php endif ?>
                        </li>
                    <?php endif ?>
        
                    <?php if ($this->isTaxvatEnabled()):?>
                        <li><?php echo $this->getTaxvatHtml() ?></li>
                    <?php endif; ?>
        
                        <li class="fields" id="register-customer-password">
                            <div class="field">
                                <label for="billing:customer_password" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                                <div class="input-box">
                                    <input type="password" name="billing[customer_password]" id="billing:customer_password" title="<?php echo $this->__('Password') ?>" class="input-text required-entry validate-password" />
                                </div>
                            </div>
                            <div class="field">
                                <label for="billing:confirm_password" class="required"><em>*</em><?php echo $this->__('Confirm Password') ?></label>
                                <div class="input-box">
                                    <input type="password" name="billing[confirm_password]" title="<?php echo $this->__('Confirm Password') ?>" id="billing:confirm_password" class="input-text required-entry validate-cpassword" />
                                </div>
                            </div>
                        </li>
                        <?php echo $this->getChildHtml('persistent.remember.me'); ?>
                        <?php endif; ?>
                        <li class="no-display"><input type="hidden" name="billing[save_in_address_book]" value="1" /></li>
                        <?php echo $this->getChildHtml('form.additional.info'); ?>
                    </ul>
                    <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
                </fieldset>
             </li>
             <li class="control">
                <input type="checkbox" name="billing[use_for_shipping]" id="billing:use_for_shipping" value="1"<?php if($this->getAddress()->getSameAsBilling()): ?> checked="checked"<?php endif; ?> title="<?php echo $this->__('Ship To Different Address') ?>" onclick="billing.setSameAsBilling(this.checked)" class="checkbox" /><label for="billing:use_for_shipping"><?php echo $this->__('Ship to different address') ?></label>
            </li>
            <?php /* if ($this->canShip()): ?>
                <li class="control">
                    <input type="radio" name="billing[use_for_shipping]" id="billing:use_for_shipping_yes" value="1" checked="checked" title="<?php echo  $this->__('Ship to this address') ?>" onclick="$('shipping:same_as_billing').checked = true;" class="radio" /><label for="billing:use_for_shipping_yes"><?php echo  $this->__('Ship to this address') ?></label></li>
                <li class="control">
                    <input type="radio" name="billing[use_for_shipping]" id="billing:use_for_shipping_no" value="0"  title="<?php echo $this->__('Ship to different address') ?>" onclick="$('shipping:same_as_billing').checked = false;" class="radio" /><label for="billing:use_for_shipping_no"><?php echo $this->__('Ship to different address') ?></label>
                </li>
            <?php endif; */  ?>
            </ul>
            <?php if (!$this->canShip()): ?>
                <input type="hidden" name="billing[use_for_shipping]" value="1" />
            <?php endif; ?>
        </fieldset>
    </div>
    <div class="col-2" style="display:none;">
        <h3 style="margin-top: 10px"><?php echo $this->__('Shipping Address')?></h3>
        <fieldset>
            <ul class="form-list">
            <?php if ($this->customerHasAddresses()): ?>
               <li class="wide">
                   <div class="select_shipping_address_title"><label for="shipping-address-select"><?php echo $this->__('Select a shipping address from your address book or enter a new address.') ?></label></div>
                    <div class="input-box" style="display: none;">
                        <?php echo $this->getAddressesHtmlSelect('shipping') ?>
                    </div>
                    <!-- New Code start -->
                    <div id="custAddress">
                        <?php $customerId = Mage::getSingleton('customer/session')->getCustomer();?>    
                        <?php $customer = Mage::getModel('customer/customer')->load($customerId->getId()); ?>
                        <?php $data = array();?>
                        <?php $i=0; foreach ($customer->getAddresses() as $address):?>
                            <?php $data = $address->toArray();?>
                            <div id="addresseList">
                                <a href="javaScript:void(0);" onclick="setAddress(this.id)" id="<?php echo $i;?>">
                                    <address> 
                                        <div id="shipping_selected_<?php echo $i;?>" class="selectedImage" style="float: right; margin: -6px; display: <?php if($customer->getPrimaryShippingAddress()->getId() == $data['entity_id']){ echo 'block'; } else{ echo 'none'; } ?>;"><img src="<?php echo $this->getSkinURl()?>images/right.jpg" /></div>
                                        <?php if(strcmp((string)$data['firstname'],(string)$data['lastname']) == 0){ echo $data['firstname'].'<br />'; } else{ echo $data['firstname'].' '.$data['lastname'].'<br />'; } ?>
                                        <?php echo $data['street'].'<br />';?>
                                        <?php echo $data['city'].','.$data['region'].','.$data['postcode'].'<br />';?>
                                        <?php $country_name = Mage::app()->getLocale()->getCountryTranslation($data['country_id']);?>
                                        <?php echo $country_name.'<br />';?>
                                        <?php echo 'T: '.$data['telephone'];?>
                                    </address>
                                </a>
                            </div>
                        <?php $i++; endforeach; ?>  
                    </div>
                    <li id="addNewShippingAddress" class="new_address"><a href="javaScript:void(0);" onclick="setNewAddress()"><?php echo $this->__('Click to Add New Address') ?></a></li>
               </li>
            <?php endif ?>
                <li id="shipping-new-address-form"<?php if ($this->customerHasAddresses()): ?> style="display:none;"<?php endif ?>>
                    <fieldset>
                        <input type="hidden" name="shipping[address_id]" value="<?php echo $this->getAddress()->getId() ?>" id="shipping:address_id" />
                        <ul>
                            <li class="fields"><?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getAddress())->setFieldIdFormat('shipping:%s')->setFieldNameFormat('shipping[%s]')->setFieldParams('onchange="shipping.setSameAsBilling(false)"')->toHtml() ?></li>
                    <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
                            <li class="fields">
                                <div class="field">
                                    <label for="shipping:street1" class="required"><em>*</em><?php echo $this->__('Address') ?></label>
                                    <div class="input-box">
                                        <input type="text" title="<?php echo $this->__('Street Address') ?>" name="shipping[street][]" id="shipping:street1" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>" class="input-text <?php echo $_streetValidationClass ?>" onchange="shipping.setSameAsBilling(false);" />
                                    </div>
                                </div>
                                <div class="field">
                                    <label for="shipping:telephone" class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>
                                    <div class="input-box">
                                        <input type="text" name="shipping[telephone]" value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" id="shipping:telephone" onchange="shipping.setSameAsBilling(false);" />
                                    </div>
                                </div>
                            </li>
                    <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                    <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                            <li class="fields">
                                <div class="input-box">
                                    <input type="text" title="<?php echo $this->__('Street Address %s', $_i) ?>" name="shipping[street][]" id="shipping:street<?php echo $_i ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet($_i)) ?>" class="input-text <?php echo $_streetValidationClass ?>" onchange="shipping.setSameAsBilling(false);" />
                                </div>
                            </li>
                    <?php endfor; ?>
                            <?php if ($this->helper('customer/address')->isVatAttributeVisible()) : ?>
                            <li class="fields">
                                <label for="billing:vat_id"><?php echo $this->__('VAT Number'); ?></label>
                                <div class="input-box">
                                    <input type="text" id="shipping:vat_id" name="shipping[vat_id]" value="<?php echo $this->escapeHtml($this->getAddress()->getVatId()); ?>" title="<?php echo $this->__('VAT Number'); ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('vat_id') ?>" />
                                </div>
                            </li>
                            <?php endif; ?>
                            <li class="fields">
                                <div class="field">
                                    <label for="shipping:postcode" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
                                    <div class="input-box">
                                        <input type="text" title="<?php echo $this->__('Zip/Postal Code') ?>" name="shipping[postcode]" id="shipping:postcode" value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>" class="input-text validate-zip-international shipping_zip <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" onchange="shipping.setSameAsBilling(false);" />
                                    </div>
                                </div>
                                <div class="field" id="autofill_shipping_city">
                                    <label for="shipping:city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
                                    <div class="input-box">
                                        <input type="text" title="<?php echo $this->__('City') ?>" name="shipping[city]" value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="shipping:city" onchange="shipping.setSameAsBilling(false);" />
                                    </div>
                                </div>
                            </li>
                            <li class="fields">
                                <div class="field" id="autofill_shipping_state">
                                    <label for="shipping:region" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
                                    <div class="input-box">
                                        <select id="shipping:region_id1" name="shipping[region_id]" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">
                                            <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                                        </select>
                                        <script type="text/javascript">
                                        //<![CDATA[
                                            $('shipping:region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
                                        //]]>
                                        </script>
                                        <input type="text" id="shipping:region" name="shipping[region]" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>" title="<?php echo $this->__('State/Province') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" />
                                        <input type="hidden" id="shipping:region_id1" name="shipping[region_id]" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>" title="<?php echo $this->__('State/Province') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" />
                                    </div>
                                </div>
                                <div class="field" id="autofill_shipping_country">
                                    <label for="shipping:country_id" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
                                    <div class="input-box">
                                        <?php echo $this->getCountryHtmlSelect('shipping') ?>
                                    </div>
                                </div>
                            </li>
                            <li class="no-display"><input type="hidden" name="shipping[save_in_address_book]" value="1" /></li>
                        </ul>
                    </fieldset>
                </li>
            </ul>
            <?php /*?><div class="buttons-set" id="shipping-buttons-container">
                <p class="required"><?php echo $this->__('* Required Fields') ?></p>
                <p class="back-link"><a href="#" onclick="checkout.back(); return false;"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
                <button type="button" class="button" title="<?php echo $this->__('Continue') ?>" onclick="shipping.save()" ><span><span><?php echo $this->__('Continue') ?></span></span></button>
                <span id="shipping-please-wait" class="please-wait" style="display:none;">
                    <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading next step...') ?>" title="<?php echo $this->__('Loading next step...') ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
                </span>
            </div><?php */?>
        
        </fieldset>
    </div>
</div>
    <div class="buttons-set" id="billing-buttons-container">
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
        <p class="back-link"><a href="#" onclick="checkout.back(); return false;"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
        <button type="button" title="<?php echo $this->__('Continue') ?>" class="button" onclick="billing.save()"><span><span><?php echo $this->__('Continue') ?></span></span></button>
        <span class="please-wait" id="billing-please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading next step...') ?>" title="<?php echo $this->__('Loading next step...') ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
        </span>
    </div>
</form>

<script type="text/javascript">
//<![CDATA[
    var billing = new Billing('co-billing-form', '<?php echo $this->getUrl('checkout/onepage/getAddress') ?>address/', '<?php echo $this->getUrl('checkout/onepage/saveBilling') ?>');
    var billingForm = new VarienForm('co-billing-form');

    //billingForm.setElementsRelation('billing:country_id', 'billing:region', '<?php echo $this->getUrl('directory/json/childRegion') ?>', '<?php echo $this->__('Select State/Province...') ?>');
    $('billing-address-select') && billing.newAddress(!$('billing-address-select').value);

    var billingRegionUpdater = new RegionUpdater('billing:country_id', 'billing:region', 'billing:region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'billing:postcode');
    if ($('onepage-guest-register-button')) {
        Event.observe($('onepage-guest-register-button'), 'click', function(event) {
            var billingRememberMe = $('co-billing-form').select('#remember-me-box');
            if (billingRememberMe.length > 0) {
                if ($('login:guest') && $('login:guest').checked) {
                    billingRememberMe[0].hide();
                } else if ($('login:register') && ($('login:register').checked || $('login:register').type == 'hidden')) {
                    billingRememberMe[0].show();
                }
            }
        });
    }

    var shipping = new Shipping('co-billing-form', '<?php echo $this->getUrl('checkout/onepage/getAddress') ?>address/', '<?php echo $this->getUrl('checkout/onepage/saveShipping') ?>',
        '<?php echo $this->getUrl('checkout/onepage/shippingMethod') ?>');
    var shippingForm = new VarienForm('co-billing-form');
    shippingForm.extraChildParams = ' onchange="shipping.setSameAsBilling(false);"';
    //shippingForm.setElementsRelation('shipping:country_id', 'shipping:region', '<?php echo $this->getUrl('directory/json/childRegion') ?>', '<?php echo $this->__('Select State/Province...') ?>');
    $('shipping-address-select') && shipping.newAddress(!$('shipping-address-select').value);

    var shippingRegionUpdater = new RegionUpdater('shipping:country_id', 'shipping:region', 'shipping:region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'shipping:postcode');
//]]>
</script>


<?php /*?><script type="text/javascript">
//<![CDATA[
    var shipping = new Shipping('co-shipping-form', '<?php echo $this->getUrl('checkout/onepage/getAddress') ?>address/', '<?php echo $this->getUrl('checkout/onepage/saveShipping') ?>',
        '<?php echo $this->getUrl('checkout/onepage/shippingMethod') ?>');
    var shippingForm = new VarienForm('co-shipping-form');
    shippingForm.extraChildParams = ' onchange="shipping.setSameAsBilling(false);"';
    //shippingForm.setElementsRelation('shipping:country_id', 'shipping:region', '<?php echo $this->getUrl('directory/json/childRegion') ?>', '<?php echo $this->__('Select State/Province...') ?>');
    $('shipping-address-select') && shipping.newAddress(!$('shipping-address-select').value);

    var shippingRegionUpdater = new RegionUpdater('shipping:country_id', 'shipping:region', 'shipping:region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'shipping:postcode');
//]]>
</script><?php */?>
<script type="text/javascript">
function setAddress(obj) {
    document.getElementById('shipping-address-select').selectedIndex = obj;
    jQuery(".selectedImage").hide();
    jQuery("#shipping_selected_"+obj).show();
    jQuery("#shipping-new-address-form").hide();
    jQuery("#addNewShippingAddress").show();
}
function setNewAddress() {
    jQuery("#shipping-address-select").find("option:contains('New Address')").each(function() {
        if(jQuery(this).text() == 'New Address') {
            jQuery(this).attr("selected","selected");
            jQuery("#shipping-new-address-form").show();
            jQuery("#addNewShippingAddress").hide();
            jQuery(".selectedImage").hide();
        }
    });
}
function setBillingAddress(obj) {
    document.getElementById('billing-address-select').selectedIndex = obj;
    jQuery(".billingselectedImage").hide();
    jQuery("#billing_selected_"+obj).show();
    jQuery("#billing-new-address-form").hide();
    jQuery("#addNewBillingAddress").show();
}
function setNewBillingAddress() {
    jQuery("#billing-address-select").find("option:contains('New Address')").each(function() {
        if(jQuery(this).text() == 'New Address') {
            jQuery(this).attr("selected","selected");
            jQuery("#billing-new-address-form").show();
            jQuery("#addNewBillingAddress").hide();
            jQuery(".billingselectedImage").hide();
        }
    });
}
jQuery(".billing_zip").focusout(function(){
    if(this.value.length > 0) {
        var data1 = "";
        var url1 = 'http://maps.googleapis.com/maps/api/geocode/json?address='+this.value+'&sensor=true';
        try {
            jQuery.ajax({
                url: url1,
                type : 'get',
                dataType: 'json',
                data: data1,
                success: function(response){
                    var result = jQuery.map(response['results'][0]['address_components'], function(val, key) {
                        if(val.types[0] == 'locality' || val.types[0] == 'administrative_area_level_1' || val.types[0] == 'country') {
                            return { long_name: val.long_name, short_name: val.short_name };
                        };
                    });
                    // i = 0 City // i = 1 State // i = 2 Country
                    jQuery('div#autofill_billing_city').find('div.input-box > input:visible:first').val(result[0]['long_name']);
                    jQuery('div#autofill_billing_state').find('div.input-box > input:visible:first').val(result[1]['long_name']);
                    jQuery('div#autofill_billing_state').find('div.input-box > input:hidden:first').val(result[1]['short_name']);
                    jQuery('div#autofill_billing_country').find('div.input-box > select:visible:first').val(result[2]['short_name']);
                }
            });
        } catch(e){ }
    };
});
jQuery(".shipping_zip").focusout(function(){
    if(this.value.length > 0) {
        var data1 = "";
        var url1 = 'http://maps.googleapis.com/maps/api/geocode/json?address='+this.value+'&sensor=true';
        try {
            jQuery.ajax({
                url: url1,
                type : 'get',
                dataType: 'json',
                data: data1,
                success: function(response){
                    var result = jQuery.map(response['results'][0]['address_components'], function(val, key) {
                        if(val.types[0] == 'locality' || val.types[0] == 'administrative_area_level_1' || val.types[0] == 'country') {
                            return { long_name: val.long_name, short_name: val.short_name };
                        };
                    });
                    // i = 0 City // i = 1 State // i = 2 Country
                    jQuery('div#autofill_shipping_city').find('div.input-box > input:visible:first').val(result[0]['long_name']);
                    jQuery('div#autofill_shipping_state').find('div.input-box > input:visible:first').val(result[1]['long_name']);
                    jQuery('div#autofill_shipping_state').find('div.input-box > input:hidden:first').val(result[1]['short_name']);
                    jQuery('div#autofill_shipping_country').find('div.input-box > select:visible:first').val(result[2]['short_name']);
                }
            });
        } catch(e){ }
    };
});

jQuery(".checkbox").click(function(){
    if(jQuery(this).is(':checked'))
        jQuery("div.col-2").show();
    else
        jQuery("div.col-2").hide();
});
</script>