<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage_Secureebs
 * @copyright  Copyright (c) 2008 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<fieldset class="form-list">
    <?php $_code=$this->getMethodCode() ?>
    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
        <li>
        	<img src="<?php echo $this->getSkinUrl('images/logo_visa.png') ?>" alt="visa" class="payment" />
			<img src="<?php echo $this->getSkinUrl('images/logo_mastercard.png') ?>" alt="master card" class="payment"  />
			<img src="<?php echo $this->getSkinUrl('images/RuPay_Logo2.jpg') ?>" alt="RuPay" class="payment"  />
			<img src="<?php echo $this->getSkinUrl('images/logo_mastsecure.png') ?>" alt="Mastercard Secure" class="payment"  /> & all other cards<br>
			<!--<b>We accept Credit/Debit Cards (Visa/Master/RuPay) issued by all Banks.<br> 
			On placing the Order, you will be redirected to HDFC Secure Payment Processing Gateway. </b>-->
            <?php echo $this->__('You will be redirected to HDFC Secure Payment Processing Gateway.') ?>
        </li>
    </ul>
</fieldset>