<?php 
	$frontcollection = Mage::getModel('styles/styles')
											->getCollection()
											->addFieldToFilter('status',1)
											->addFieldToFilter('stitching_service_id',$_REQUEST['service'])
											->addFieldToFilter('stitching_service', array('like' => '%'.$_REQUEST['stitching_type'].'%'));
	$lehangacollection = Mage::getModel('lehanga/lehanga')
											->getCollection()
											->addFieldToFilter('stitching_service', array('like' => '%'.$_REQUEST['stitching_type'].'%'))
											->addFieldToFilter('status',1);
	$salwarcollection = Mage::getModel('salwar/salwar')
											->getCollection()
											->addFieldToFilter('stitching_service', array('like' => '%'.$_REQUEST['stitching_type'].'%'))
											->addFieldToFilter('status',1);

	$tasselcollection = Mage::getModel('tassel/tassel')
											->getCollection()
											->addFieldToFilter('stitching_service', array('like' => '%'.$_REQUEST['stitching_type'].'%'))
											->addFieldToFilter('status',1);
?>
<div class="measure_details">
	<div class="measure_detail" id="style_fit">
		<div class="label_title"><label>1. Style & Fit</label><label class="right"></label></div>
		<div class="style_fit_details" id="measurement_step">
			<div class="front">
				<?php if (sizeof($frontcollection) > 0) { ?>
					<div class="label_title1"><label>Front Styles</label></div>
					<div class="front_style_details">
						<ul class="front_style" id="item_style">
						<?php $i = 0; foreach ($frontcollection as $key => $_front) { ?>
							<li class="front_style_li" data="<?php echo $i; ?>">
								<div class="title"><label><?php echo $_front->getTitle(); ?></label></div>
								<div class="image"><img width="130" height="180" alt="<?php echo $_front->getTitle(); ?>" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$_front->getImage(); ?>"></div>
								<div class="select_option"><input class="front_id" name="front_id" type="radio" value="<?php echo $_front->getStyleId(); ?>" /></div>
							</li>
						<?php $i++; } ?>
						</ul>
					</div>
				<?php } ?>
			</div>
			<div class="back"></div>
			<div class="sleeve"></div>
			<div class="lehanga">
				<?php if( sizeof($lehangacollection) > 0 && sizeof($frontcollection) == 0) { ?>
					<div class="label_title1"><label>Lehanga/Skirt/Petticoat Styles</label></div>
					<div class="sleeve_style_details">
						<ul class="back_style" id="item_style">
							<?php $i = 0; foreach ($lehangacollection as $key => $_lehanga) { ?>
								<li class="lehanga_style_li" data="<?php echo $i; ?>">
								<div class="title"><label><?php echo $_lehanga->getTitle(); ?></label></div>
								<div class="image"><img width="130" height="180" alt="<?php echo $_lehanga->getTitle(); ?>" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$_lehanga->getImage(); ?>"></div>
								<div class="select_option"><input id="<?php echo $_REQUEST['service']; ?>" class="lehanga_id" name="lehanga_id" type="radio" value="<?php echo $_lehanga->getLehangaId(); ?>" /></div>
								</li>
							<?php $i++; } ?>
						</ul>
					</div>
				<?php } ?>
			</div>
			<div class="salwar">
				<?php if( sizeof($salwarcollection) > 0 && sizeof($frontcollection) == 0 && sizeof($lehangacollection) == 0) { ?>
					<div class="label_title1"><label>Salwar Styles</label></div>
					<div class="sleeve_style_details">
						<ul class="back_style" id="item_style">
							<?php $i = 0; foreach ($salwarcollection as $key => $_salwar) { ?>
								<li class="lehanga_style_li" data="<?php echo $i; ?>">
								<div class="title"><label><?php echo $_salwar->getTitle(); ?></label></div>
								<div class="image"><img width="130" height="180" alt="<?php echo $_salwar->getTitle(); ?>" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$_salwar->getImage(); ?>"></div>
								<div class="select_option"><input id="<?php echo $_REQUEST['service']; ?>" class="salwar_id" name="salwar_id" type="radio" value="<?php echo $_salwar->getSalwarId(); ?>" /></div>
								</li>
							<?php $i++; } ?>
						</ul>
					</div>
				<?php } ?>
			</div>
			<div class="tassel"><input type="hidden" class="tassel_size" value="<?php echo sizeof($tasselcollection); ?>"></div>
			<div class="goto_nextstep"><button type="button" class="take_measurement"> Next Step </button></div>
		</div>
	</div>
	<div class="measure_detail" id="measurement">
		<div class="label_title"><label>2. Measurements</label><label class="right"></label></div>
		<div class="measurement_details" id="measurement_step"></div>
	</div>
	<div class="measure_detail" id="review">
		<div class="label_title"><label>3. Review</label><label class="right"></label></div>
		<div class="measurement_review" id="measurement_step"></div>
	</div>


	<script type="text/javascript">
	    var jQuery = jQuery.noConflict();
	    jQuery(function(){
	    	jQuery("#item_style").flexisel();
	        jQuery('.label_title').click(function() {
	        	jQuery(this).parent().parent().find('#measurement_step').show();
			});
	        jQuery('.front_id').click(function() {
	            var data1 = "&front_id="+this.value+"&service="+jQuery('.service').val();
	            var url1 = '<?php echo Mage::getBaseUrl(); ?>measurement/measure/backstyles';
				try {
					jQuery.ajax({
						url: url1,
						type : 'post',
						data: data1,
						success: function(response){
							if (response) {
								var string = response;
							} else{
								var string = '<div class="back"><div class="label_title1"><label>Back Styles</label></div><div class="back_style_details"><p>Currently the Back Styles are Unavailable for this product</p></div></div>';
							}
							jQuery('.back').replaceWith(string);
						}
					});
				} catch(e){ }
	        });
	        jQuery('.back_id').click(function() {
				var front_id = 0;
		    	jQuery(".back_id").each(function() {
					if( jQuery(this).prop("checked")== true) {
						front_id = jQuery(this).attr("value");
					}
				});
		        var data1 = "&back_id="+this.value+"&front_id="+front_id+"&service="+jQuery('.service').val();
	            var url1 = '<?php echo Mage::getBaseUrl(); ?>measurement/measure/sleevestyles';
				try {
					jQuery.ajax({
						url: url1,
						type : 'post',
						data: data1,
						success: function(response){
							if (response) {
								var string = response;
							} else{
								var string = '<div class="sleeve"><div class="label_title1"><label>Sleeve Styles</label></div><div class="sleeve_style_details"><p>Currently the Sleeve Styles are Unavailable for this product</p></div></div>';
							}
							jQuery('.sleeve').replaceWith(string);
						}
					});
				} catch(e){ }
	        });
	        jQuery('.salwar_id').click(function() {
	        	var tassel_size = parseInt(jQuery('.tassel_size').val());
        		var service = parseInt(jQuery('.service').val());
        		var stitching_type = parseInt(jQuery('.stitching_type').val());
        		if (tassel_size > 0) {
        			var data1 = "&stitching_type="+stitching_type+"&lehanga_id="+this.value+"&service="+service;
		            var url1 = '<?php echo Mage::getBaseUrl(); ?>measurement/measure/gettasselstyles';
		            try {
						jQuery.ajax({
							url: url1,
							type : 'post',
							data: data1,
							success: function(response){
								if (response) {
									var string = response;
								} else{
									var string = '<div class="tassel"><p>Currently the Styles are Unavailable for this product</p></div>';
								}
								// jQuery('.style_fit_details').toggle();
								jQuery('.tassel').replaceWith(string);
								// jQuery('.measurement_details').toggle();
							}
						});
					} catch(e){ }
        		}else{
        			var data1 = "&stitching_type="+stitching_type+"&lehanga_id="+this.value+"&service="+service;
		            var url1 = '<?php echo Mage::getBaseUrl(); ?>measurement/measure/getmeasurements';
		            try {
						jQuery.ajax({
							url: url1,
							type : 'post',
							data: data1,
							success: function(response){
								if (response) {
									var string = response;
								} else{
									var string = '<div id="measurement_step" class="measurement_details"><p>Currently the Measurements are Unavailable for this product</p></div>';
								}
								// jQuery('.style_fit_details').toggle();
								jQuery('.measurement_details').replaceWith(string);
								// jQuery('.measurement_details').toggle();
							}
						});
					} catch(e){ }
        		}
			});
	        jQuery('.lehanga_id').click(function() {
	        	var tassel_size = parseInt(jQuery('.tassel_size').val());
        		var service = parseInt(jQuery('.service').val());
        		var stitching_type = parseInt(jQuery('.stitching_type').val());
        		if (tassel_size > 0) {
        			var data1 = "&stitching_type="+stitching_type+"&lehanga_id="+this.value+"&service="+service;
		            var url1 = '<?php echo Mage::getBaseUrl(); ?>measurement/measure/gettasselstyles';
		            try {
						jQuery.ajax({
							url: url1,
							type : 'post',
							data: data1,
							success: function(response){
								if (response) {
									var string = response;
								} else{
									var string = '<div class="tassel"><p>Currently the Styles are Unavailable for this product</p></div>';
								}
								// jQuery('.style_fit_details').toggle();
								jQuery('.tassel').replaceWith(string);
								// jQuery('.measurement_details').toggle();
							}
						});
					} catch(e){ }
        		}else{
        			var data1 = "&stitching_type="+stitching_type+"&lehanga_id="+this.value+"&service="+service;
		            var url1 = '<?php echo Mage::getBaseUrl(); ?>measurement/measure/getmeasurements';
		            try {
						jQuery.ajax({
							url: url1,
							type : 'post',
							data: data1,
							success: function(response){
								if (response) {
									var string = response;
								} else{
									var string = '<div id="measurement_step" class="measurement_details"><p>Currently the Measurements are Unavailable for this product</p></div>';
								}
								// jQuery('.style_fit_details').toggle();
								jQuery('.measurement_details').replaceWith(string);
								// jQuery('.measurement_details').toggle();
							}
						});
					} catch(e){ }
        		}
			});
	    });
	</script>
</div>