<div class="custom_measurements">
	<div class="m_attr">
		<label id="label" class="required"><em>*</em><b>Measurements For </b></label>
		<label class="value"><input id="required-entry" type="text" name="storing_for" value="Myself" class="measurement_textfield required-entry" /></label>
		<label class="content" id="content">Name for your Measurements Set e.g. MySelf, Mom, Sister, etc...</label>
	</div>
	<?php $front = Mage::getModel('styles/styles')->getCollection()->addFieldToSelect('measurement_attr')->addFieldToFilter('style_id',$_REQUEST['front_id'])->addFieldToFilter('status',1)->getFirstItem();
		$back = Mage::getModel('back/back')->getCollection()->addFieldToSelect('measurement_attr')->addFieldToFilter('back_id',$_REQUEST['back_id'])->addFieldToFilter('status',1)->getFirstItem();
		$sleeve = Mage::getModel('sleeves/sleeves')->getCollection()->addFieldToSelect('measurement_attr')->addFieldToFilter('sleeves_id',$_REQUEST['sleeve_id'])->addFieldToFilter('status',1)->getFirstItem();
		$lehanga = Mage::getModel('lehanga/lehanga')->getCollection()->addFieldToSelect('measurement_attr')->addFieldToFilter('lehanga_id',$_REQUEST['lehanga_id'])->addFieldToFilter('status',1)->getFirstItem();
		$salwar = Mage::getModel('salwar/salwar')->getCollection()->addFieldToSelect('measurement_attr')->addFieldToFilter('salwar_id',$_REQUEST['salwar_id'])->addFieldToFilter('status',1)->getFirstItem();
		$tassel = Mage::getModel('tassel/tassel')->getCollection()->addFieldToSelect('measurement_attr')->addFieldToFilter('tassel_id',$_REQUEST['tassel_id'])->addFieldToFilter('status',1)->getFirstItem();
		if(strlen($front['measurement_attr']) > 0) {
			$front_attr = explode(',', $front['measurement_attr']); ?>
			<div class="front_measurements" id="measurements_group">
				<div class="title">Front Measurements</div>
				<div class="front_measurement_details">
					<?php foreach ($front_attr as $key => $_front) {
						$_front1 = Mage::getModel('measurement/measurement')->load($_front);
						$customtitles = Mage::getModel('measurement/customtitles')->getCollection()->addFieldToFilter('measurement_id',$_front1->getMeasurementId());
						$min = $_front1->getMinVal();
						$max = $_front1->getMaxVal();
						if($_REQUEST['units'] == 'cm'){ 
							$unit = 2.54;
							$min = round( ($min*$unit), 2);
							$min = 5 * round($min / 5, 2);
							$max = round( ($max*$unit), 2);
							$max = 5 * round($max / 5, 2);
						}
						$originalmin = $min;
						$difference = $_front1->getDifference(); ?>
						<div class="m_attr">
							<label id="label" class="<?php if($_front1->getIsRequired() == 1){ echo "required"; } ?>"><?php if($_front1->getIsRequired() == 1){ echo "<em>*</em>"; } ?><?php echo $_front1->getTitle(); ?></label>
							<label class="value">
								<?php if($_front1->getFieldType() == 'radio') { ?>
									<?php foreach ($customtitles as $key => $_customtitle) { ?>
										<label class="radio_button"><input id="<?php if($_front1->getIsRequired() == 1){ echo "required-entry"; } ?>" name="<?php echo $_REQUEST['service']; ?>[<?php echo $_front1->getMeasurementId(); ?>]" type="radio" value="<?php echo $_customtitle->getCustomTitleId(); ?>" /><?php echo $_customtitle->getTitle(); ?></label>
									<?php } ?>
								<?php } elseif($_front1->getFieldType() == 'text_area') { ?>
									<label class="value">
										<textarea class="<?php if($_front1->getIsRequired() == 1){ echo "required-entry"; } ?>" id="<?php if($_front1->getIsRequired() == 1){ echo "required-entry"; } ?>" name="<?php echo $_REQUEST['service']; ?>[<?php echo $_front1->getMeasurementId(); ?>]" cols="45" rows="3" style="resize: none;"></textarea>
									</label>
								<?php }elseif($_front1->getFieldType() == 'text_field') { ?>
									<input id="<?php if($_front1->getIsRequired() == 1){ echo "required-entry"; } ?>" class="measurement_textfield <?php if($_front1->getIsRequired() == 1){ echo "required-entry"; } ?>" type="number" step="<?php echo $difference; ?>" name="<?php echo $_REQUEST['service']; ?>[<?php echo $_front1->getMeasurementId(); ?>]" min="<?php echo $min; ?>" max="<?php echo $max; ?>" >
									<span><span><?php echo '('.$min.' - '.$max.')'; ?></span><span><?php echo $_REQUEST['units']; ?></span></span>
								<?php }elseif($_front1->getFieldType() == 'dropdown') {
									if($_front1->getDropdownType() == 'standard') { ?>
									 	<select class="<?php if($_front1->getIsRequired() == 1){ echo "required-entry"; } ?>" id="<?php if($_front1->getIsRequired() == 1){ echo "required-entry"; } ?>" name="<?php echo $_REQUEST['service']; ?>[<?php echo $_front1->getMeasurementId(); ?>]">
											<option></option>
											<?php while($min <= $max) { ?>
												<option><?php echo $min; ?></option>
												<?php $min += $difference;
											} ?>
										</select>
										<span><span><?php echo '('.$originalmin.' - '.$max.')'; ?></span><span><?php echo $_REQUEST['units']; ?></span></span>
									 <?php }else if($_front1->getDropdownType() == 'custom'){ ?>
									 	<select class="<?php if($_front1->getIsRequired() == 1){ echo "required-entry"; } ?>" id="<?php if($_front1->getIsRequired() == 1){ echo "required-entry"; } ?>" name="<?php echo $_REQUEST['service']; ?>[<?php echo $_front1->getMeasurementId(); ?>]">
											<option></option>
											<?php foreach ($customtitles as $key => $_customtitle) { ?>
												<option value="<?php echo $_customtitle->getCustomTitleId(); ?>"><?php echo $_customtitle->getTitle(); ?></option>
											<?php } ?>
										</select>
									 <?php } ?>
								<?php } ?>
							</label>
							<?php if (!empty($_front1->getImage())) { ?>
								<label class="image"><img width="190" height="230" title="Image" alt="Image" src="<?php echo Mage::getBaseUrl('media').$_front1->getImage(); ?>"></label>
							<?php } ?>
							<label class="content">
								<h5>Ho to Measure</h5>
								<h3><?php echo strtoupper($_front1->getTitle()); ?></h3>
								<?php echo $_front1->getContent(); ?>
							</label>
						</div>

					<?php } ?>
				</div>
				<div class="more_info"></div>
			</div>

		<?php }
		if(strlen($back['measurement_attr']) > 0) {
			$back_attr = explode(',', $back['measurement_attr']); ?>
			<div class="back_measurements" id="measurements_group">
				<div class="title">Back Measurements</div>
				<div class="back_measurement_details">
					<?php foreach ($back_attr as $key => $_back) {
						$_back1 = Mage::getModel('measurement/measurement')->load($_back);
						$customtitles = Mage::getModel('measurement/customtitles')->getCollection()->addFieldToFilter('measurement_id',$_back1->getMeasurementId());
						$min = $_back1->getMinVal();
						$max = $_back1->getMaxVal();
						if($_REQUEST['units'] == 'cm'){ 
							$unit = 2.54;
							$min = round( ($min*$unit), 2);
							$min = 5 * round($min / 5, 2);
							$max = round( ($max*$unit), 2);
							$max = 5 * round($max / 5, 2);
						}
						$originalmin = $min;
						$difference = $_back1->getDifference(); ?>
						<div class="m_attr"><label id="label" class="<?php if($_back1->getIsRequired() == 1){ echo "required"; } ?>"><?php if($_back1->getIsRequired() == 1){ echo "<em>*</em>"; } ?><?php echo $_back1->getTitle(); ?></label>
							<label class="value">
								<?php if($_back1->getFieldType() == 'radio') {
									foreach ($customtitles as $key => $_customtitle) { ?>
										<label class="radio_button"><input id="<?php if($_back1->getIsRequired() == 1){ echo "required-entry"; } ?>" name="<?php echo $_REQUEST['service']; ?>[<?php echo $_back1->getMeasurementId(); ?>]" type="radio" value="<?php echo $_customtitle->getCustomTitleId(); ?>" /><?php echo $_customtitle->getTitle(); ?></label>
									<?php } ?>
								<?php } elseif($_back1->getFieldType() == 'text_area') { ?>
									<label class="value">
										<textarea class="<?php if($_back1->getIsRequired() == 1){ echo "required-entry"; } ?>" name="<?php echo $_REQUEST['service']; ?>[<?php echo $_back1->getMeasurementId(); ?>]" cols="45" rows="3" style="resize: none;" id="<?php if($_back1->getIsRequired() == 1){ echo "required-entry"; } ?>"></textarea>
									</label>
								<?php }elseif($_back1->getFieldType() == 'text_field') { ?>
									<input class="measurement_textfield <?php if($_back1->getIsRequired() == 1){ echo "required-entry"; } ?>" type="number" step="<?php echo $difference; ?>" name="<?php echo $_REQUEST['service']; ?>[<?php echo $_back1->getMeasurementId(); ?>]" min="<?php echo $min; ?>" max="<?php echo $max; ?>" id="<?php if($_back1->getIsRequired() == 1){ echo "required-entry"; } ?>" >
									<span><span><?php echo '('.$min.' - '.$max.')'; ?></span><span><?php echo $_REQUEST['units']; ?></span></span>
								<?php }elseif($_back1->getFieldType() == 'dropdown') {
									if($_back1->getDropdownType() == 'standard') { ?>
									 	<select class="<?php if($_back1->getIsRequired() == 1){ echo "required-entry"; } ?>" name="<?php echo $_REQUEST['service']; ?>[<?php echo $_back1->getMeasurementId(); ?>]" id="<?php if($_back1->getIsRequired() == 1){ echo "required-entry"; } ?>">
											<option></option>
											<?php while($min <= $max) { ?>
												<option><?php echo $min; ?></option>
												<?php $min += $difference;
											} ?>
										</select>
										<span><span><?php echo '('.$originalmin.' - '.$max.')'; ?></span><span><?php echo $_REQUEST['units']; ?></span></span>
									<?php }else if($_back1->getDropdownType() == 'custom'){ ?>
									 	<select class="<?php if($_back1->getIsRequired() == 1){ echo "required-entry"; } ?>" name="<?php echo $_REQUEST['service']; ?>[<?php echo $_back1->getMeasurementId(); ?>]" id="<?php if($_back1->getIsRequired() == 1){ echo "required-entry"; } ?>">
											<option></option>
											<?php foreach ($customtitles as $key => $_customtitle) { ?>
												<option value="<?php echo $_customtitle->getCustomTitleId(); ?>"><?php echo $_customtitle->getTitle(); ?></option>
											<?php } ?>
										</select>
									<?php } ?>
								<?php } ?>
							</label>
							<?php if(!empty($_back1->getImage())) { ?>
								<label class="image"><img width="190" height="230" title="Image" alt="Image" src="<?php echo Mage::getBaseUrl('media').$_back1->getImage(); ?>"></label>
							<?php } ?>
							<label class="content">
								<h5>Ho to Measure</h5>
								<h3><?php echo strtoupper($_back1->getTitle()); ?></h3>
								<?php echo $_back1->getContent(); ?>
							</label>
						</div>

					<?php } ?>
				</div>
				<div class="more_info"></div>
			</div>
		<?php }
		if(strlen($sleeve['measurement_attr']) > 0) {
			// print_r($sleeve['measurement_attr']);
			$sleeve_attr = explode(',', $sleeve['measurement_attr']); ?>
			<div class="sleeve_measurements" id="measurements_group">
				<div class="title">Sleeve Measurements</div>
				<div class="sleeve_measurement_details">
					<?php foreach ($sleeve_attr as $key => $_sleeve) {
						$_sleeve1 = Mage::getModel('measurement/measurement')->load($_sleeve);
						$customtitles = Mage::getModel('measurement/customtitles')->getCollection()->addFieldToFilter('measurement_id',$_sleeve1->getMeasurementId());
						$min = $_sleeve1->getMinVal();
						$max = $_sleeve1->getMaxVal();
						if($_REQUEST['units'] == 'cm'){ 
							$unit = 2.54;
							$min = round( ($min*$unit), 2);
							$min = 5 * round($min / 5, 2);
							$max = round( ($max*$unit), 2);
							$max = 5 * round($max / 5, 2);
						}
						$originalmin = $min;
						$difference = $_sleeve1->getDifference(); ?>
						<div class="m_attr"><label id="label" class="<?php if($_sleeve1->getIsRequired() == 1){ echo "required"; } ?>"><?php if($_sleeve1->getIsRequired() == 1){ echo "<em>*</em>"; } ?><?php echo $_sleeve1->getTitle(); ?></label>
							<label class="value">
								<?php 
								if($_sleeve1->getFieldType() == 'radio') { ?>
									<?php foreach ($customtitles as $key => $_customtitle) { ?>
										<label class="radio_button"><input id="<?php if($_sleeve1->getIsRequired() == 1){ echo "required-entry"; } ?>" name="<?php echo $_REQUEST['service']; ?>[<?php echo $_sleeve1->getMeasurementId(); ?>]" type="radio" value="<?php echo $_customtitle->getCustomTitleId(); ?>" /><?php echo $_customtitle->getTitle(); ?></label>
									<?php } ?>
								<?php } elseif($_sleeve1->getFieldType() == 'text_area') { ?>
									<label class="value">
										<textarea class="<?php if($_sleeve1->getIsRequired() == 1){ echo "required-entry"; } ?>" name="<?php echo $_REQUEST['service']; ?>[<?php echo $_sleeve1->getMeasurementId(); ?>]" class="" cols="45" rows="3" style="resize: none;" id="<?php if($_sleeve1->getIsRequired() == 1){ echo "required-entry"; } ?>"></textarea>
									</label>
								<?php }elseif($_sleeve1->getFieldType() == 'text_field') { ?>
									<input class="measurement_textfield <?php if($_sleeve1->getIsRequired() == 1){ echo "required-entry"; } ?>" type="number" step="<?php echo $difference; ?>" name="<?php echo $_sleeve1->getMeasurementId(); ?>" min="<?php echo $min; ?>" max="<?php echo $max; ?>" id="<?php if($_sleeve1->getIsRequired() == 1){ echo "required-entry"; } ?>" >
									<span><span><?php echo '('.$min.' - '.$max.')'; ?></span><span><?php echo $_REQUEST['units']; ?></span></span>
								<?php }elseif($_sleeve1->getFieldType() == 'dropdown') {
									if($_sleeve1->getDropdownType() == 'standard') { ?>
									 	<select class="<?php if($_sleeve1->getIsRequired() == 1){ echo "required-entry"; } ?>" name="<?php echo $_REQUEST['service']; ?>[<?php echo $_sleeve1->getMeasurementId(); ?>]" id="<?php if($_sleeve1->getIsRequired() == 1){ echo "required-entry"; } ?>">
											<option></option>
											<?php while($min <= $max) { ?>
												<option><?php echo $min; ?></option>
												<?php $min += $difference;
											} ?>
										</select>
										<span><span><?php echo '('.$originalmin.' - '.$max.')'; ?></span><span><?php echo $_REQUEST['units']; ?></span></span>
									 <?php }else if($_sleeve1->getDropdownType() == 'custom'){ ?>
									 	<select class="<?php if($_sleeve1->getIsRequired() == 1){ echo "required-entry"; } ?>" name="<?php echo $_REQUEST['service']; ?>[<?php echo $_sleeve1->getMeasurementId(); ?>]" id="<?php if($_sleeve1->getIsRequired() == 1){ echo "required-entry"; } ?>">
											<option></option>
											<?php foreach ($customtitles as $key => $_customtitle) { ?>
												<option value="<?php echo $_customtitle->getCustomTitleId(); ?>"><?php echo $_customtitle->getTitle(); ?></option>
											<?php } ?>
										</select>
									 <?php } ?>
								<?php } ?>
							</label>
							<?php if (!empty($_sleeve1->getImage())) { ?>
								<label class="image"><img width="190" height="230" title="Image" alt="Image" src="<?php echo Mage::getBaseUrl('media').$_sleeve1->getImage(); ?>"></label>
							<?php } ?>
							<label class="content">
								<h5>Ho to Measure</h5>
								<h3><?php echo strtoupper($_sleeve1->getTitle()); ?></h3>
								<?php echo $_sleeve1->getContent(); ?>
							</label>
						</div>

					<?php } ?>
				</div>
				<div class="more_info"></div>
			</div>
		<?php }
		if(strlen($salwar['measurement_attr']) > 0) {
			$salwar_attr = explode(',', $salwar['measurement_attr']); ?>
			<div class="salwar_measurements" id="measurements_group">
				<div class="title">Salwar Measurements</div>
				<div class="salwar_measurement_details">
					<?php foreach ($salwar_attr as $key => $_salwar) {
						$_salwar1 = Mage::getModel('measurement/measurement')->load($_salwar);
						$customtitles = Mage::getModel('measurement/customtitles')->getCollection()->addFieldToFilter('measurement_id',$_salwar1->getMeasurementId());
						$min = $_salwar1->getMinVal();
						$max = $_salwar1->getMaxVal();
						if($_REQUEST['units'] == 'cm'){ 
							$unit = 2.54;
							$min = round( ($min*$unit), 2);
							$min = 5 * round($min / 5, 2);
							$max = round( ($max*$unit), 2);
							$max = 5 * round($max / 5, 2);
						}
						$originalmin = $min;
						$difference = $_salwar1->getDifference(); ?>
						<div class="m_attr"><label id="label" class="<?php if($_salwar1->getIsRequired() == 1){ echo "required"; } ?>"><?php if($_salwar1->getIsRequired() == 1){ echo "<em>*</em>"; } ?><?php echo $_salwar1->getTitle(); ?></label>
							<label class="value">
								<?php if($_salwar1->getFieldType() == 'radio') {
									foreach ($customtitles as $key => $_customtitle) { ?>
										<label class="radio_button"><input id="<?php if($_salwar1->getIsRequired() == 1){ echo "required-entry"; } ?>" name="<?php echo $_REQUEST['service']; ?>[<?php echo $_salwar1->getMeasurementId(); ?>]" type="radio" value="<?php echo $_customtitle->getCustomTitleId(); ?>" /><?php echo $_customtitle->getTitle(); ?></label>
									<?php } ?>
								<?php } elseif($_salwar1->getFieldType() == 'text_area') { ?>
									<label class="value">
										<textarea class="<?php if($_salwar1->getIsRequired() == 1){ echo "required-entry"; } ?>" name="<?php echo $_REQUEST['service']; ?>[<?php echo $_salwar1->getMeasurementId(); ?>]" cols="45" rows="3" style="resize: none;" id="<?php if($_salwar1->getIsRequired() == 1){ echo "required-entry"; } ?>"></textarea>
									</label>
								<?php }elseif($_salwar1->getFieldType() == 'text_field') { ?>
									<input class="measurement_textfield <?php if($_salwar1->getIsRequired() == 1){ echo "required-entry"; } ?>" type="number" step="<?php echo $difference; ?>" name="<?php echo $_REQUEST['service']; ?>[<?php echo $_salwar1->getMeasurementId(); ?>]" min="<?php echo $min; ?>" max="<?php echo $max; ?>" id="<?php if($_salwar1->getIsRequired() == 1){ echo "required-entry"; } ?>" >
									<span><span><?php echo '('.$min.' - '.$max.')'; ?></span><span><?php echo $_REQUEST['units']; ?></span></span>
								<?php }elseif($_salwar1->getFieldType() == 'dropdown') {
									if($_salwar1->getDropdownType() == 'standard') { ?>
									 	<select id="<?php if($_salwar1->getIsRequired() == 1){ echo "required-entry"; } ?>" class="<?php if($_salwar1->getIsRequired() == 1){ echo "required-entry"; } ?>" name="<?php echo $_REQUEST['service']; ?>[<?php echo $_salwar1->getMeasurementId(); ?>]">
											<option></option>
											<?php while($min <= $max) { ?>
												<option><?php echo $min; ?></option>
												<?php $min += $difference;
											} ?>
										</select>
										<span><span><?php echo '('.$originalmin.' - '.$max.')'; ?></span><span><?php echo $_REQUEST['units']; ?></span></span>
									<?php }else if($_salwar1->getDropdownType() == 'custom'){ ?>
									 	<select id="<?php if($_salwar1->getIsRequired() == 1){ echo "required-entry"; } ?>" class="<?php if($_salwar1->getIsRequired() == 1){ echo "required-entry"; } ?>" name="<?php echo $_REQUEST['service']; ?>[<?php echo $_salwar1->getMeasurementId(); ?>]">
											<option></option>
											<?php foreach ($customtitles as $key => $_customtitle) { ?>
												<option value="<?php echo $_customtitle->getCustomTitleId(); ?>"><?php echo $_customtitle->getTitle(); ?></option>
											<?php } ?>
										</select>
									<?php } ?>
								<?php } ?>
							</label>
							<?php if(!empty($_salwar1->getImage())) { ?>
								<label class="image"><img width="190" height="230" title="Image" alt="Image" src="<?php echo Mage::getBaseUrl('media').$_salwar1->getImage(); ?>"></label>
							<?php } ?>
							<label class="content">
								<h5>Ho to Measure</h5>
								<h3><?php echo strtoupper($_salwar1->getTitle()); ?></h3>
								<?php echo $_salwar1->getContent(); ?>
							</label>
						</div>

					<?php } ?>
				</div>
				<div class="more_info"></div>
			</div>
		<?php }
		if(strlen($lehanga['measurement_attr']) > 0) {
			$lehanga_attr = explode(',', $lehanga['measurement_attr']); ?>
			<div class="lehanga_measurements" id="measurements_group">
				<div class="title">Lehanga Measurements</div>
				<div class="lehanga_measurement_details">
					<?php foreach ($lehanga_attr as $key => $_lehanga) {
						$_lehanga1 = Mage::getModel('measurement/measurement')->load($_lehanga);
						$customtitles = Mage::getModel('measurement/customtitles')->getCollection()->addFieldToFilter('measurement_id',$_lehanga1->getMeasurementId());
						$min = $_lehanga1->getMinVal();
						$max = $_lehanga1->getMaxVal();
						if($_REQUEST['units'] == 'cm'){ 
							$unit = 2.54;
							$min = round( ($min*$unit), 2);
							$min = 5 * round($min / 5, 2);
							$max = round( ($max*$unit), 2);
							$max = 5 * round($max / 5, 2);
						}
						$originalmin = $min;
						$difference = $_lehanga1->getDifference(); ?>
						<div class="m_attr"><label id="label" class="<?php if($_lehanga1->getIsRequired() == 1){ echo "required"; } ?>"><?php if($_lehanga1->getIsRequired() == 1){ echo "<em>*</em>"; } ?><?php echo $_lehanga1->getTitle(); ?></label>
							<label class="value">
								<?php if($_lehanga1->getFieldType() == 'radio') {
									foreach ($customtitles as $key => $_customtitle) { ?>
										<label class="radio_button"><input id="<?php if($_lehanga1->getIsRequired() == 1){ echo "required-entry"; } ?>" name="<?php echo $_REQUEST['service']; ?>[<?php echo $_lehanga1->getMeasurementId(); ?>]" type="radio" value="<?php echo $_customtitle->getCustomTitleId(); ?>" /><?php echo $_customtitle->getTitle(); ?></label>
									<?php } ?>
								<?php } elseif($_lehanga1->getFieldType() == 'text_area') { ?>
									<label class="value">
										<textarea class="<?php if($_lehanga1->getIsRequired() == 1){ echo "required-entry"; } ?>" name="<?php echo $_REQUEST['service']; ?>[<?php echo $_lehanga1->getMeasurementId(); ?>]" cols="45" rows="3" style="resize: none;" id="<?php if($_lehanga1->getIsRequired() == 1){ echo "required-entry"; } ?>"></textarea>
									</label>
								<?php }elseif($_lehanga1->getFieldType() == 'text_field') { ?>
									<input id="<?php if($_lehanga1->getIsRequired() == 1){ echo "required-entry"; } ?>" class="measurement_textfield <?php if($_lehanga1->getIsRequired() == 1){ echo "required-entry"; } ?>" type="number" step="<?php echo $difference; ?>" name="<?php echo $_REQUEST['service']; ?>[<?php echo $_lehanga1->getMeasurementId(); ?>]" min="<?php echo $min; ?>" max="<?php echo $max; ?>" >
									<span><span><?php echo '('.$min.' - '.$max.')'; ?></span><span><?php echo $_REQUEST['units']; ?></span></span>
								<?php }elseif($_lehanga1->getFieldType() == 'dropdown') {
									if($_lehanga1->getDropdownType() == 'standard') { ?>
									 	<select id="<?php if($_lehanga1->getIsRequired() == 1){ echo "required-entry"; } ?>" class="<?php if($_lehanga1->getIsRequired() == 1){ echo "required-entry"; } ?>" name="<?php echo $_REQUEST['service']; ?>[<?php echo $_lehanga1->getMeasurementId(); ?>]">
											<option></option>
											<?php while($min <= $max) { ?>
												<option><?php echo $min; ?></option>
												<?php $min += $difference;
											} ?>
										</select>
										<span><span><?php echo '('.$originalmin.' - '.$max.')'; ?></span><span><?php echo $_REQUEST['units']; ?></span></span>
									<?php }else if($_lehanga1->getDropdownType() == 'custom'){ ?>
									 	<select id="<?php if($_lehanga1->getIsRequired() == 1){ echo "required-entry"; } ?>" class="<?php if($_lehanga1->getIsRequired() == 1){ echo "required-entry"; } ?>" name="<?php echo $_REQUEST['service']; ?>[<?php echo $_lehanga1->getMeasurementId(); ?>]">
											<option></option>
											<?php foreach ($customtitles as $key => $_customtitle) { ?>
												<option value="<?php echo $_customtitle->getCustomTitleId(); ?>"><?php echo $_customtitle->getTitle(); ?></option>
											<?php } ?>
										</select>
									<?php } ?>
								<?php } ?>
							</label>
							<?php if(!empty($_lehanga1->getImage())) { ?>
								<label class="image"><img width="190" height="230" title="Image" alt="Image" src="<?php echo Mage::getBaseUrl('media').$_lehanga1->getImage(); ?>"></label>
							<?php } ?>
							<label class="content">
								<h5>Ho to Measure</h5>
								<h3><?php echo strtoupper($_lehanga1->getTitle()); ?></h3>
								<?php echo $_lehanga1->getContent(); ?>
							</label>
						</div>

					<?php } ?>
				</div>
				<div class="more_info"></div>
			</div>
		<?php }
		if(strlen($tassel['measurement_attr']) > 0) {
			$tassel_attr = explode(',', $tassel['measurement_attr']); ?>
			<div class="tassel_measurements" id="measurements_group">
				<div class="title">Tassel Measurements</div>
				<div class="tassel_measurement_details">
					<?php foreach ($tassel_attr as $key => $_tassel) {
						$_tassel1 = Mage::getModel('measurement/measurement')->load($_tassel);
						$customtitles = Mage::getModel('measurement/customtitles')->getCollection()->addFieldToFilter('measurement_id',$_tassel1->getMeasurementId());
						$min = $_tassel1->getMinVal();
						$max = $_tassel1->getMaxVal();
						if($_REQUEST['units'] == 'cm'){ 
							$unit = 2.54;
							$min = round( ($min*$unit), 2);
							$min = 5 * round($min / 5, 2);
							$max = round( ($max*$unit), 2);
							$max = 5 * round($max / 5, 2);
						}
						$originalmin = $min;
						$difference = $_tassel1->getDifference(); ?>
						<div class="m_attr">
							<label id="label" class="<?php if($_tassel1->getIsRequired() == 1){ echo "required"; } ?>"><?php if($_tassel1->getIsRequired() == 1){ echo "<em>*</em>"; } ?><?php echo $_tassel1->getTitle(); ?></label>
							<label class="value">
								<?php if($_tassel1->getFieldType() == 'radio') { ?>
									<?php foreach ($customtitles as $key => $_customtitle) { ?>
										<label class="radio_button"><input id="<?php if($_tassel1->getIsRequired() == 1){ echo "required-entry"; } ?>" name="<?php echo $_REQUEST['service']; ?>[<?php echo $_tassel1->getMeasurementId(); ?>]" type="radio" value="<?php echo $_customtitle->getCustomTitleId(); ?>" /><?php echo $_customtitle->getTitle(); ?></label>
									<?php } ?>
								<?php } elseif($_tassel1->getFieldType() == 'text_area') { ?>
									<label class="value">
										<textarea id="<?php if($_tassel1->getIsRequired() == 1){ echo "required-entry"; } ?>" class="<?php if($_tassel1->getIsRequired() == 1){ echo "required-entry"; } ?>" name="<?php echo $_REQUEST['service']; ?>[<?php echo $_tassel1->getMeasurementId(); ?>]" class="" cols="45" rows="3" style="resize: none;"></textarea>
									</label>
								<?php }elseif($_tassel1->getFieldType() == 'text_field') { ?>
									<input class="measurement_textfield <?php if($_tassel1->getIsRequired() == 1){ echo "required-entry"; } ?>" type="number" step="<?php echo $difference; ?>" name="<?php echo $_REQUEST['service']; ?>[<?php echo $_tassel1->getMeasurementId(); ?>]" min="<?php echo $min; ?>" max="<?php echo $max; ?>" id="<?php if($_tassel1->getIsRequired() == 1){ echo "required-entry"; } ?>" >
									<span><span><?php echo '('.$min.' - '.$max.')'; ?></span><span><?php echo $_REQUEST['units']; ?></span></span>
								<?php }elseif($_tassel1->getFieldType() == 'dropdown') {
									if($_tassel1->getDropdownType() == 'standard') { ?>
									 	<select id="<?php if($_tassel1->getIsRequired() == 1){ echo "required-entry"; } ?>" class="<?php if($_tassel1->getIsRequired() == 1){ echo "required-entry"; } ?>" name="<?php echo $_REQUEST['service']; ?>[<?php echo $_tassel1->getMeasurementId(); ?>]">
											<option></option>
											<?php while($min <= $max) { ?>
												<option><?php echo $min; ?></option>
												<?php $min += $difference;
											} ?>
										</select>
										<span><span><?php echo '('.$originalmin.' - '.$max.')'; ?></span><span><?php echo $_REQUEST['units']; ?></span></span>
									 <?php }else if($_tassel1->getDropdownType() == 'custom'){ ?>
									 	<select id="<?php if($_tassel1->getIsRequired() == 1){ echo "required-entry"; } ?>" class="<?php if($_tassel1->getIsRequired() == 1){ echo "required-entry"; } ?>" name="<?php echo $_REQUEST['service']; ?>[<?php echo $_tassel1->getMeasurementId(); ?>]">
											<option></option>
											<?php foreach ($customtitles as $key => $_customtitle) { ?>
												<option value="<?php echo $_customtitle->getCustomTitleId(); ?>"><?php echo $_customtitle->getTitle(); ?></option>
											<?php } ?>
										</select>
									 <?php } ?>
								<?php } ?>
							</label>
							<?php if (!empty($_tassel1->getImage())) { ?>
								<label class="image"><img width="190" height="230" title="Image" alt="Image" src="<?php echo Mage::getBaseUrl('media').$_tassel1->getImage(); ?>"></label>
							<?php } ?>
							<label class="content">
								<h5>Ho to Measure</h5>
								<h3><?php echo strtoupper($_tassel1->getTitle()); ?></h3>
								<?php echo $_tassel1->getContent(); ?>
							</label>
						</div>

					<?php } ?>
				</div>
				<div class="more_info"></div>
			</div>

		<?php }
	?>
	<script type="text/javascript">
		var jQuery = jQuery.noConflict();
		jQuery(function(){
			jQuery('label.value input').focus( function() {
				jQuery(jQuery(this).parent().parent()).find('label.content:first').show();
				jQuery(jQuery(this).parent().parent()).find('label.image:first').show();
			});
			jQuery('label.value input').blur( function() {
				jQuery(jQuery(this).parent().parent()).find('label.content:first').hide();
				jQuery(jQuery(this).parent().parent()).find('label.image:first').hide();
			});
			jQuery('label.value select').focus( function() {
				jQuery(jQuery(this).parent().parent()).find('label.content:first').show();
				jQuery(jQuery(this).parent().parent()).find('label.image:first').show();
			});
			jQuery('label.value select').blur( function() {
				jQuery(jQuery(this).parent().parent()).find('label.content:first').hide();
				jQuery(jQuery(this).parent().parent()).find('label.image:first').hide();
			});
			jQuery("label.value input").hover(
				function(){
					jQuery(jQuery(this).parent().parent()).find('label.content:first').toggle();
					jQuery(jQuery(this).parent().parent()).find('label.image:first').toggle();
				},
				function(){
					jQuery(jQuery(this).parent().parent()).find('label.content:first').toggle();
					jQuery(jQuery(this).parent().parent()).find('label.image:first').toggle();
				}
			);
			jQuery("label.value select").hover(
				function(){
					jQuery(jQuery(this).parent().parent()).find('label.content:first').toggle();
					jQuery(jQuery(this).parent().parent()).find('label.image:first').toggle();
				},
				function(){
					jQuery(jQuery(this).parent().parent()).find('label.content:first').toggle();
					jQuery(jQuery(this).parent().parent()).find('label.image:first').toggle();
				}
			);
		});
	</script>
</div>
