<div class="measurement_block" id="measurement_step">
	<div class="options_submitting_measurement">
		<div id="submitting_measurement_option"><input id="<?php echo $_REQUEST['service']; ?>" class="submitting_measurement_option" type="radio" name="measurement_type" value="simple" / > <b>Sample</b></div>
		<div id="submitting_measurement_option"><input id="<?php echo $_REQUEST['service']; ?>" class="submitting_measurement_option" type="radio" name="measurement_type" value="standard" / > <b>Standard Measurement</b></div>
		<div id="submitting_measurement_option"><input id="<?php echo $_REQUEST['service']; ?>" class="submitting_measurement_option" type="radio" name="measurement_type" value="custom" / > <b>Custom Measurement</b></div>
	</div>
	<div class="my_stored_measurement"></div>
	<div class="measuring_units"></div>
	<div class="measurement_attributes">
		<div class="simple_measurements"></div>
		<div class="standard_measurements"></div>
		<div class="custom_measurements"></div>
	</div>
	<div class="goto_nextstep"><input type="button" class="goto_reviewstep" value="Next Step" /></div>
</div>
<script type="text/javascript">
    var jQuery = jQuery.noConflict();
    jQuery(function(){
    	jQuery('.goto_reviewstep').click(function() {
    		var errorcount = 0;
			jQuery('.measurement_attributes').find('#required-entry').each(function(){
				var type = jQuery(this).attr('type');
				if (type == 'text' || type == 'number') {
					var size = jQuery(this).val().length;
				} else if(type == 'radio') {
					var name = jQuery(this).attr('name');
					var size = jQuery('input:radio[name='+name+']:checked').val().length;
				} else{
					var size = jQuery(this).val().length;
				}
				if(size == 0){
					jQuery(this).focus();
					jQuery(this).css('border','1px solid');
					jQuery(this).css('color','red');
					errorcount++;
					return false;
				}else{
					jQuery(this).attr('style','');
				}
			});
			if(errorcount == 0) {
				var data1 = jQuery("form#measurement11").serialize();
	    		var url1 = '<?php echo Mage::getBaseUrl(); ?>measurement/measure/getreviewblock';
				try {
					jQuery.ajax({
						url: url1,
						type : 'post',
						data: data1,
						success: function(response){
							if (response) {
								// jQuery('.measurement_block').toggle();
								jQuery('.measurement_review').replaceWith(response);
							}
						}
					});
				} catch(e){ }
			}
    	});

		jQuery('input.submitting_measurement_option').click(function() {
			jQuery('.measurement_block').find('.goto_nextstep:first').show();
			if(this.value == 'simple'){
				jQuery('.measuring_units').replaceWith('<div class="measuring_units"></div>');
				jQuery('.standard_measurements').replaceWith('<div class="standard_measurements"></div>');
				jQuery('.custom_measurements').replaceWith('<div class="custom_measurements"></div>');
				var data1 = "&service="+jQuery('.service').val();
				var url1 = '<?php echo Mage::getBaseUrl(); ?>measurement/measure/getsimplemeasurements';
				try {
					jQuery.ajax({
						url: url1,
						type : 'post',
						data: data1,
						success: function(response){
							if (response) {
								jQuery('.simple_measurements').replaceWith(response);
							}
						}
					});
				} catch(e){ }
			}else if(this.value == 'standard') {
				jQuery('.simple_measurements').replaceWith('<div class="simple_measurements"></div>');
				jQuery('.custom_measurements').replaceWith('<div class="custom_measurements"></div>');
				var data1 = "&service="+jQuery('.service').val();
				var url1 = '<?php echo Mage::getBaseUrl(); ?>measurement/measure/getmeasurementunits';
				try {
					jQuery.ajax({
						url: url1,
						type : 'post',
						data: data1,
						success: function(response){
							if (response) {
								jQuery('.measuring_units').replaceWith(response);
							}
						}
					});
				} catch(e){ }
			} else if(this.value == 'custom') {
				jQuery('.simple_measurements').replaceWith('<div class="simple_measurements"></div>');
				jQuery('.standard_measurements').replaceWith('<div class="standard_measurements"></div>');
				jQuery('.custom_measurements').replaceWith('<div class="custom_measurements"></div>');
				var data1 = "&service="+jQuery('.service').val();
				var url1 = '<?php echo Mage::getBaseUrl(); ?>measurement/measure/getmeasurementunits';
				try {
					jQuery.ajax({
						url: url1,
						type : 'post',
						data: data1,
						success: function(response){
							if (response) {
								jQuery('.measuring_units').replaceWith(response);
							}
						}
					});
				} catch(e){ }
			}
        });
	});
</script>