<?php 
	$attr = Mage::getModel('catalog/product')->getResource()->getAttribute("a27");
	if (isset($_REQUEST['product_id'])) {
		$_product = Mage::getModel('catalog/product')->load($_REQUEST['product_id']);
		$imageUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'catalog/product' . $_product->getImage();
		$imageCacheUrl = Mage::helper('catalog/image')->init($_product, 'image')->resize(200,300);
		$from = Mage::app()->getStore()->getBaseCurrencyCode();
		$to = Mage::app()->getStore()->getCurrentCurrencyCode();
		$quote_id_val = Mage::getSingleton('checkout/session')->getQuoteId();
		$c_id = Mage::getSingleton('customer/session')->getCustomer()->getId();
	?>
	<div class="measurements_taking_for">
		<div class="product_image"><img src="<?php echo $imageCacheUrl; ?>" /></div>
		<div class="product_details">
			<div><h4><?php echo $_product->getName(); ?></h4></div>
			<div><?php echo 'SKU : '.$_product->getSku(); ?></div>
			<?php $attribute = Mage::getModel('eav/config')->getAttribute('catalog_product', 'a27');
			$options = array();
			foreach( $attribute->getSource()->getAllOptions(true, true) as $option ) {
				if(strlen($option['label']) > 0){
					$options[$option['value']] = $option['label'];
				}
			}
			if(isset($_REQUEST['order_id']) && $_REQUEST['order_id'] > 0) {
				$_order = Mage::getModel('sales/order')->load($_REQUEST['order_id']);
				foreach ($_order->getAllItems() as $item) {
					if ($item->getProductId() == $_product->getId()) {
						// echo $_product->getId();
						$stored_stitchings = Mage::getModel('newaddaction/newaddaction')->getCollection()->addFieldToFilter('product_id',$_product->getId())->addFieldToFilter('quote_id',$_order->getQuoteId())->getFirstItem();
						if(sizeof($stored_stitchings) > 0) {
							foreach ($options as $key => $value) {
								if (isset($stored_stitchings[$key]) && $stored_stitchings[$key] > 0 && $key != 8 && $key != 9) {
									$is_submited = Mage::getModel('measurementremember/measurementremember')->getCollection()->addFieldToFilter('product_id',$_product->getId())->addFieldToFilter('quote_id',$_order->getQuoteId())->addFieldToFilter('c_id',$c_id)->addFieldToFilter('stitching_service_id',$key)->getFirstItem();
									if ($is_submited->getMeasurementrememberId() > 0) { ?>
										
									<?php } else{
										$stitching = Mage::getModel('stitchingservices/stitchingservices')->load($stored_stitchings[$key]);
										$type_stitching_name = $attr->getSource()->getOptionText($stitching->getStitchingServiceId()); ?>
										<div><?php echo '<b>'.$type_stitching_name.' : </b>'.$stitching->getTitle() ?> &nbsp; <a href="<?php echo Mage::getBaseUrl(); ?>measurement?product_id=<?php echo $_product->getId(); ?>&stitching_type=<?php echo $stored_stitchings[$key]; ?><?php if (isset($_REQUEST['order_id'])) { echo '&order_id='.$_REQUEST['order_id']; }?>">Submit Now</a></div>
									<?php } ?>
								<?php }
							}
						}
					}
				}
			 ?>
			<?php } else{ ?>
				<?php $stored_stitchings = Mage::getModel('newaddaction/newaddaction')->getCollection()->addFieldToFilter('product_id',$_product->getId())->addFieldToFilter('quote_id',$quote_id_val)->getFirstItem(); ?>
				<?php if(sizeof($stored_stitchings) > 0) {
					foreach ($options as $key => $value) {
						if (isset($stored_stitchings[$key]) && $stored_stitchings[$key] > 0 && $key != 8 && $key != 9) {
							$is_submited = Mage::getModel('measurementremember/measurementremember')->getCollection()->addFieldToFilter('product_id',$_product->getId())->addFieldToFilter('quote_id',$quote_id_val)->addFieldToFilter('c_id',$c_id)->addFieldToFilter('stitching_service_id',$key)->getFirstItem();
							if ($is_submited->getMeasurementrememberId() > 0) { ?>
								
							<?php } else{
								$stitching = Mage::getModel('stitchingservices/stitchingservices')->load($stored_stitchings[$key]);
								$type_stitching_name = $attr->getSource()->getOptionText($stitching->getStitchingServiceId()); ?>
								<div><?php echo '<b>'.$type_stitching_name.' : </b>'.$stitching->getTitle().' - '.Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol().Mage::helper('directory')->currencyConvert($stitching->getStitchingServicePrice(), $from, $to); ?> &nbsp; <a href="<?php echo Mage::getBaseUrl(); ?>measurement?product_id=<?php echo $_product->getId(); ?>&stitching_type=<?php echo $stored_stitchings[$key]; ?><?php if (isset($_REQUEST['order_id'])) { echo '&order_id='.$_REQUEST['order_id']; }?>">Submit Now</a></div>
							<?php } ?>
						<?php }
					}
				} ?>
			<?php } ?>
		</div>
	</div>
	<?php }
	if (isset($_REQUEST['measurement_id']) && $_REQUEST['measurement_id'] > 0) {
		$_product = Mage::getModel('catalog/product')->load($_REQUEST['product_id']);
		$measurementremember = Mage::getModel('measurementremember/measurementremember')->load($_REQUEST['measurement_id']);
		$measurementremember1 = Mage::getModel('measurementremember/flatrates')->getCollection()->addFieldToFilter('measurementremember_id',$measurementremember->getMeasurementrememberId())->getFirstItem();
	 	if (isset($measurementremember) && isset($_product)) {
	 		$frontcollection = Mage::getModel('styles/styles')
												->getCollection()
												->addFieldToFilter('status',1)
												->addFieldToFilter('stitching_service_id',$measurementremember->getStitchingServiceId())
												->addFieldToFilter('stitching_service', array('like' => '%'.$_REQUEST['stitching_type'].'%'));
			$backcollection = Mage::getModel('back/back')
												->getCollection()
												->addFieldToFilter('status',1)
												->addFieldToFilter('front_id',$measurementremember1->getFrontId());
			$sleevecollection = Mage::getModel('sleeves/sleeves')
												->getCollection()
												->addFieldToFilter('status',1)
												->addFieldToFilter('front_id',$measurementremember1->getFrontId())
												->addFieldToFilter('back_id',$measurementremember1->getBackId());
			$lehangacollection = Mage::getModel('lehanga/lehanga')
												->getCollection()
												->addFieldToFilter('status',1)
												->addFieldToFilter('lehanga_id',$measurementremember1->getLehangaId());
			$salwarcollection = Mage::getModel('salwar/salwar')
												->getCollection()
												->addFieldToFilter('status',1)
												->addFieldToFilter('salwar_id',$measurementremember1->getSalwarId());
			$tasselcollection = Mage::getModel('tassel/tassel')
												->getCollection()
												->addFieldToFilter('status',1)
												->addFieldToFilter('tassel_id',$measurementremember1->getTasselId());

	 		$stitching_name = $attr->getSource()->getOptionText($measurementremember->getStitchingServiceId()); ?>
	 		<input type="hidden" id="front_id" data="<?php echo $measurementremember1->getFrontId(); ?>">
			<input type="hidden" id="back_id" data="<?php echo $measurementremember1->getBackId(); ?>">
			<input type="hidden" id="sleeve_id" data="<?php echo $measurementremember1->getSleeveId(); ?>">
			<input type="hidden" id="lehanga_id" data="<?php echo $measurementremember1->getLehangaId(); ?>">
			<input type="hidden" id="salwar_id" data="<?php echo $measurementremember1->getSalwarId(); ?>">
			<input type="hidden" id="tassel_id" data="<?php echo $measurementremember1->getTasselId(); ?>">
	 		<form action="<?php echo Mage::getBaseUrl(); ?>measurementremember/measurement/edit" method="post" id="editmeasurement">
	 			<div class="product_measurement">
	 				<div class="tabed"><a class="selectedTab" href="javascript:;"><?php echo $stitching_name; ?></a></div>
	 				<input type="hidden" name="service" class="service" value="<?php echo $measurementremember->getStitchingServiceId(); ?>" />
					<input type="hidden" name="customer_id" class="customer_id" value="<?php echo Mage::getSingleton('customer/session')->getId(); ?>" />
					<input type="hidden" name="product_id" class="product_id" value="<?php echo $_product->getId(); ?>" />
					<input type="hidden" name="stitching_type" class="stitching_type" value="<?php echo $_REQUEST['stitching_type']; ?>" />
					<input type="hidden" name="measurement_id" class="measurement_id" value="<?php echo $measurementremember->getMeasurementrememberId(); ?>" />
					<div class="measure_details">
						<div class="measure_detail" id="style_fit">
							<div class="label_title"><label>1. Style</label></div>
							<div class="style_fit_details" id="measurement_step">
								<?php if(sizeof($frontcollection) > 0) { ?>
									<div class="clearer"></div>
									<div class="front">
										<div class="label_title1"><label>Front Styles</label></div>
										<div class="front_style_details">
											<ul class="front_style" id="item_style">
											<?php foreach($frontcollection as $key => $_front) { ?>
												<li class="front_style_li">
													<div class="title"><label><?php echo $_front->getTitle(); ?></label></div>
													<div class="image"><img width="130" height="180" alt="<?php echo $_front->getTitle(); ?>" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$_front->getImage(); ?>"></div>
													<div class="select_option"><input class="front_id" name="front_id" type="radio" <?php if($_front->getStyleId() == $measurementremember1->getFrontId()){ echo 'checked'; } ?> value="<?php echo $_front->getStyleId(); ?>" /></div>
												</li>
											<?php } ?>
											</ul>
										</div>
									</div>
								<?php } ?>
								<?php if(sizeof($backcollection) > 0) { ?>
									<div class="clearer"></div>
									<div class="back">
										<div class="label_title1"><label>Back Styles</label></div>
										<div class="back_style_details">
											<ul class="back_style" id="item_style1">
												<?php foreach ($backcollection as $key => $_back) { ?>
													<li class="back_style_li">
													<div class="title"><label><?php echo $_back->getTitle(); ?></label></div>
													<div class="image"><img width="130" height="180" alt="<?php echo $_back->getTitle(); ?>" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$_back->getImage(); ?>"></div>
													<div class="select_option"><input <?php if($_back->getBackId() == $measurementremember1->getBackId()){ echo 'checked'; } ?> class="back_id" name="back_id" type="radio" value="<?php echo $_back->getBackId(); ?>" /></div>
													</li>
												<?php } ?>
											</ul>
										</div>
									</div>
								<?php } ?>
								<?php if(sizeof($sleevecollection) > 0) { ?>
									<div class="clearer"></div>
									<div class="sleeve">
										<div class="label_title1"><label>Sleeve Styles</label></div>
										<div class="sleeve_style_details">
											<ul class="sleeve_style" id="item_style2">
												<?php foreach ($sleevecollection as $key => $_sleeve) { ?>
													<li class="sleeve_style_li">
													<div class="title"><label><?php echo $_sleeve->getTitle(); ?></label></div>
													<div class="image"><img width="130" height="180" alt="<?php echo $_sleeve->getTitle(); ?>" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$_sleeve->getImage(); ?>"></div>
													<div class="select_option"><input <?php if($_sleeve->getSleevesId() == $measurementremember1->getSleeveId()){ echo 'checked'; } ?> class="sleeve_id" name="sleeve_id" type="radio" value="<?php echo $_sleeve->getSleevesId(); ?>" /></div>
													</li>
												<?php } ?>
											</ul>
										</div>
									</div>
								<?php } ?>
								<?php if(sizeof($lehangacollection) > 0) { ?>
									<div class="clearer"></div>
									<div class="lehanga">
										<div class="label_title1"><label>Lehanga/Skirt/Petticoat Styles</label></div>
										<div class="lehanga_style_details">
											<ul class="lehanga_style" id="item_style3">
												<?php foreach ($lehangacollection as $key => $_lehanga) { ?>
													<li class="lehanga_style_li">
													<div class="title"><label><?php echo $_lehanga->getTitle(); ?></label></div>
													<div class="image"><img width="130" height="180" alt="<?php echo $_lehanga->getTitle(); ?>" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$_lehanga->getImage(); ?>"></div>
													<div class="select_option"><input class="lehanga_id" name="lehanga_id" type="radio" value="<?php echo $_lehanga->getLehangaId(); ?>" /></div>
													</li>
												<?php } ?>
											</ul>
										</div>
									</div>
								<?php } ?>
								<?php if(sizeof($salwarcollection) > 0) { ?>
									<div class="clearer"></div>
									<div class="salwar">
										<div class="label_title1"><label>Salwar Styles</label></div>
										<div class="salware_style_details">
											<ul class="salwar_style" id="item_style4">
												<?php foreach ($salwarcollection as $key => $_salwar) { ?>
													<li class="salwar_style_li">
													<div class="title"><label><?php echo $_salwar->getTitle(); ?></label></div>
													<div class="image"><img width="130" height="180" alt="<?php echo $_salwar->getTitle(); ?>" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$_salwar->getImage(); ?>"></div>
													<div class="select_option"><input <?php if($_salwar->getSalwarId() == $measurementremember1->getSalwarId()){ echo 'checked'; } ?> class="salwar_id" name="salwar_id" type="radio" value="<?php echo $_salwar->getSalwarId(); ?>" /></div>
													</li>
												<?php } ?>
											</ul>
										</div>
									</div>
								<?php } ?>
								<?php if(sizeof($tasselcollection) > 0) { ?>
									<div class="clearer"></div>
									<div class="tassel">
										<div class="label_title1"><label>Tassele Styles</label></div>
										<div class="tassel_style_details">
											<ul class="tassel_style" id="item_style5">
												<?php foreach ($tasselcollection as $key => $_tassel) { ?>
													<li class="tassel_style_li">
													<div class="title"><label><?php echo $_tassel->getTitle(); ?></label></div>
													<div class="image"><img width="130" height="180" alt="<?php echo $_tassel->getTitle(); ?>" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$_tassel->getImage(); ?>"></div>
													<div class="select_option"><input <?php if($_tassel->getTasselId() == $measurementremember1->getTasselId()){ echo 'checked'; } ?> class="tassel_id" name="tassel_id" type="radio" value="<?php echo $_tassel->getTasselId(); ?>" /></div>
													</li>
												<?php } ?>
											</ul>
										</div>
									</div>
								<?php } ?>
							</div>
						</div>
						<div class="clearer"></div>
						<div class="measure_detail" id="measurement">
							<div class="label_title"><label>2. Measurements & Fit</label>
							</div>
							<div class="measurement_details" id="measurement_step">
								<div class="measurement_block" id="measurement_step">
									<div class="options_submitting_measurement">
										<div id="submitting_measurement_option"><input class="submitting_measurement_option" type="radio" name="measurement_type" value="simple" / > <b>Sample</b></div>
										<div id="submitting_measurement_option"><input class="submitting_measurement_option" type="radio" name="measurement_type" value="standard" / > <b>Standard Measurement</b></div>
										<div id="submitting_measurement_option"><input class="submitting_measurement_option" type="radio" name="measurement_type" checked value="custom" / > <b>Custom Measurement</b></div>
									</div>
									<div class="measuring_units"><p>
										<input <?php if($measurementremember1->getMeasurmentUnits() == 'in'){ echo 'checked'; } ?> class="measuring_unit" type="radio" name="measurment_units" value="in"> Inchs
										<input <?php if($measurementremember1->getMeasurmentUnits() == 'cm'){ echo 'checked'; } ?> class="measuring_unit" type="radio" name="measurment_units" value="cm"> Centemeters
									</p></div>
									<div class="measurement_attributes">
										<div class="simple_measurements"></div>
										<div class="standard_measurements"></div>
										<div class="custom_measurements">
											<div class="m_attr">
												<label id="label" class="required"><b>Measurements For </b></label>
												<label class="value"><input type="text" name="storing_for" class="measurement_textfield required-entry" value="<?php echo $measurementremember->getTitle(); ?>" /></label>
												<label class="content" id="content">Name for your Measurements Set e.g. MySelf, Mom, Sister, etc...</label>
											</div>
											<?php $front = Mage::getModel('styles/styles')->getCollection()->addFieldToSelect('measurement_attr')->addFieldToFilter('style_id',$measurementremember1->getFrontId())->addFieldToFilter('status',1)->getFirstItem();
												$back = Mage::getModel('back/back')->getCollection()->addFieldToSelect('measurement_attr')->addFieldToFilter('back_id',$measurementremember1->getBackId())->addFieldToFilter('status',1)->getFirstItem();
												$sleeve = Mage::getModel('sleeves/sleeves')->getCollection()->addFieldToSelect('measurement_attr')->addFieldToFilter('sleeves_id',$measurementremember1->getSleeveId())->addFieldToFilter('status',1)->getFirstItem();
												$lehanga = Mage::getModel('lehanga/lehanga')->getCollection()->addFieldToSelect('measurement_attr')->addFieldToFilter('lehanga_id',$measurementremember1->getLehangaId())->addFieldToFilter('status',1)->getFirstItem();
												$salwar = Mage::getModel('salwar/salwar')->getCollection()->addFieldToSelect('measurement_attr')->addFieldToFilter('salwar_id',$measurementremember1->getSalwarId())->addFieldToFilter('status',1)->getFirstItem();
												$tassel = Mage::getModel('tassel/tassel')->getCollection()->addFieldToSelect('measurement_attr')->addFieldToFilter('tassel_id',$measurementremember1->getTasselId())->addFieldToFilter('status',1)->getFirstItem();
												if(strlen($front['measurement_attr']) > 0) {
													$front_attr = explode(',', $front['measurement_attr']); ?>
													<div class="front_measurements">
														<div class="front_measurement_details">
															<?php foreach ($front_attr as $key => $_front) {
																$_front1 = Mage::getModel('measurement/measurement')->load($_front);
																$customtitles = Mage::getModel('measurement/customtitles')->getCollection()->addFieldToFilter('measurement_id',$_front1->getMeasurementId());
																$min = $_front1->getMinVal();
																$max = $_front1->getMaxVal();
																if($measurementremember1->getMeasurmentUnits() == 'cm'){ 
																	$unit = 2.54;
																	$min = round( ($min*$unit), 2);
																	$min = 5 * round($min / 5, 2);
																	$max = round( ($max*$unit), 2);
																	$max = 5 * round($max / 5, 2);
																}
																$originalmin = $min;
																$b = $measurementremember1->{'get' .$_front1->getMeasurementId()}();
																$difference = $_front1->getDifference(); ?>
																<div class="m_attr"><label id="label" class="<?php if($_front1->getIsRequired() == 1){ echo "required"; } ?>"><?php echo $_front1->getTitle(); ?></label>
																	<label class="value">
																		<?php if($_front1->getFieldType() == 'radio') { ?>
																			<?php foreach ($customtitles as $key => $_customtitle) { ?>
																				<label class="radio_button"><input id="<?php if($_front1->getIsRequired() == 1){ echo "required-entry"; } ?>" <?php if(abs(($_customtitle->getCustomTitleId()-$b)/$b) < 0.00001) { echo 'checked'; } ?> name="<?php echo $measurementremember->getStitchingServiceId(); ?>[<?php echo $_front1->getMeasurementId(); ?>]" type="radio" value="<?php echo $_customtitle->getCustomTitleId(); ?>" class="<?php if($_front1->getIsRequired() == 1){ echo "required-entry"; } ?>" /><?php echo $_customtitle->getTitle(); ?></label>
																			<?php } ?>
																		<?php } elseif($_front1->getFieldType() == 'text_area') { ?>
																			<label class="value">
																				<textarea id="<?php if($_front1->getIsRequired() == 1){ echo "required-entry"; } ?>" class="<?php if($_front1->getIsRequired() == 1){ echo "required-entry"; } ?>" name="<?php echo $measurementremember->getStitchingServiceId(); ?>[<?php echo $_front1->getMeasurementId(); ?>]" cols="45" rows="3" style="resize: none;"><?php echo $measurementremember1->{'get' .$_front1->getMeasurementId()}(); ?></textarea>
																			</label>
																		<?php }elseif($_front1->getFieldType() == 'text_field') { ?>
																			<input id="<?php if($_front1->getIsRequired() == 1){ echo "required-entry"; } ?>" value="<?php echo $measurementremember1->{'get' .$_front1->getMeasurementId()}(); ?>" class="measurement_textfield <?php if($_front1->getIsRequired() == 1){ echo "required-entry"; } ?>" type="number" step="<?php echo $difference; ?>" name="<?php echo $measurementremember->getStitchingServiceId(); ?>[<?php echo $_front1->getMeasurementId(); ?>]" min="<?php echo $min; ?>" max="<?php echo $max; ?>" >
																			<span><span><?php echo '('.$min.' - '.$max.')'; ?></span><span><?php echo $_front1->getMeasurmentUnits(); ?></span></span>
																		<?php }elseif($_front1->getFieldType() == 'dropdown') {
																			if($_front1->getDropdownType() == 'standard') { ?>
																			 	<select id="<?php if($_front1->getIsRequired() == 1){ echo "required-entry"; } ?>" class="<?php if($_front1->getIsRequired() == 1){ echo "required-entry"; } ?>" name="<?php echo $measurementremember->getStitchingServiceId(); ?>[<?php echo $_front1->getMeasurementId(); ?>]">
																					<option></option>
																					<?php while($min <= $max) { ?>
																						<option <?php if(abs(($min-$b)/$b) < 0.00001) { echo 'selected'; } ?> ><?php echo $min; ?></option>
																						<?php $min += $difference;
																					} ?>
																				</select>
																				<span><span><?php echo '('.$originalmin.' - '.$max.')'; ?></span><span><?php echo $_front1->getMeasurmentUnits(); ?></span></span>
																			 <?php }else if($_front1->getDropdownType() == 'custom'){ ?>
																			 	<select id="<?php if($_front1->getIsRequired() == 1){ echo "required-entry"; } ?>" class="<?php if($_front1->getIsRequired() == 1){ echo "required-entry"; } ?>" name="<?php echo $measurementremember->getStitchingServiceId(); ?>[<?php echo $_front1->getMeasurementId(); ?>]">
																					<option></option>
																					<?php foreach ($customtitles as $key => $_customtitle) { ?>
																						<option <?php if (abs(($_customtitle->getCustomTitleId()-$b)/$b) < 0.00001) { echo 'selected'; } ?> value="<?php echo $_customtitle->getCustomTitleId(); ?>"><?php echo $_customtitle->getTitle(); ?></option>
																					<?php } ?>
																				</select>
																			 <?php } ?>
																		<?php } ?>
																	</label>
																	<?php if (!empty($_front1->getImage())) { ?>
																		<label class="image"><img width="250" height="280" title="Image" alt="Image" src="<?php echo Mage::getBaseUrl('media').$_front1->getImage(); ?>"></label>
																	<?php } ?>
																	<label class="content">
																		<h5>Ho to Measure</h5>
																		<h3><?php echo strtoupper($_front1->getTitle()); ?></h3>
																		<?php echo $_front1->getContent(); ?>
																	</label>
																</div>

															<?php } ?>
														</div>
													</div>

												<?php }
												if(strlen($back['measurement_attr']) > 0) {
													$back_attr = explode(',', $back['measurement_attr']); ?>
													<div class="back_measurements">
														<!-- <div class="title">Back Measurements</div> -->
														<div class="back_measurement_details">
															<?php foreach ($back_attr as $key => $_back) {
																$_back1 = Mage::getModel('measurement/measurement')->load($_back);
																$customtitles = Mage::getModel('measurement/customtitles')->getCollection()->addFieldToFilter('measurement_id',$_back1->getMeasurementId());
																$min = $_back1->getMinVal();
																$max = $_back1->getMaxVal();
																if($measurementremember1->getMeasurmentUnits() == 'cm'){ 
																	$unit = 2.54;
																	$min = round( ($min*$unit), 2);
																	$min = 5 * round($min / 5, 2);
																	$max = round( ($max*$unit), 2);
																	$max = 5 * round($max / 5, 2);
																}
																$originalmin = $min;
																$b = $measurementremember1->{'get' .$_back1->getMeasurementId()}();
																$difference = $_back1->getDifference(); ?>
																<div class="m_attr"><label id="label" class="<?php if($_back1->getIsRequired() == 1){ echo "required"; } ?>"><?php echo $_back1->getTitle(); ?></label>
																	<label class="value">
																		<?php if($_back1->getFieldType() == 'radio') { ?>
																			<?php foreach ($customtitles as $key => $_customtitle) { ?>
																				<label class="radio_button"><input id="<?php if($_back1->getIsRequired() == 1){ echo "required-entry"; } ?>" class="<?php if($_back1->getIsRequired() == 1){ echo "required-entry"; } ?>" <?php if(abs(($_customtitle->getCustomTitleId()-$b)/$b) < 0.00001) { echo 'checked'; } ?> name="<?php echo $measurementremember->getStitchingServiceId(); ?>[<?php echo $_back1->getMeasurementId(); ?>]" type="radio" value="<?php echo $_customtitle->getCustomTitleId(); ?>" /><?php echo $_customtitle->getTitle(); ?></label>
																			<?php } ?>
																		<?php } elseif($_back1->getFieldType() == 'text_area') { ?>
																			<label class="value">
																				<textarea id="<?php if($_back1->getIsRequired() == 1){ echo "required-entry"; } ?>" class="<?php if($_back1->getIsRequired() == 1){ echo "required-entry"; } ?>" name="<?php echo $measurementremember->getStitchingServiceId(); ?>[<?php echo $_back1->getMeasurementId(); ?>]" class="" cols="45" rows="3" style="resize: none;"><?php echo $measurementremember1->{'get' .$_back1->getMeasurementId()}(); ?></textarea>
																			</label>
																		<?php }elseif($_back1->getFieldType() == 'text_field') { ?>
																			<input id="<?php if($_back1->getIsRequired() == 1){ echo "required-entry"; } ?>" value="<?php echo $measurementremember1->{'get' .$_back1->getMeasurementId()}(); ?>" class="measurement_textfield <?php if($_back1->getIsRequired() == 1){ echo "required-entry"; } ?>" type="number" step="<?php echo $difference; ?>" name="<?php echo $measurementremember->getStitchingServiceId(); ?>[<?php echo $_back1->getMeasurementId(); ?>]" min="<?php echo $min; ?>" max="<?php echo $max; ?>" >
																			<span><span><?php echo '('.$min.' - '.$max.')'; ?></span><span><?php echo $_back1->getMeasurmentUnits(); ?></span></span>
																		<?php }elseif($_back1->getFieldType() == 'dropdown') {
																			if($_back1->getDropdownType() == 'standard') { ?>
																			 	<select id="<?php if($_back1->getIsRequired() == 1){ echo "required-entry"; } ?>" class="<?php if($_back1->getIsRequired() == 1){ echo "required-entry"; } ?>" name="<?php echo $measurementremember->getStitchingServiceId(); ?>[<?php echo $_back1->getMeasurementId(); ?>]">
																					<option></option>
																					<?php while($min <= $max) { ?>
																						<option <?php if(abs(($min-$b)/$b) < 0.00001) { echo 'selected'; } ?> ><?php echo $min; ?></option>
																						<?php $min += $difference;
																					} ?>
																				</select>
																				<span><span><?php echo '('.$originalmin.' - '.$max.')'; ?></span><span><?php echo $_back1->getMeasurmentUnits(); ?></span></span>
																			<?php }else if($_back1->getDropdownType() == 'custom'){ ?>
																			 	<select id="<?php if($_back1->getIsRequired() == 1){ echo "required-entry"; } ?>" class="<?php if($_back1->getIsRequired() == 1){ echo "required-entry"; } ?>" name="<?php echo $measurementremember->getStitchingServiceId(); ?>[<?php echo $_back1->getMeasurementId(); ?>]">
																					<option></option>
																					<?php foreach ($customtitles as $key => $_customtitle) { ?>
																						<option <?php if (abs(($_customtitle->getCustomTitleId()-$b)/$b) < 0.00001) { echo 'selected'; } ?> value="<?php echo $_customtitle->getCustomTitleId(); ?>"><?php echo $_customtitle->getTitle(); ?></option>
																					<?php } ?>
																				</select>
																			<?php } ?>
																		<?php } ?>
																	</label>
																	<?php if (!empty($_back1->getImage())) { ?>
																		<label class="image"><img width="250" height="280" title="Image" alt="Image" src="<?php echo Mage::getBaseUrl('media').$_back1->getImage(); ?>"></label>
																	<?php } ?>
																	<label class="content">
																		<h5>Ho to Measure</h5>
																		<h3><?php echo strtoupper($_back1->getTitle()); ?></h3>
																		<?php echo $_back1->getContent(); ?>
																	</label>
																</div>

															<?php } ?>
														</div>
													</div>
												<?php }
												if(strlen($sleeve['measurement_attr']) > 0) {
													// print_r($sleeve['measurement_attr']);
													$sleeve_attr = explode(',', $sleeve['measurement_attr']); ?>
													<div class="sleeve_measurements">
														<!-- <div class="title">Sleeve Measurements</div> -->
														<div class="sleeve_measurement_details">
															<?php foreach ($sleeve_attr as $key => $_sleeve) {
																$_sleeve1 = Mage::getModel('measurement/measurement')->load($_sleeve);
																$customtitles = Mage::getModel('measurement/customtitles')->getCollection()->addFieldToFilter('measurement_id',$_sleeve1->getMeasurementId());
																$min = $_sleeve1->getMinVal();
																$max = $_sleeve1->getMaxVal();
																if($measurementremember1->getMeasurmentUnits() == 'cm'){ 
																	$unit = 2.54;
																	$min = round( ($min*$unit), 2);
																	$min = 5 * round($min / 5, 2);
																	$max = round( ($max*$unit), 2);
																	$max = 5 * round($max / 5, 2);
																}
																$originalmin = $min;
																$b = $measurementremember1->{'get' .$_sleeve1->getMeasurementId()}();
																$difference = $_sleeve1->getDifference(); ?>
																<div class="m_attr"><label id="label" class="<?php if($_sleeve1->getIsRequired() == 1){ echo "required"; } ?>"><?php echo $_sleeve1->getTitle(); ?></label>
																	<label class="value">
																		<?php if($_sleeve1->getFieldType() == 'radio') { ?>
																			<?php foreach ($customtitles as $key => $_customtitle) { ?>
																				<label class="radio_button"><input id="<?php if($_sleeve1->getIsRequired() == 1){ echo "required-entry"; } ?>" class="<?php if($_sleeve1->getIsRequired() == 1){ echo "required-entry"; } ?>" <?php if(abs(($_customtitle->getCustomTitleId()-$b)/$b) < 0.00001) { echo 'checked'; } ?> name="<?php echo $measurementremember->getStitchingServiceId(); ?>[<?php echo $_sleeve1->getMeasurementId(); ?>]" type="radio" value="<?php echo $_customtitle->getCustomTitleId(); ?>" /><?php echo $_customtitle->getTitle(); ?></label>
																			<?php } ?>
																		<?php } elseif($_sleeve1->getFieldType() == 'text_area') { ?>
																			<label class="value">
																				<textarea id="<?php if($_sleeve1->getIsRequired() == 1){ echo "required-entry"; } ?>" class="<?php if($_sleeve1->getIsRequired() == 1){ echo "required-entry"; } ?>" name="<?php echo $measurementremember->getStitchingServiceId(); ?>[<?php echo $_sleeve1->getMeasurementId(); ?>]" cols="45" rows="3" style="resize: none;"><?php echo $measurementremember1->{'get' .$_sleeve1->getMeasurementId()}(); ?></textarea>
																			</label>
																		<?php }elseif($_sleeve1->getFieldType() == 'text_field') { ?>
																			<input id="<?php if($_sleeve1->getIsRequired() == 1){ echo "required-entry"; } ?>" value="<?php echo $measurementremember1->{'get' .$_sleeve1->getMeasurementId()}(); ?>" class="measurement_textfield <?php if($_sleeve1->getIsRequired() == 1){ echo "required-entry"; } ?>" type="number" step="<?php echo $difference; ?>" name="<?php echo $_sleeve1->getMeasurementId(); ?>" min="<?php echo $min; ?>" max="<?php echo $max; ?>" >
																			<span><span><?php echo '('.$min.' - '.$max.')'; ?></span><span><?php echo $_sleeve1->getMeasurmentUnits(); ?></span></span>
																		<?php }elseif($_sleeve1->getFieldType() == 'dropdown') {
																			if($_sleeve1->getDropdownType() == 'standard') { ?>
																			 	<select id="<?php if($_sleeve1->getIsRequired() == 1){ echo "required-entry"; } ?>" class="<?php if($_sleeve1->getIsRequired() == 1){ echo "required-entry"; } ?>" name="<?php echo $measurementremember->getStitchingServiceId(); ?>[<?php echo $_sleeve1->getMeasurementId(); ?>]">
																					<option></option>
																					<?php while($min <= $max) { ?>
																						<option <?php if(abs(($min-$b)/$b) < 0.00001) { echo 'selected'; } ?> ><?php echo $min; ?></option>
																						<?php $min += $difference;
																					} ?>
																				</select>
																				<span><span><?php echo '('.$originalmin.' - '.$max.')'; ?></span><span><?php echo $_sleeve1->getMeasurmentUnits(); ?></span></span>
																			 <?php }else if($_sleeve1->getDropdownType() == 'custom'){ ?>
																			 	<select id="<?php if($_sleeve1->getIsRequired() == 1){ echo "required-entry"; } ?>" class="<?php if($_sleeve1->getIsRequired() == 1){ echo "required-entry"; } ?>" name="<?php echo $measurementremember->getStitchingServiceId(); ?>[<?php echo $_sleeve1->getMeasurementId(); ?>]">
																					<option></option>
																					<?php foreach ($customtitles as $key => $_customtitle) { ?>
																						<option <?php if(abs(($_customtitle->getCustomTitleId()-$b)/$b) < 0.00001) { echo 'selected'; } ?> value="<?php echo $_customtitle->getCustomTitleId(); ?>"><?php echo $_customtitle->getTitle(); ?></option>
																					<?php } ?>
																				</select>
																			 <?php } ?>
																		<?php } ?>
																	</label>
																	<?php if (!empty($_sleeve1->getImage())) { ?>
																		<label class="image"><img width="250" height="280" title="Image" alt="Image" src="<?php echo Mage::getBaseUrl('media').$_sleeve1->getImage(); ?>"></label>
																	<?php } ?>
																	<label class="content">
																		<h5>Ho to Measure</h5>
																		<h3><?php echo strtoupper($_sleeve1->getTitle()); ?></h3>
																		<?php echo $_sleeve1->getContent(); ?>
																	</label>
																</div>

															<?php } ?>
														</div>
													</div>
												<?php }
												if(strlen($lehanga['measurement_attr']) > 0) {
													$lehanga_attr = explode(',', $lehanga['measurement_attr']); ?>
													<div class="lehanga_measurements">
														<!-- <div class="title">Lehanga Measurements</div> -->
														<div class="lehanga_measurement_details">
															<?php foreach ($lehanga_attr as $key => $_lehanga) {
																$_lehanga1 = Mage::getModel('measurement/measurement')->load($_lehanga);
																$customtitles = Mage::getModel('measurement/customtitles')->getCollection()->addFieldToFilter('measurement_id',$_lehanga1->getMeasurementId());
																$min = $_lehanga1->getMinVal();
																$max = $_lehanga1->getMaxVal();
																if($measurementremember1->getMeasurmentUnits() == 'cm'){ 
																	$unit = 2.54;
																	$min = round( ($min*$unit), 2);
																	$min = 5 * round($min / 5, 2);
																	$max = round( ($max*$unit), 2);
																	$max = 5 * round($max / 5, 2);
																}
																$originalmin = $min;
																$b = $measurementremember1->{'get' .$_lehanga1->getMeasurementId()}();
																$difference = $_lehanga1->getDifference(); ?>
																<div class="m_attr"><label id="label" class="<?php if($_lehanga1->getIsRequired() == 1){ echo "required"; } ?>"><?php echo $_lehanga1->getTitle(); ?></label>
																	<label class="value">
																		<?php if($_lehanga1->getFieldType() == 'radio') { ?>
																			<?php foreach ($customtitles as $key => $_customtitle) { ?>
																				<label class="radio_button"><input id="<?php if($_lehanga1->getIsRequired() == 1){ echo "required-entry"; } ?>" class="<?php if($_lehanga1->getIsRequired() == 1){ echo "required-entry"; } ?>" <?php if(abs(($_customtitle->getCustomTitleId()-$b)/$b) < 0.00001) { echo 'checked'; } ?> name="<?php echo $measurementremember->getStitchingServiceId(); ?>[<?php echo $_lehanga1->getMeasurementId(); ?>]" type="radio" value="<?php echo $_customtitle->getCustomTitleId(); ?>" /><?php echo $_customtitle->getTitle(); ?></label>
																			<?php } ?>
																		<?php } elseif($_lehanga1->getFieldType() == 'text_area') { ?>
																			<label class="value">
																				<textarea id="<?php if($_lehanga1->getIsRequired() == 1){ echo "required-entry"; } ?>" class="<?php if($_lehanga1->getIsRequired() == 1){ echo "required-entry"; } ?>" name="<?php echo $measurementremember->getStitchingServiceId(); ?>[<?php echo $_lehanga1->getMeasurementId(); ?>]" class="" cols="45" rows="3" style="resize: none;"><?php echo $measurementremember1->{'get' .$_lehanga1->getMeasurementId()}(); ?></textarea>
																			</label>
																		<?php }elseif($_lehanga1->getFieldType() == 'text_field') { ?>
																			<input id="<?php if($_lehanga1->getIsRequired() == 1){ echo "required-entry"; } ?>" value="<?php echo $measurementremember1->{'get' .$_lehanga1->getMeasurementId()}(); ?>" class="measurement_textfield <?php if($_lehanga1->getIsRequired() == 1){ echo "required-entry"; } ?>" type="number" step="<?php echo $difference; ?>" name="<?php echo $measurementremember->getStitchingServiceId(); ?>[<?php echo $_lehanga1->getMeasurementId(); ?>]" min="<?php echo $min; ?>" max="<?php echo $max; ?>" >
																			<span><span><?php echo '('.$min.' - '.$max.')'; ?></span><span><?php echo $_lehanga1->getMeasurmentUnits(); ?></span></span>
																		<?php }elseif($_lehanga1->getFieldType() == 'dropdown') {
																			if($_lehanga1->getDropdownType() == 'standard') { ?>
																			 	<select id="<?php if($_lehanga1->getIsRequired() == 1){ echo "required-entry"; } ?>" class="<?php if($_lehanga1->getIsRequired() == 1){ echo "required-entry"; } ?>" name="<?php echo $measurementremember->getStitchingServiceId(); ?>[<?php echo $_lehanga1->getMeasurementId(); ?>]">
																					<option></option>
																					<?php while($min <= $max) { ?>
																						<option <?php if(abs(($min-$b)/$b) < 0.00001) { echo 'selected'; } ?> ><?php echo $min; ?></option>
																						<?php $min += $difference;
																					} ?>
																				</select>
																				<span><span><?php echo '('.$originalmin.' - '.$max.')'; ?></span><span><?php echo $_lehanga1->getMeasurmentUnits(); ?></span></span>
																			<?php }else if($_lehanga1->getDropdownType() == 'custom'){ ?>
																			 	<select id="<?php if($_lehanga1->getIsRequired() == 1){ echo "required-entry"; } ?>" class="<?php if($_lehanga1->getIsRequired() == 1){ echo "required-entry"; } ?>" name="<?php echo $measurementremember->getStitchingServiceId(); ?>[<?php echo $_lehanga1->getMeasurementId(); ?>]">
																					<option></option>
																					<?php foreach ($customtitles as $key => $_customtitle) { ?>
																						<option <?php if (abs(($_customtitle->getCustomTitleId()-$b)/$b) < 0.00001) { echo 'selected'; } ?> value="<?php echo $_customtitle->getCustomTitleId(); ?>"><?php echo $_customtitle->getTitle(); ?></option>
																					<?php } ?>
																				</select>
																			<?php } ?>
																		<?php } ?>
																	</label>
																	<?php if (!empty($_lehanga1->getImage())) { ?>
																		<label class="image"><img width="250" height="280" title="Image" alt="Image" src="<?php echo Mage::getBaseUrl('media').$_lehanga1->getImage(); ?>"></label>
																	<?php } ?>
																	<label class="content">
																		<h5>Ho to Measure</h5>
																		<h3><?php echo strtoupper($_lehanga1->getTitle()); ?></h3>
																		<?php echo $_lehanga1->getContent(); ?>
																	</label>
																</div>

															<?php } ?>
														</div>
													</div>
												<?php }
												if(strlen($salwar['measurement_attr']) > 0) {
													$salwar_attr = explode(',', $salwar['measurement_attr']); ?>
													<div class="salwar_measurements">
														<!-- <div class="title">Salwar Measurements</div> -->
														<div class="salwar_measurement_details">
															<?php foreach ($salwar_attr as $key => $_salwar) {
																$_salwar1 = Mage::getModel('measurement/measurement')->load($_salwar);
																$customtitles = Mage::getModel('measurement/customtitles')->getCollection()->addFieldToFilter('measurement_id',$_salwar1->getMeasurementId());
																$min = $_salwar1->getMinVal();
																$max = $_salwar1->getMaxVal();
																if($measurementremember1->getMeasurmentUnits() == 'cm'){ 
																	$unit = 2.54;
																	$min = round( ($min*$unit), 2);
																	$min = 5 * round($min / 5, 2);
																	$max = round( ($max*$unit), 2);
																	$max = 5 * round($max / 5, 2);
																}
																$originalmin = $min;
																$b = $measurementremember1->{'get' .$_salwar1->getMeasurementId()}();
																$difference = $_salwar1->getDifference(); ?>
																<div class="m_attr"><label id="label" class="<?php if($_salwar1->getIsRequired() == 1){ echo "required"; } ?>"><?php echo $_salwar1->getTitle(); ?></label>
																	<label class="value">
																		<?php if($_salwar1->getFieldType() == 'radio') { ?>
																			<?php foreach ($customtitles as $key => $_customtitle) { ?>
																				<label class="radio_button"><input id="<?php if($_salwar1->getIsRequired() == 1){ echo "required-entry"; } ?>" class="<?php if($_salwar1->getIsRequired() == 1){ echo "required-entry"; } ?>" <?php if(abs(($_customtitle->getCustomTitleId()-$b)/$b) < 0.00001) { echo 'checked'; } ?> name="<?php echo $measurementremember->getStitchingServiceId(); ?>[<?php echo $_salwar1->getMeasurementId(); ?>]" type="radio" value="<?php echo $_customtitle->getCustomTitleId(); ?>" /><?php echo $_customtitle->getTitle(); ?></label>
																			<?php } ?>
																		<?php } elseif($_salwar1->getFieldType() == 'text_area') { ?>
																			<label class="value">
																				<textarea id="<?php if($_salwar1->getIsRequired() == 1){ echo "required-entry"; } ?>" class="<?php if($_salwar1->getIsRequired() == 1){ echo "required-entry"; } ?>" name="<?php echo $measurementremember->getStitchingServiceId(); ?>[<?php echo $_salwar1->getMeasurementId(); ?>]" class="" cols="45" rows="3" style="resize: none;"><?php echo $measurementremember1->{'get' .$_salwar1->getMeasurementId()}(); ?></textarea>
																			</label>
																		<?php }elseif($_salwar1->getFieldType() == 'text_field') { ?>
																			<input id="<?php if($_salwar1->getIsRequired() == 1){ echo "required-entry"; } ?>" value="<?php echo $measurementremember1->{'get' .$_salwar1->getMeasurementId()}(); ?>" class="measurement_textfield <?php if($_salwar1->getIsRequired() == 1){ echo "required-entry"; } ?>" type="number" step="<?php echo $difference; ?>" name="<?php echo $measurementremember->getStitchingServiceId(); ?>[<?php echo $_salwar1->getMeasurementId(); ?>]" min="<?php echo $min; ?>" max="<?php echo $max; ?>" >
																			<span><span><?php echo '('.$min.' - '.$max.')'; ?></span><span><?php echo $_salwar1->getMeasurmentUnits(); ?></span></span>
																		<?php }elseif($_salwar1->getFieldType() == 'dropdown') {
																			if($_salwar1->getDropdownType() == 'standard') { ?>
																			 	<select id="<?php if($_salwar1->getIsRequired() == 1){ echo "required-entry"; } ?>" class="<?php if($_salwar1->getIsRequired() == 1){ echo "required-entry"; } ?>" name="<?php echo $measurementremember->getStitchingServiceId(); ?>[<?php echo $_salwar1->getMeasurementId(); ?>]">
																					<option></option>
																					<?php while($min <= $max) { ?>
																						<option <?php if(abs(($min-$b)/$b) < 0.00001) { echo 'selected'; } ?> ><?php echo $min; ?></option>
																						<?php $min += $difference;
																					} ?>
																				</select>
																				<span><span><?php echo '('.$originalmin.' - '.$max.')'; ?></span><span><?php echo $_salwar1->getMeasurmentUnits(); ?></span></span>
																			<?php }else if($_salwar1->getDropdownType() == 'custom'){ ?>
																			 	<select id="<?php if($_salwar1->getIsRequired() == 1){ echo "required-entry"; } ?>" class="<?php if($_salwar1->getIsRequired() == 1){ echo "required-entry"; } ?>" name="<?php echo $measurementremember->getStitchingServiceId(); ?>[<?php echo $_salwar1->getMeasurementId(); ?>]">
																					<option></option>
																					<?php foreach ($customtitles as $key => $_customtitle) { ?>
																						<option <?php if (abs(($_customtitle->getCustomTitleId()-$b)/$b) < 0.00001) { echo 'selected'; } ?> value="<?php echo $_customtitle->getCustomTitleId(); ?>"><?php echo $_customtitle->getTitle(); ?></option>
																					<?php } ?>
																				</select>
																			<?php } ?>
																		<?php } ?>
																	</label>
																	<?php if (!empty($_salwar1->getImage())) { ?>
																		<label class="image"><img width="250" height="280" title="Image" alt="Image" src="<?php echo Mage::getBaseUrl('media').$_salwar1->getImage(); ?>"></label>
																	<?php } ?>
																	<label class="content">
																		<h5>Ho to Measure</h5>
																		<h3><?php echo strtoupper($_salwar1->getTitle()); ?></h3>
																		<?php echo $_salwar1->getContent(); ?>
																	</label>
																</div>

															<?php } ?>
														</div>
													</div>
												<?php }
												if(strlen($tassel['measurement_attr']) > 0) {
													$tassel_attr = explode(',', $tassel['measurement_attr']); ?>
													<div class="tassel_measurements">
														<!-- <div class="title">tassel Measurements</div> -->
														<div class="tassel_measurement_details">
															<?php foreach ($tassel_attr as $key => $_tassel) {
																$_tassel1 = Mage::getModel('measurement/measurement')->load($_tassel);
																$customtitles = Mage::getModel('measurement/customtitles')->getCollection()->addFieldToFilter('measurement_id',$_tassel1->getMeasurementId());
																$min = $_tassel1->getMinVal();
																$max = $_tassel1->getMaxVal();
																if($measurementremember1->getMeasurmentUnits() == 'cm'){ 
																	$unit = 2.54;
																	$min = round( ($min*$unit), 2);
																	$min = 5 * round($min / 5, 2);
																	$max = round( ($max*$unit), 2);
																	$max = 5 * round($max / 5, 2);
																}
																$originalmin = $min;
																$b = $measurementremember1->{'get' .$_tassel1->getMeasurementId()}();
																$difference = $_tassel1->getDifference(); ?>
																<div class="m_attr"><label id="label" class="<?php if($_tassel1->getIsRequired() == 1){ echo "required"; } ?>"><?php echo $_tassel1->getTitle(); ?></label>
																	<label class="value">
																		<?php if($_tassel1->getFieldType() == 'radio') { ?>
																			<?php foreach ($customtitles as $key => $_customtitle) { ?>
																				<label class="radio_button"><input id="<?php if($_tassel1->getIsRequired() == 1){ echo "required-entry"; } ?>" class="<?php if($_tassel1->getIsRequired() == 1){ echo "required-entry"; } ?>" <?php if(abs(($_customtitle->getCustomTitleId()-$b)/$b) < 0.00001) { echo 'checked'; } ?> name="<?php echo $measurementremember->getStitchingServiceId(); ?>[<?php echo $_tassel1->getMeasurementId(); ?>]" type="radio" value="<?php echo $_customtitle->getCustomTitleId(); ?>" /><?php echo $_customtitle->getTitle(); ?></label>
																			<?php } ?>
																		<?php } elseif($_tassel1->getFieldType() == 'text_area') { ?>
																			<label class="value">
																				<textarea id="<?php if($_tassel1->getIsRequired() == 1){ echo "required-entry"; } ?>" class="<?php if($_tassel1->getIsRequired() == 1){ echo "required-entry"; } ?>" name="<?php echo $measurementremember->getStitchingServiceId(); ?>[<?php echo $_tassel1->getMeasurementId(); ?>]" class="" cols="45" rows="3" style="resize: none;"><?php echo $measurementremember1->{'get' .$_tassel1->getMeasurementId()}(); ?></textarea>
																			</label>
																		<?php }elseif($_tassel1->getFieldType() == 'text_field') { ?>
																			<input id="<?php if($_tassel1->getIsRequired() == 1){ echo "required-entry"; } ?>" value="<?php echo $measurementremember1->{'get' .$_tassel1->getMeasurementId()}(); ?>" class="measurement_textfield <?php if($_tassel1->getIsRequired() == 1){ echo "required-entry"; } ?>" type="number" step="<?php echo $difference; ?>" name="<?php echo $measurementremember->getStitchingServiceId(); ?>[<?php echo $_tassel1->getMeasurementId(); ?>]" min="<?php echo $min; ?>" max="<?php echo $max; ?>" >
																			<span><span><?php echo '('.$min.' - '.$max.')'; ?></span><span><?php echo $_tassel1->getMeasurmentUnits(); ?></span></span>
																		<?php }elseif($_tassel1->getFieldType() == 'dropdown') {
																			if($_tassel1->getDropdownType() == 'standard') { ?>
																			 	<select id="<?php if($_tassel1->getIsRequired() == 1){ echo "required-entry"; } ?>" class="<?php if($_tassel1->getIsRequired() == 1){ echo "required-entry"; } ?>" name="<?php echo $measurementremember->getStitchingServiceId(); ?>[<?php echo $_tassel1->getMeasurementId(); ?>]">
																					<option></option>
																					<?php while($min <= $max) { ?>
																						<option <?php if(abs(($min-$b)/$b) < 0.00001) { echo 'selected'; } ?> ><?php echo $min; ?></option>
																						<?php $min += $difference;
																					} ?>
																				</select>
																				<span><span><?php echo '('.$originalmin.' - '.$max.')'; ?></span><span><?php echo $_tassel1->getMeasurmentUnits(); ?></span></span>
																			<?php }else if($_tassel1->getDropdownType() == 'custom'){ ?>
																			 	<select id="<?php if($_tassel1->getIsRequired() == 1){ echo "required-entry"; } ?>" class="<?php if($_tassel1->getIsRequired() == 1){ echo "required-entry"; } ?>" name="<?php echo $measurementremember->getStitchingServiceId(); ?>[<?php echo $_tassel1->getMeasurementId(); ?>]">
																					<option></option>
																					<?php foreach ($customtitles as $key => $_customtitle) { ?>
																						<option <?php if (abs(($_customtitle->getCustomTitleId()-$b)/$b) < 0.00001) { echo 'selected'; } ?> value="<?php echo $_customtitle->getCustomTitleId(); ?>"><?php echo $_customtitle->getTitle(); ?></option>
																					<?php } ?>
																				</select>
																			<?php } ?>
																		<?php } ?>
																	</label>
																	<?php if (!empty($_tassel1->getImage())) { ?>
																		<label class="image"><img width="250" height="280" title="Image" alt="Image" src="<?php echo Mage::getBaseUrl('media').$_tassel1->getImage(); ?>"></label>
																	<?php } ?>
																	<label class="content">
																		<h5>Ho to Measure</h5>
																		<h3><?php echo strtoupper($_tassel1->getTitle()); ?></h3>
																		<?php echo $_tassel1->getContent(); ?>
																	</label>
																</div>

															<?php } ?>
														</div>
													</div>
												<?php }
											?>
										</div>
									</div>
									<div class="goto_nextstep" style="display:block;"><input type="button" class="goto_reviewstep" value="Next Step" /></div>
								</div>
							</div>
						</div>
						<div class="measure_detail" id="review">
							<div class="label_title"><label>3. Review</label></div>
							<div id="measurement_step" class="measurement_review">
								<?php echo '<div class=review_selected_style>
									<ul class=ul_review_selected_style>';
										if($measurementremember1->getFrontId() > 0) {
											$front = Mage::getModel('styles/styles')->getCollection()->addFieldToSelect('*')->addFieldToFilter('style_id',$measurementremember1->getFrontId())->addFieldToFilter('status',1)->getFirstItem(); ?>
											<li class=li_review_selected_style>
												<div class="selected_style_image"><img width=200 height=300 alt="<?php echo $front->getTitle(); ?>" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$front->getImage(); ?>"></div>
												<?php if ($measurementremember1->getMeasurementType() == 'custom') { ?>
													<div class="selected_style_measurements">
														<?php $front_smeasurements = explode(',', $front->getMeasurementAttr());
														foreach ($front_smeasurements as $value) {
															$measurement = Mage::getModel('measurement/measurement')->getCollection()->addFieldToSelect('*')->addFieldToFilter('measurement_id',$value)->addFieldToFilter('status',1)->getFirstItem(); ?>
															<div class="review_your_measurements1">
																<label class="label"><b><?php echo $measurement->getTitle().' : '; ?></b></label>
																<?php if($measurement->getDropdownType() == 'custom'){
																	$customtitles = Mage::getModel('measurement/customtitles')->load($measurementremember1->{'get' . $value}());
																	$final_value = $customtitles->getTitle();
																}else{
																	if($measurement->getFieldType() == 'text_area'){
																		$final_value = $measurementremember1->{'get' . $value}();
																	}else{
																		$final_value = $measurementremember1->{'get' . $value}().' '.$measurementremember1->getMeasurmentUnits();
																	}
																} ?>
																<label class="value"><?php echo $final_value; ?></label>
															</div>
														<?php } ?>
													</div>
												<?php } ?>
											</li>
										<?php }
										if($measurementremember1->getBackId() > 0) {
											$back = Mage::getModel('back/back')->getCollection()->addFieldToSelect('*')->addFieldToFilter('back_id',$measurementremember1->getBackId())->addFieldToFilter('status',1)->getFirstItem(); ?>
											<li class=li_review_selected_style>
												<div class="selected_style_image"><img width=200 height=300 alt="<?php echo $back->getTitle(); ?>" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$back->getImage(); ?>"></div>
												<?php if ($measurementremember1->getMeasurementType() == 'custom') { ?>
													<div class="selected_style_measurements">
														<?php $back_smeasurements = explode(',', $back->getMeasurementAttr());
														foreach ($back_smeasurements as $value) {
															$measurement = Mage::getModel('measurement/measurement')->getCollection()->addFieldToSelect('*')->addFieldToFilter('measurement_id',$value)->addFieldToFilter('status',1)->getFirstItem(); ?>
															<div class="review_your_measurements1">
																<label class="label"><b><?php echo $measurement->getTitle().' : '; ?></b></label>
																<?php if($measurement->getDropdownType() == 'custom'){
																	$customtitles = Mage::getModel('measurement/customtitles')->load($measurementremember1->{'get' . $value}());
																	$final_value = $customtitles->getTitle();
																}else{
																	if($measurement->getFieldType() == 'text_area'){
																		$final_value = $measurementremember1->{'get' . $value}();
																	}else{
																		$final_value = $measurementremember1->{'get' . $value}().' '.$measurementremember1->getMeasurmentUnits();
																	}
																} ?>
																<label class="value"><?php echo $final_value; ?></label>
															</div>
														<?php } ?>
													</div>
												<?php } ?>
											</li>
										<?php }
										if($measurementremember1->getSleeveId() > 0) {
											$sleeve = Mage::getModel('sleeves/sleeves')->getCollection()->addFieldToSelect('*')->addFieldToFilter('sleeves_id',$measurementremember1->getSleeveId())->addFieldToFilter('status',1)->getFirstItem(); ?>
											<li class=li_review_selected_style>
												<div class="selected_style_image"><img width=200 height=300 alt="<?php echo $sleeve->getTitle(); ?>" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$sleeve->getImage(); ?>"></div>
												<?php if ($measurementremember1->getMeasurementType() == 'custom') { ?>
													<div class="selected_style_measurements">
														<?php $sleeve_smeasurements = explode(',', $sleeve->getMeasurementAttr());
														foreach ($sleeve_smeasurements as $value) {
															$measurement = Mage::getModel('measurement/measurement')->getCollection()->addFieldToSelect('*')->addFieldToFilter('measurement_id',$value)->addFieldToFilter('status',1)->getFirstItem(); ?>
															<div class="review_your_measurements1">
																<label class="label"><b><?php echo $measurement->getTitle().' : '; ?></b></label>
																<?php if($measurement->getDropdownType() == 'custom'){
																	$customtitles = Mage::getModel('measurement/customtitles')->load($measurementremember1->{'get' . $value}());
																	$final_value = $customtitles->getTitle();
																}else{
																	if($measurement->getFieldType() == 'text_area'){
																		$final_value = $measurementremember1->{'get' . $value}();
																	}else{
																		$final_value = $measurementremember1->{'get' . $value}().' '.$measurementremember1->getMeasurmentUnits();
																	}
																} ?>
																<label class="value"><?php echo $final_value; ?></label>
															</div>
														<?php } ?>
													</div>
												<?php } ?>
											</li>
										<?php }
										if ($measurementremember1->getLehangaId() > 0) {
											$lehanga = Mage::getModel('lehanga/lehanga')->getCollection()->addFieldToSelect('*')->addFieldToFilter('lehanga_id',$measurementremember1->getLehangaId())->addFieldToFilter('status',1)->getFirstItem(); ?>
											<li class=li_review_selected_style>
												<div class="selected_style_image"><img width=200 height=300 alt="<?php echo $lehanga->getTitle(); ?>" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$lehanga->getImage(); ?>"></div>
												<?php if ($measurementremember1->getMeasurementType() == 'custom') { ?>
													<div class="selected_style_measurements">
														<?php $lehanga_smeasurements = explode(',', $lehanga->getMeasurementAttr());
														foreach ($lehanga_smeasurements as $value) {
															$measurement = Mage::getModel('measurement/measurement')->getCollection()->addFieldToSelect('*')->addFieldToFilter('measurement_id',$value)->addFieldToFilter('status',1)->getFirstItem(); ?>
															<div class="review_your_measurements1">
																<label class="label"><b><?php echo $measurement->getTitle().' : '; ?></b></label>
																<?php if($measurement->getDropdownType() == 'custom'){
																	$customtitles = Mage::getModel('measurement/customtitles')->load($measurementremember1->{'get' . $value}());
																	$final_value = $customtitles->getTitle();
																}else{
																	if($measurement->getFieldType() == 'text_area'){
																		$final_value = $measurementremember1->{'get' . $value}();
																	}else{
																		$final_value = $measurementremember1->{'get' . $value}().' '.$measurementremember1->getMeasurmentUnits();
																	}
																} ?>
																<label class="value"><?php echo $final_value; ?></label>
															</div>
														<?php } ?>
													</div>
												<?php } ?>
											</li>
										<?php }
										if ($measurementremember1->getSalwarId() > 0) {
											$salwar = Mage::getModel('salwar/salwar')->getCollection()->addFieldToSelect('*')->addFieldToFilter('salwar_id',$measurementremember1->getSalwarId())->addFieldToFilter('status',1)->getFirstItem(); ?>
											<li class=li_review_selected_style>
												<div class="selected_style_image"><img width=200 height=300 alt="<?php echo $salwar->getTitle(); ?>" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$salwar->getImage(); ?>"></div>
												<?php if ($measurementremember1->getMeasurementType() == 'custom') { ?>
													<div class="selected_style_measurements">
														<?php $salwar_smeasurements = explode(',', $salwar->getMeasurementAttr());
														foreach ($salwar_smeasurements as $value) {
															$measurement = Mage::getModel('measurement/measurement')->getCollection()->addFieldToSelect('*')->addFieldToFilter('measurement_id',$value)->addFieldToFilter('status',1)->getFirstItem(); ?>
															<div class="review_your_measurements1">
																<label class="label"><b><?php echo $measurement->getTitle().' : '; ?></b></label>
																<?php if($measurement->getDropdownType() == 'custom'){
																	$customtitles = Mage::getModel('measurement/customtitles')->load($measurementremember1->{'get' . $value}());
																	$final_value = $customtitles->getTitle();
																}else{
																	if($measurement->getFieldType() == 'text_area'){
																		$final_value = $measurementremember1->{'get' . $value}();
																	}else{
																		$final_value = $measurementremember1->{'get' . $value}().' '.$measurementremember1->getMeasurmentUnits();
																	}
																} ?>
																<label class="value"><?php echo $final_value; ?></label>
															</div>
														<?php } ?>
													</div>
												<?php } ?>
											</li>
										<?php }
										if ($measurementremember1->getTasselId() > 0) {
											$tassel = Mage::getModel('tassel/tassel')->getCollection()->addFieldToSelect('*')->addFieldToFilter('tassel_id',$measurementremember1->getTasselId())->addFieldToFilter('status',1)->getFirstItem(); ?>
											<li class=li_review_selected_style>
												<div class="selected_style_image"><img width=200 height=300 alt="<?php echo $tassel->getTitle(); ?>" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$tassel->getImage(); ?>"></div>
												<?php if ($measurementremember1->getMeasurementType() == 'custom') { ?>
													<div class="selected_style_measurements">
														<?php $tassel_smeasurements = explode(',', $tassel->getMeasurementAttr());
														foreach ($tassel_smeasurements as $value) {
															$measurement = Mage::getModel('measurement/measurement')->getCollection()->addFieldToSelect('*')->addFieldToFilter('measurement_id',$value)->addFieldToFilter('status',1)->getFirstItem(); ?>
															<div class="review_your_measurements1">
																<label class="label"><b><?php echo $measurement->getTitle().' : '; ?></b></label>
																<?php if($measurement->getDropdownType() == 'custom'){
																	$customtitles = Mage::getModel('measurement/customtitles')->load($measurementremember1->{'get' . $value}());
																	$final_value = $customtitles->getTitle();
																}else{
																	if($measurement->getFieldType() == 'text_area'){
																		$final_value = $measurementremember1->{'get' . $value}();
																	}else{
																		$final_value = $measurementremember1->{'get' . $value}().' '.$measurementremember1->getMeasurmentUnits();
																	}
																} ?>
																<label class="value"><?php echo $final_value; ?></label>
															</div>
														<?php } ?>
													</div>
												<?php } ?>
											</li>
										<?php } ?>
									</ul>
								</div>
								<div class="goto_nextstep" style="display: block;"><button id="submit_measurements" class="take_measurement" type="submit">Edit & Submit</button></div>
								</div>
						</div>
					</div>
	 			</div>
	 		</form>
	 	<?php }
	} else if( isset($_REQUEST['product_id']) && isset($_REQUEST['stitching_type']) ){ ?>
		<form action="<?php echo Mage::getBaseUrl(); ?>measurementremember/measurement/save" method="post" id="measurement11">
			<div class="product_measurement">
				<?php $_product = Mage::getModel('catalog/product')->load($_REQUEST['product_id']);
				$stitching_services = explode(',', $_product->getA27());
				$attr = Mage::getModel('catalog/product')->getResource()->getAttribute("a27");
				if(Mage::getSingleton('customer/session')->isLoggedIn()) {
					$measurementremember = Mage::getModel('measurementremember/measurementremember')->getCollection()->addFieldToFilter('c_id',Mage::getSingleton('customer/session')->getId())->addFieldToFilter('product_id',$_product->getId())->addFieldToFilter('stitching_type',$_REQUEST['stitching_type'])->addFieldToFilter('quote_id',Mage::getSingleton('checkout/session')->getQuoteId());
				} else{
					echo 'Please Login to your Account to Measurements';
				}
				$count = 0;
				foreach ($stitching_services as $key => $value) {
					$stitching_name = $attr->getSource()->getOptionText($value);
					$frontcollection = Mage::getModel('styles/styles')->getCollection()->addFieldToFilter('stitching_service_id',$value)->addFieldToFilter('stitching_service', array('like' => '%'.$_REQUEST['stitching_type'].'%'))->addFieldToFilter('status',1);
					$salwarcollection = Mage::getModel('salwar/salwar')->getCollection()->addFieldToFilter('stitching_service_id',$value)->addFieldToFilter('stitching_service', array('like' => '%'.$_REQUEST['stitching_type'].'%'))->addFieldToFilter('status',1);
					$lehangacollection = Mage::getModel('lehanga/lehanga')->getCollection()->addFieldToFilter('stitching_service_id',$value)->addFieldToFilter('stitching_service', array('like' => '%'.$_REQUEST['stitching_type'].'%'))->addFieldToFilter('status',1);
					if (sizeof($frontcollection) > 0 && sizeof($measurementremember) == 0) { ?>
						<div class="tabed">
							<a class="selectedTab" href="javascript:;"><?php echo $stitching_name; ?></a>
						</div>
							<input type="hidden" name="service" class="service" value="<?php echo $value; ?>" />
							<input type="hidden" name="customer_id" class="customer_id" value="<?php echo Mage::getSingleton('customer/session')->getId(); ?>" />
							<input type="hidden" name="stitching_type" class="stitching_type" value="<?php echo $_REQUEST['stitching_type']; ?>" />
							<?php if(isset($_REQUEST['order_id'])) { ?>
								<input type="hidden" id="order_id" name="order_id" class="order_id" value="<?php echo $_REQUEST['order_id']; ?>" />
							<?php } ?>
							<input type="hidden" name="product_id" class="product_id" value="<?php echo $_product->getId(); ?>" />
							<?php $measurementremember = Mage::getModel('measurementremember/measurementremember')->getCollection()->addFieldToFilter('c_id',Mage::getSingleton('customer/session')->getId())->addFieldToFilter('stitching_type', $_REQUEST['stitching_type'])->addFieldToFilter('account',1);
							echo '<div class="existing_measurements">
									<select class="existing_measurements" name="existing_measurements">';
										echo '<option>--- Please Select/Add New Measurement ---</option>';
											foreach ($measurementremember as $key => $_remember){
												echo '<option value="'.$_remember->getMeasurementrememberId().'">'.$_remember->getTitle().'</option>';
											}
										echo '<option value="new">Add New Measurements</option>';
									echo '</select>
							</div>'; ?>
							<div class="measure_details"></div>
					<?php $count++; }else if (sizeof($salwarcollection) > 0 && sizeof($measurementremember) == 0) { ?>
						<div class="tabed">
							<a class="selectedTab" href="javascript:;"><?php echo $stitching_name; ?></a>
						</div>
							<input type="hidden" name="service" class="service" value="<?php echo $value; ?>" />
							<input type="hidden" name="customer_id" class="customer_id" value="<?php echo Mage::getSingleton('customer/session')->getId(); ?>" />
							<input type="hidden" name="stitching_type" class="stitching_type" value="<?php echo $_REQUEST['stitching_type']; ?>" />
							<?php if (isset($_REQUEST['order_id'])) { ?>
								<input type="hidden" name="order_id" class="order_id" value="<?php echo $_REQUEST['order_id']; ?>" />
							<?php } ?>
							<input type="hidden" name="product_id" class="product_id" value="<?php echo $_product->getId(); ?>" />
							<?php $measurementremember = Mage::getModel('measurementremember/measurementremember')->getCollection()->addFieldToFilter('c_id',Mage::getSingleton('customer/session')->getId())->addFieldToFilter('stitching_type', $_REQUEST['stitching_type'])->addFieldToFilter('account',1);
							echo '<div class="existing_measurements">
									<select class="existing_measurements" name="existing_measurements">';
										echo '<option>--- Please Select/Add New Measurement ---</option>';
											foreach ($measurementremember as $key => $_remember){
												echo '<option value="'.$_remember->getMeasurementrememberId().'">'.$_remember->getTitle().'</option>';
											}
										echo '<option value="new">Add New Measurements</option>';
									echo '</select>
							</div>'; ?>
							<div class="measure_details"></div>
					<?php $count++; } else if (sizeof($lehangacollection) > 0 && sizeof($measurementremember) == 0) { ?>
						<div class="tabed">
							<a class="selectedTab" href="javascript:;"><?php echo $stitching_name; ?></a>
						</div>
							<input type="hidden" name="service" class="service" value="<?php echo $value; ?>" />
							<input type="hidden" name="customer_id" class="customer_id" value="<?php echo Mage::getSingleton('customer/session')->getId(); ?>" />
							<input type="hidden" name="stitching_type" class="stitching_type" value="<?php echo $_REQUEST['stitching_type']; ?>" />
							<?php if (isset($_REQUEST['order_id'])) { ?>
								<input type="hidden" name="order_id" class="order_id" value="<?php echo $_REQUEST['order_id']; ?>" />
							<?php } ?>
							<input type="hidden" name="product_id" class="product_id" value="<?php echo $_product->getId(); ?>" />
							<?php $measurementremember = Mage::getModel('measurementremember/measurementremember')->getCollection()->addFieldToFilter('c_id',Mage::getSingleton('customer/session')->getId())->addFieldToFilter('stitching_type', $_REQUEST['stitching_type'])->addFieldToFilter('account',1);
							echo '<div class="existing_measurements">
									<select class="existing_measurements" name="existing_measurements">';
										echo '<option>--- Please Select/Add New Measurement ---</option>';
											foreach ($measurementremember as $key => $_remember){
												echo '<option value="'.$_remember->getMeasurementrememberId().'">'.$_remember->getTitle().'</option>';
											}
										echo '<option value="new">Add New Measurements</option>';
									echo '</select>
							</div>'; ?>
							<div class="measure_details"></div>
					<?php $count++; } ?>
				<?php if ($count > 0) { break; }
				} ?>
				<?php if (sizeof($stitching_services) == $count) {
					echo 'All Measurements are already submitted for this product <br>';
				} ?>
			</div>
		</form>
		<script type="text/javascript">
		        var dataForm = new VarienForm('measurement11', true);
	    </script>
	<?php } ?>
	<script type="text/javascript">
	    var jQuery = jQuery.noConflict();
	    jQuery(function(){
	    	jQuery("#item_style").flexisel();
	    	jQuery("#item_style1").flexisel();
	    	jQuery("#item_style2").flexisel();
	    	jQuery("#item_style3").flexisel();
	    	jQuery("#item_style4").flexisel();
	    	jQuery("#item_style5").flexisel();

	    	var front_id = parseInt(jQuery('#front_id').attr('data'));
	    	var back_id = parseInt(jQuery('#back_id').attr('data'));
	    	var sleeve_id = parseInt(jQuery('#sleeve_id').attr('data'));
	    	var lehanga_id = parseInt(jQuery('#lehanga_id').attr('data'));
	    	var salwar_id = parseInt(jQuery('#salwar_id').attr('data'));
	    	var tassel_id = parseInt(jQuery('#tassel_id').attr('data'));
	    	if (front_id > 0) {
	    		jQuery("input.front_id").each(function() {
					if( front_id == parseInt(jQuery(this).val())) {
						jQuery(this).prop("checked", true);
					}
				});
	    	}
	    	if (back_id > 0) {
	    		jQuery("input.back_id").each(function() {
					if( back_id == parseInt(jQuery(this).val())) {
						jQuery(this).prop("checked", true);
					}
				});
	    	}
	    	if (sleeve_id > 0) {
	    		jQuery("input.sleeve_id").each(function() {
					if( sleeve_id == parseInt(jQuery(this).val())) {
						jQuery(this).prop("checked", true);
					}
				});
	    	}
	    	if (lehanga_id > 0) {
	    		jQuery("input.lehanga_id").each(function() {
					if( lehanga_id == parseInt(jQuery(this).val())) {
						jQuery(this).prop("checked", true);
					}
				});
	    	}
	    	if (salwar_id > 0) {
	    		jQuery("input.salwar_id").each(function() {
					if( salwar_id == parseInt(jQuery(this).val())) {
						jQuery(this).prop("checked", true);
					}
				});
	    	}
	    	if (tassel_id > 0) {
	    		jQuery("input.tassel_id").each(function() {
					if( tassel_id == parseInt(jQuery(this).val())) {
						jQuery(this).prop("checked", true);
					}
				});
	    	}
	    	jQuery('.value input').focus( function() {
				jQuery(jQuery(this).parent().parent()).find('label.content:first').show();
				jQuery(jQuery(this).parent().parent()).find('label.image:first').show();
			});
			jQuery('.value input').blur( function() {
				jQuery(jQuery(this).parent().parent()).find('label.content:first').hide();
				jQuery(jQuery(this).parent().parent()).find('label.image:first').hide();
			});
			jQuery('.value select').focus( function() {
				jQuery(jQuery(this).parent().parent()).find('label.content:first').show();
				jQuery(jQuery(this).parent().parent()).find('label.image:first').show();
			});
			jQuery('.value select').blur( function() {
				jQuery(jQuery(this).parent().parent()).find('label.content:first').hide();
				jQuery(jQuery(this).parent().parent()).find('label.image:first').hide();
			});
			jQuery(".value input").hover(
				function(){
					jQuery(jQuery(this).parent().parent()).find('label.content:first').toggle();
					jQuery(jQuery(this).parent().parent()).find('label.image:first').toggle();
				},
				function(){
					jQuery(jQuery(this).parent().parent()).find('label.content:first').toggle();
					jQuery(jQuery(this).parent().parent()).find('label.image:first').toggle();
				}
			);
			jQuery(".value select").hover(
				function(){
					jQuery(jQuery(this).parent().parent()).find('label.content:first').toggle();
					jQuery(jQuery(this).parent().parent()).find('label.image:first').toggle();
				},
				function(){
					jQuery(jQuery(this).parent().parent()).find('label.content:first').toggle();
					jQuery(jQuery(this).parent().parent()).find('label.image:first').toggle();
				}
			);



	    	jQuery('.front_id').click(function() {
	            var data1 = "&front_id="+this.value+"&service="+jQuery('.service').val();
	            var url1 = '<?php echo Mage::getBaseUrl(); ?>measurement/measure/backstyles';
				try {
					jQuery.ajax({
						url: url1,
						type : 'post',
						data: data1,
						success: function(response){
							if (response) {
								var string = response;
							} else{
								var string = '<div class="back"><div class="label_title1"><label>Back Styles</label></div><div class="back_style_details"><p>Currently the Back Styles are Unavailable for this product</p></div></div>';
							}
							jQuery('.back').replaceWith(string);
							jQuery('.sleeve').replaceWith('<div class="sleeve"><div class="label_title1"><label>Sleeve Styles</label></div><div class="sleeve_style_details"><p>Please Select Back Style</p></div></div>');
						}
					});
				} catch(e){ }
	        });
	        jQuery('.back_id').click(function() {
				var front_id = 0;
		    	jQuery(".back_id").each(function() {
					if( jQuery(this).prop("checked")== true) {
						front_id = jQuery(this).attr("value");
					}
				});
		        var data1 = "&back_id="+this.value+"&front_id="+front_id+"&service="+jQuery('.service').val();
	            var url1 = '<?php echo Mage::getBaseUrl(); ?>measurement/measure/sleevestyles';
				try {
					jQuery.ajax({
						url: url1,
						type : 'post',
						data: data1,
						success: function(response){
							if (response) {
								var string = response;
							} else{
								var string = '<div class="sleeve"><div class="label_title1"><label>Sleeve Styles</label></div><div class="sleeve_style_details"><p>Currently the Sleeve Styles are Unavailable for this product</p></div></div>';
							}
							jQuery('.sleeve').replaceWith(string);
						}
					});
				} catch(e){ }
	        });
	        jQuery('.take_measurement').click(function() {
	        	if (jQuery(this).parents('.measure_detail').attr('id') == 'style_fit') {
	        		var front_id = 0;
					var back_id = 0;
					var sleeve_id = 0;
					var salwar_id = 0;
					var lehanga_id = 0;
					var tassel_id = 0;
			    	jQuery(".front_id").each(function() {
						if( jQuery(this).prop("checked")== true) {
							front_id = jQuery(this).attr("value");
						}
					});
			    	jQuery(".back_id").each(function() {
						if( jQuery(this).prop("checked")== true) {
							back_id = jQuery(this).attr("value");
						}
					});
			    	jQuery(".sleeve_id").each(function() {
						if( jQuery(this).prop("checked")== true) {
							sleeve_id = jQuery(this).attr("value");
						}
					});
					jQuery(".lehanga_id").each(function() {
						if( jQuery(this).prop("checked")== true) {
							lehanga_id = jQuery(this).attr("value");
						}
					});
					jQuery(".salwar_id").each(function() {
						if( jQuery(this).prop("checked")== true) {
							salwar_id = jQuery(this).attr("value");
						}
					});
					jQuery(".tassel_id").each(function() {
						if( jQuery(this).prop("checked")== true) {
							tassel_id = jQuery(this).attr("value");
						}
					});
					var data1 = "&front_id="+front_id+"&back_id="+back_id+"&sleeve_id="+sleeve_id+"&service="+jQuery('.service').val();
		            var url1 = '<?php echo Mage::getBaseUrl(); ?>measurement/measure/getmeasurements';
		            try {
						jQuery.ajax({
							url: url1,
							type : 'post',
							data: data1,
							success: function(response){
								if (response) {
									var string = response;
								} else{
									var string = '<div id="measurement_step" class="measurement_details"><p>Currently the Measurements are Unavailable for this product</p></div>';
								}
								jQuery('.style_fit_details').toggle();
								jQuery('.measurement_details').replaceWith(string);
								// jQuery('.measurement_details').toggle();
							}
						});
					} catch(e){ }
	        	// } else if(jQuery(this).parents('.measure_detail').attr('id') == 'measurement'){
	        	// 	alert('measurement');
	        	// } else if(jQuery(this).parents('.measure_detail').attr('id') == 'review'){
	        	// 	alert('review');
	        	}
			});

			jQuery('.goto_reviewstep').click(function() {
	    		var errorcount = 0;
				jQuery('.measurement_attributes').find('#required-entry').each(function(){
					var type = jQuery(this).attr('type');
					if (type == 'text' || type == 'number') {
						var size = jQuery(this).val().length;
					} else if(type == 'radio') {
						var name = jQuery(this).attr('name');
						var size = jQuery('input:radio[name='+name+']:checked').val().length;
					} else{
						var size = jQuery(this).val().length;
					}
					if(size == 0){
						jQuery(this).focus();
						jQuery(this).css('border','1px solid');
						jQuery(this).css('color','red');
						errorcount++;
						return false;
					}else{
						jQuery(this).attr('style','');
					}
				});
				if(errorcount == 0) {
					var data1 = jQuery("form#editmeasurement").serialize();
		    		var url1 = '<?php echo Mage::getBaseUrl(); ?>measurement/measure/getreviewblock';
					try {
						jQuery.ajax({
							url: url1,
							type : 'post',
							data: data1,
							success: function(response){
								if (response) {
									// jQuery('.measurement_block').toggle();
									jQuery('.measurement_review').replaceWith(response);
								}
							}
						});
					} catch(e){ }
				}
	    	});


	        jQuery('select.existing_measurements').change(function() {
	        	if (this.value == 'new') {
	        		var service = parseInt(jQuery('.service').val());
	        		var available_stitching_services = [21, 23];
					// if (jQuery.inArray(service, available_stitching_services) != -1) {
					//   alert('Found');
					// }else{
	        			var data1 = "&service="+service+"&stitching_type="+jQuery('.stitching_type').val();
						var url1 = '<?php echo Mage::getBaseUrl(); ?>measurement/measure/frontstyles';
						try {
							jQuery.ajax({
								url: url1,
								type : 'post',
								data: data1,
								success: function(response){
									if (response) {
										var string = response;
									} else{
										var string = '<div class="measure_details"><div class="measure_detail" id="style_fit"><div class="label_title"><label>1. Style & Fit</label><label class="right"><img src="http://www.renergyteda2014.hubvents.com/assets/images/arrowdown.gif"></label></div><div class="style_fit_details" id="measurement_step"><div class="front"><div class="label_title1"><label>Front Styles</label></div><div class="back_style_details"><p>Currently the Front Styles are Unavailable for this product</p></div></div></div></div></div>';
									}
									jQuery('.measure_details').replaceWith(string);
								}
							});
						} catch(e){ }
	        		// }
	        	} else if(this.value > 0){
	        		var data1 = "&stitching_type="+jQuery('.stitching_type').val()+"&service="+jQuery('.service').val()+"&existing_measurement_id="+this.value+"&product_id=<?php echo $_product->getId(); ?>";
	        		var url1 = '<?php echo Mage::getBaseUrl(); ?>measurement/measure/showreviewblock';
					try {
						jQuery.ajax({
							url: url1,
							type : 'post',
							data: data1,
							success: function(response){
								if (response) {
									var string = response;
								} else{
									var string = '<div class="measure_details"><div id="review" class="measure_detail"><div class="label_title"><label> Review</label></div><div id="measurement_step" class="measurement_review"></div></div></div>';
								}
								jQuery('.measure_details').replaceWith(string);
							}
						});
					} catch(e){ }

	        	}
					
	        });
	    });
	</script>

<style type="text/css">

	.measurements_taking_for{padding-bottom: 20px;}
	.product_image{float: left;max-width: 50%;padding: 0 2%;}
	.product_details{height: 300px;}
	div.existing_measurements{margin: 25px 10px;}
	/*.selected_style_measurements{min-height: 280px;}*/
	.m_attr .value > textarea{width: 20%;line-height: 20px;}
	.m_attr > .value > select {width: 20%;}
	.m_attr > .value > .measurement_textfield {height: 30px;padding-left: 5px;width: 19.3%;}
	.m_attr > .value > .radio_button input {line-height: 30px;width: 15%;max-width: 25px;}
	.measurement_textfield{font-size: 14px;height: 20px;}
	.loading {text-align: center;display:none;}
	.loading > img {position: fixed;}
	.goto_nextstep {text-align: right;}
	.goto_nextstep button, .goto_nextstep input {background: mediumaquamarine none repeat scroll 0 0;border: 0 none;font-size: 14px;font-weight: bold;margin-bottom: 10px;margin: 0 5px;padding: 5px;}
	.additional_comment > input {margin-right: 5px;margin-left: 5px;margin-top: -3px;}
	.front_style_details, .back_style_details, .sleeve_style_details {height: 250px !important;padding: 20px;}
	.measure_details .label_title1{background: #f3f3f3 none repeat scroll 0 0;font-size: 15px;font-weight: bold;margin-bottom: 5px;padding: 3px;text-align: center;}
	.measure_details .label_title{box-shadow: 0px 7px 15px #b6b6b6;background: #cfcfcf none repeat scroll 0 0;font-size: 16px;padding: 5px;margin-bottom:20px;}
	.tabed {background: rgba(0, 0, 0, 0) none repeat scroll 0 0;border-bottom: 1px solid #bdbdbd;font-size: 18px;height: 33px;margin: 8px 0 5px;}
	.tabed .selectedTab {background: #ffffff none repeat scroll 0 0;cursor: default;padding-bottom: 12px;}
	.tabed a {background: #ececec none repeat scroll 0 0;border-color: #b6b6b6 #b6b6b6 -moz-use-text-color;border-image: none;border-style: solid solid none;border-width: 1px 1px medium;color: #414141;cursor: default;float: left;height: 10px;line-height: 10px;margin-left: 5px;padding: 11px 15px;text-decoration: none;}
	.additional_comment {padding: 10px;height: 30px;line-height: 30px;}
	.additional_comment1 {padding: 10px;font-size: 14px;}
	.additional_comment > label {font-size: 14px;padding-right: 20px;}
	.measurement_block {padding: 20px;}	
	.measurement_attributes {padding: 10px 30px;}
	#submitting_measurement_option {line-height: 20px;padding: 5px;}
	.measuring_units, .my_stored_measurement, .simple_measurements {padding: 10px 30px;}
	.measuring_units > p, .simple_measurements > p {border: 1px solid;line-height: 40px;padding-left: 20px;font-size: 15px;color: #4c0f0e;}
	.m_attr .content {border: 1px solid #a2a2a2;border-radius: 5px;display: none;padding: 10px;width: 200px;float: right;margin-right: 20px;}
	.m_attr .image {display: none;float: right;text-align: center;}
	.m_attr {margin-bottom: 10px;padding: 5px;}
	.m_attr > #label {float: left;min-height: 35px;width: 20% !important;}
	.goto_nextstep{display:none;}
	.review_your_measurements1 {font-size: 13px;line-height: 25px;}
	.review_your_measurements1 .label {float: left;text-align: left;width: 65% !important;}
	.review_your_measurements1 .value {float: left;}
	.li_review_selected_style {float: left;padding-bottom: 20px;text-align: center;width: 25%;}
	.desktop td {padding: 5px 10px;text-align: center;}
	.desktop th {padding: 2px 10px;text-align: center;}
	.mobile td {padding: 10px;}
	.measure_details .label_title label{color: #000;font-size: 16px;font-weight: bold;padding-left: 10px;text-transform: uppercase;}
	#measurements_group .title{color: green;font-size: 15px;font-weight: bold;padding: 5px;}
	.custom_measurements .m_attr:first-child #content {display: none;padding: 10px;min-height: 20px;}
	@media (max-width: 600px) {
		.custom_measurements .m_attr:first-child #content {width: 95%;}
		.measurement_block {padding: 20px 10px;}
		.measuring_units, .my_stored_measurement, .simple_measurements {padding: 10px;}
		.measurement_attributes {padding: 10px 10px;}
		.m_attr > .value > .measurement_textfield {width: 58%;}
		.m_attr > #label {width: 100% !important;}
		.m_attr > .value > select{width: 60%;}
		.m_attr .image{margin: 2.5%;width: 95%;}
		.m_attr .content{float: left;margin: 2.5% 0;width: 95%;}
		.li_review_selected_style{width: 100%;}
		.product_image{float: none;max-width: 100%;padding: 5px;text-align: center;border: 1px solid #cfcfcf;}
		.product_image > img{width: 100%;}
		.product_details{height: auto;}
		.main-container .inner-container .product_details  h4 {font-size: 16px;padding-top: 10px;}
		.product_details a {font-size: 14px;color: #d86f65;font-weight: bold;}
		.existing_measurements{margin-left: -10px;}
	}
	@media (min-width: 601px) and (max-width: 1000px) {
		.custom_measurements .m_attr:first-child #content {width: 95%;}
		.measurement_block {padding: 20px 10px;}
		.measuring_units, .my_stored_measurement, .simple_measurements {padding: 10px;}
		.measurement_attributes {padding: 10px 10px;}
		.m_attr > .value > .measurement_textfield {width: 38%;}
		.m_attr > #label {width: 40% !important;}
		.m_attr > .value > select{width: 40%;}
		.m_attr .image{margin: 2.5%;width: 40%;}
		.m_attr .content{float: left;margin: 2.5% 0;width: 40%;}
		.li_review_selected_style{width: 50%;}
	}
</style>