<?php 
	$sleevecollection = Mage::getModel('sleeves/sleeves')
											->getCollection()
											->addFieldToFilter('status',1)
											->addFieldToFilter('front_id',$_REQUEST['front_id'])
											->addFieldToFilter('back_id',$_REQUEST['back_id'])
											->addFieldToFilter('stitching_service_id',$_REQUEST['service']);
	$lehangacollection = Mage::getModel('lehanga/lehanga')
											->getCollection()
											->addFieldToFilter('stitching_service', array('like' => '%'.$_REQUEST['stitching_type'].'%'))
											->addFieldToFilter('status',1)
											->addFieldToFilter('stitching_service_id',$_REQUEST['service']);
	$salwarcollection = Mage::getModel('salwar/salwar')
											->getCollection()
											->addFieldToFilter('stitching_service', array('like' => '%'.$_REQUEST['stitching_type'].'%'))
											->addFieldToFilter('status',1)
											->addFieldToFilter('stitching_service_id',$_REQUEST['service']);
	$tasselcollection = Mage::getModel('tassel/tassel')->getCollection()
											->addFieldToFilter('stitching_service', array('like' => '%'.$_REQUEST['stitching_type'].'%'))
											->addFieldToFilter('status',1)
											->addFieldToFilter('stitching_service_id',$_REQUEST['service']);
?>
<div class="sleeve">
	<div class="label_title1"><label>Sleeve Styles</label></div>
	<div class="sleeve_style_details">
		<?php if(sizeof($sleevecollection) > 0) { ?>
			<ul class="back_style" id="item_style2">
				<?php $i = 0; foreach ($sleevecollection as $key => $_sleeve) { ?>
					<li class="sleeve_style_li" data="<?php echo $i; ?>">
					<div class="title"><label><?php echo $_sleeve->getTitle(); ?></label></div>
					<div class="image"><img width="130" height="180" alt="<?php echo $_sleeve->getTitle(); ?>" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$_sleeve->getImage(); ?>"></div>
					<div class="select_option"><input id="<?php echo $_REQUEST['service']; ?>" class="sleeve_id" name="sleeve_id" type="radio" value="<?php echo $_sleeve->getSleevesId(); ?>" /></div>
					</li>
				<?php $i++; } ?>
			</ul>
		<?php } else { ?>
			<p>Currently the Sleeve Styles are Unavailable for this product</p>
		<?php } ?>
	</div>
	<input type="hidden" class="lehanga_size" value="<?php echo sizeof($lehangacollection); ?>">
	<input type="hidden" class="salwar_size" value="<?php echo sizeof($salwarcollection); ?>">
	<input type="hidden" class="tassel_size" value="<?php echo sizeof($tasselcollection); ?>">
	<script type="text/javascript">
		var jQuery = jQuery.noConflict();
		jQuery(function(){
			jQuery("#item_style2").flexisel();
		    jQuery('.sleeve_id').click(function() {
        		var service = parseInt(jQuery('.service').val());
        		var lehanga_size = parseInt(jQuery('.lehanga_size').val());
        		var salwar_size = parseInt(jQuery('.salwar_size').val());
        		var tassel_size = parseInt(jQuery('.tassel_size').val());
        		var stitching_type = parseInt(jQuery('.stitching_type').val());
        		if (lehanga_size > 0) {
        			var data1 = "&stitching_type="+stitching_type+"&service="+service;
		            var url1 = '<?php echo Mage::getBaseUrl(); ?>measurement/measure/getlehangastyles';
		            try {
						jQuery.ajax({
							url: url1,
							type : 'post',
							data: data1,
							success: function(response){
								if (response) {
									var string = response;
								} else{
									var string = '<div class="lehanga"><p>Currently the Measurements are Unavailable for this product</p></div>';
								}
								jQuery('.lehanga').replaceWith(string);
							}
						});
					} catch(e){ }
        		} else if(salwar_size > 0){
        			var data1 = "&stitching_type="+stitching_type+"&service="+service;
		            var url1 = '<?php echo Mage::getBaseUrl(); ?>measurement/measure/getsalwarstyles';
		            try {
						jQuery.ajax({
							url: url1,
							type : 'post',
							data: data1,
							success: function(response){
								if (response) {
									var string = response;
								} else{
									var string = '<div class="salwar"><p>Currently the Measurements are Unavailable for this product</p></div>';
								}
								jQuery('.salwar').replaceWith(string);
							}
						});
					} catch(e){ }
        		} else if(tassel_size > 0 && salwar_size == 0 & lehanga_size == 0){
        			var data1 = "&stitching_type="+stitching_type+"&service="+service;
		            var url1 = '<?php echo Mage::getBaseUrl(); ?>measurement/measure/gettasselstyles';
		            try {
						jQuery.ajax({
							url: url1,
							type : 'post',
							data: data1,
							success: function(response){
								if (response) {
									var string = response;
								} else{
									var string = '<div class="tassel"><p>Currently the Measurements are Unavailable for this product</p></div>';
								}
								jQuery('.tassel').replaceWith(string);
							}
						});
					} catch(e){ }
        		} else {
        			var front_id = 0;
		        	var back_id = 0;
		        	var sleeve_id = 0;
		        	var lehanga_id = 0;
		        	var tassel_id = 0;
		        	var salwar_id = 0;
			    	jQuery(".front_id").each(function() {
						if( jQuery(this).prop("checked")== true) {
							front_id = jQuery(this).attr("value");
						}
					});
			    	jQuery(".back_id").each(function() {
						if( jQuery(this).prop("checked")== true) {
							back_id = jQuery(this).attr("value");
						}
					});
			    	jQuery(".sleeve_id").each(function() {
						if( jQuery(this).prop("checked")== true) {
							sleeve_id = jQuery(this).attr("value");
						}
					});
					jQuery(".lehanga_id").each(function() {
						if( jQuery(this).prop("checked")== true) {
							lehanga_id = jQuery(this).attr("value");
						}
					});
					jQuery(".salwar_id").each(function() {
						if( jQuery(this).prop("checked")== true) {
							salwar_id = jQuery(this).attr("value");
						}
					});
					jQuery(".tassel_id").each(function() {
						if( jQuery(this).prop("checked")== true) {
							tassel_id = jQuery(this).attr("value");
						}
					});
					var data1 = "&front_id="+front_id+"&back_id="+back_id+"&sleeve_id="+sleeve_id+"&lehanga_id="+lehanga_id+"&salwar_id="+salwar_id+"&tassel_id="+tassel_id+"&service="+service;
		            var url1 = '<?php echo Mage::getBaseUrl(); ?>measurement/measure/getmeasurements';
		            try {
						jQuery.ajax({
							url: url1,
							type : 'post',
							data: data1,
							success: function(response){
								if (response) {
									var string = response;
								} else{
									var string = '<div id="measurement_step" class="measurement_details"><p>Currently the Measurements are Unavailable for this product</p></div>';
								}
								// jQuery('.style_fit_details').toggle();
								jQuery('.measurement_details').replaceWith(string);
								// jQuery('.measurement_details').toggle();
							}
						});
					} catch(e){ }
        		}
			});
		});
	</script>
</div>