<div class="options_submitting_measurement">
	<div id="submitting_measurement_option"><input class="submitting_measurement_option" type="radio" name="measurement_type" value="simple" / > <b>Sample</b> (?) Send your own sample garment for measurements by courier to M/s Mysore Saree Udyog Pvt Ltd. 1st floor 294 K Kamaraj road Bangalore - 560042 India</div>
	<div id="submitting_measurement_option"><input class="submitting_measurement_option" type="radio" name="measurement_type" value="standard" / > <b>Standard Measurement</b></div>
	<div id="submitting_measurement_option"><input class="submitting_measurement_option" type="radio" name="measurement_type" value="custom" / > <b>Custom Measurement</b></div>
</div>
<div class="my_stored_measurement"></div>
<div class="measuring_unit"></div>
<div class="measurement_attributes">
	<div class="simple_measurements"></div>
	<div class="standard_measurements"></div>
	<div class="custom_measurements"></div>
</div>
<script type="text/javascript">
    var jQuery = jQuery.noConflict();
    jQuery(function(){
		jQuery('input.submitting_measurement_option').click(function() {
			if(this.value == 'simple'){
				jQuery('.standard_measurements').replaceWith('<div class="standard_measurements"></div>');
				jQuery('.custom_measurements').replaceWith('<div class="custom_measurements"></div>');
				var data1 = "";
				var url1 = '<?php echo Mage::getBaseUrl(); ?>measurement/measure/takesimplemeasurements';
				try {
					jQuery.ajax({
						url: url1,
						type : 'post',
						data: data1,
						success: function(response){
							if (response) {
								jQuery('.simple_measurements').replaceWith(response);
							}
						}
					});
				} catch(e){ }

			}else if(this.value == 'standard') {
				jQuery('.simple_measurements').replaceWith('<div class="simple_measurements"></div>');
				jQuery('.custom_measurements').replaceWith('<div class="custom_measurements"></div>');
			} else if(this.value == 'custom') {
				jQuery('.simple_measurements').replaceWith('<div class="simple_measurements"></div>');
				jQuery('.standard_measurements').replaceWith('<div class="standard_measurements"></div>');
				jQuery('.custom_measurements').replaceWith('<div class="custom_measurements"></div>');
			}
        });
    });
</script>