<?php
    $url= $_SERVER['REQUEST_URI'];
    $urlarr=explode('/id/',$url);
    $myid= explode('/',$urlarr[1]);
    $attrid = $myid[0];
    if(!empty($attrid)){
    	$collection = Mage::getSingleton('mycategory/mycategory')->getCollection()->addFieldToFilter('mycategory_id',$attrid)->getFirstItem();
    }

    $rootcategories = Mage::getSingleton('catalog/category')->getCategories(Mage::getSingleton('core/store')->load(Mage_Core_Model_App::DISTRO_STORE_ID)->getRootCategoryId());
	$attributes = Mage::getSingleton('catalog/product')->getAttributes();
	$attributeArray = array();
	foreach($attributes as $a){
		foreach ($a->getEntityType()->getAttributeCodes() as $attributeName) {
			$attribute_details = Mage::getSingleton("eav/config")->getAttribute('catalog_product', $attributeName);
			if(($attribute_details->getIsUserDefined() == 1) && ($attribute_details->getFrontendInput() == 'multiselect' || $attribute_details->getFrontendInput() == 'select')){
				$attributeArray[] = array(
										'title' => $attributeName,
										'label' => $attribute_details->getFrontendLabel()
				);
			}
		}
		break;
	}
?>
<table class="form-list" cellspacing="0">
	<tr>
		<td class="label"><label for="category">Target Category <span class="required">*</span></label></td>
		<td class="value">
	        <select class="required-entry select" name="category" id="category">
	        	<option>--- Please Select ---</option>
	        	<?php //foreach($rootcategories as $category){ ?>
					<!-- <option value ="<?php //echo $category->getId(); ?>" <?php //if(isset($collection) && $collection->getCategory() == $category->getId()) { //echo 'selected'; } ?> ><?php //echo $category->getName(); ?></option> -->
					<?php $sub1rootcategories = Mage::getSingleton('catalog/category')->getCategories(132);
					foreach ($sub1rootcategories as $category1) { ?>
						<option value ="<?php echo $category1->getId(); ?>" <?php if (isset($collection) && $collection->getCategory() == $category1->getId()) { echo 'selected'; } ?> ><?php echo ' - '.$category1->getName(); ?></option>
						<?php $sub2rootcategories = Mage::getSingleton('catalog/category')->getCategories($category1->getId());
						foreach ($sub2rootcategories as $category2) { ?>
							<option value ="<?php echo $category2->getId(); ?>" <?php if (isset($collection) && $collection->getCategory() == $category2->getId()) { echo 'selected'; } ?> ><?php echo ' - - '.$category2->getName(); ?></option>
							<?php $sub3rootcategories = Mage::getSingleton('catalog/category')->getCategories($category2->getId());
							foreach ($sub3rootcategories as $category3) { ?>
								<option value ="<?php echo $category3->getId(); ?>" <?php if (isset($collection) && $collection->getCategory() == $category3->getId()) { echo 'selected'; } ?> ><?php echo ' - - - '.$category3->getName(); ?></option>
								<?php $sub4rootcategories = Mage::getSingleton('catalog/category')->getCategories($category3->getId());
								foreach ($sub4rootcategories as $category4) { ?>
									<option value ="<?php echo $category4->getId(); ?>" <?php if (isset($collection) && $collection->getCategory() == $category4->getId()) { echo 'selected'; } ?> ><?php echo ' - - - - '.$category4->getName(); ?></option>
									<?php $sub5rootcategories = Mage::getSingleton('catalog/category')->getCategories($category4->getId());
									foreach ($sub5rootcategories as $category5) { ?>
										<option value ="<?php echo $category5->getId(); ?>" <?php if (isset($collection) && $collection->getCategory() == $category5->getId()) { echo 'selected'; } ?> ><?php echo ' - - - - - '.$category5->getName(); ?></option>
										<?php $sub6rootcategories = Mage::getSingleton('catalog/category')->getCategories($category5->getId());
										foreach ($sub6rootcategories as $category6) { ?>
											<option value ="<?php echo $category6->getId(); ?>" <?php if (isset($collection) && $collection->getCategory() == $category6->getId()) { echo 'selected'; } ?> ><?php echo ' - - - - - - '.$category6->getName(); ?></option>
											<?php $sub6rootcategories = Mage::getSingleton('catalog/category')->getCategories($category6->getId());
											foreach ($sub7rootcategories as $category7) { ?>
												<option value ="<?php echo $category7->getId(); ?>" <?php if (isset($collection) && $collection->getCategory() == $category7->getId()) { echo 'selected'; } ?> ><?php echo ' - - - - - - - '.$category7->getName(); ?></option>
												<?php $sub8rootcategories = Mage::getSingleton('catalog/category')->getCategories($category7->getId());
												foreach ($sub8rootcategories as $category8) { ?>
													<option value ="<?php echo $category8->getId(); ?>" <?php if (isset($collection) && $collection->getCategory() == $category8->getId()) { echo 'selected'; } ?> ><?php echo ' - - - -  - - -  - '.$category8->getName(); ?></option>
													<?php $sub9rootcategories = Mage::getSingleton('catalog/category')->getCategories($category8->getId());
													foreach ($sub9rootcategories as $category9) { ?>
														<option value ="<?php echo $category9->getId(); ?>" <?php if (isset($collection) && $collection->getCategory() == $category9->getId()) { echo 'selected'; } ?> ><?php echo ' - - - - - - - - - '.$category9->getName(); ?></option>
														<?php $sub10rootcategories = Mage::getSingleton('catalog/category')->getCategories($category9->getId());
														foreach ($sub10rootcategories as $category10) { ?>
															<option value ="<?php echo $category10->getId(); ?>" <?php if (isset($collection) && $collection->getCategory() == $category10->getId()) { echo 'selected'; } ?> ><?php echo ' - - -  - - -  - - -  - '.$category10->getName(); ?></option>
														<?php }
													}
												}
											}
										}
									}
								}
							}
						}
					}
				//} ?>
	        </select>
        </td>
	</tr>

	<tr>
		<td class="label"><label for="<?php echo $this->getElement()->getName() ?>"><?php echo $this->getElement()->getLabel() ?> <span class="required">*</span></label></td>
		<td class="value">
        <select class="required-entry required-entry select" name="attr1" id="attribute" onchange="myFunction(this)">
        	<option value="">--- Please Select ---</option>
        	<?php foreach ($attributeArray as $_attribute) { ?>
				<option value="<?php echo $_attribute['title']; ?>" <?php if (isset($collection) && $collection->getAttr1() == $_attribute['title']){ echo 'selected'; } ?> ><?php echo $_attribute['label']; ?></option>
			<?php } ?>
        </select>
        <p id="note_<?php echo $this->getElement()->getName() ?>" class="note"><span><?php echo $this->getElement()->getNote() ?></span></p>
            </td>
	</tr>

	<tr>
        <td class="label"><label for="attr1_values">Attribute 1 Values <span class="required">*</span></label></td>
    	<td class="value">
        	<select multiple="multiple" size="10" class="required-entry required-entry select multiselect" name="attr1_values[]" id="attr1_values">
        		<?php if (isset($collection)) {
        			$attribute = Mage::getSingleton('eav/config')->getAttribute(Mage_Catalog_Model_Product::ENTITY, $collection->getAttr1());
        			$stored_values = explode(',', $collection->getAttr1Values());
        		}
				if (isset($attribute) && $attribute->usesSource()) {
					$options = $attribute->getSource()->getAllOptions(false);
					foreach ($options as $_option) { ?>
						<option value="<?php echo $_option['value']; ?>" <?php if(in_array($_option['value'], $stored_values)){ echo 'selected'; } ?> ><?php echo $_option['label']; ?></option>
					<?php }
				} else{ ?>
					<option value="">--- Please Select A Value Above ---</option>
				<?php } ?>
			</select>
			<p id="note_attr1_values" class="note"><span>Selected attribute values will display in frontend</span></p>
		</td>
    </tr>

	<tr>
		<td class="label"><label for="attr2">Product Attribute 2</label></td>
		<td class="value">
        <select class="select" name="attr2" id="attribute" onchange="myFunction(this)">
        	<option value="">--- Please Select ---</option>
        	<?php foreach ($attributeArray as $_attribute) { ?>
				<option value="<?php echo $_attribute['title']; ?>" <?php if (isset($collection) && $collection->getAttr2() == $_attribute['title']){ echo 'selected'; } ?> ><?php echo $_attribute['label']; ?></option>
			<?php } ?>
        </select>
        <p class="note" id="note_attr2"><span>Selected One Attribute</span></p>
            </td>
	</tr>

	<tr>
        <td class="label"><label for="attr2_values">Attribute 2 Values </label></td>
    	<td class="value">
        	<select multiple="multiple" size="10" class="select multiselect" name="attr2_values[]" id="attr2_values">
        		<?php if (isset($collection)) {
        			$attribute = Mage::getSingleton('eav/config')->getAttribute(Mage_Catalog_Model_Product::ENTITY, $collection->getAttr2());
        			$stored_values = explode(',', $collection->getAttr2Values());
        		}
				if (isset($attribute) && $attribute->usesSource()) {
					$options = $attribute->getSource()->getAllOptions(false);
					foreach ($options as $_option) { ?>
						<option value="<?php echo $_option['value']; ?>" <?php if(in_array($_option['value'], $stored_values)){ echo 'selected'; } ?> ><?php echo $_option['label']; ?></option>
					<?php }
				} else{ ?>
					<option value="">--- Please Select A Value Above ---</option>
				<?php } ?>
			</select>
			<p id="note_attr2_values" class="note"><span>Selected attribute values will display in frontend</span></p>
		</td>
    </tr>

	<tr>
		<td class="label"><label for="attr3">Product Attribute 3</label></td>
		<td class="value">
        <select class="select" name="attr3" id="attribute" onchange="myFunction(this)">
        	<option value="">--- Please Select ---</option>
        	<?php foreach ($attributeArray as $_attribute) { ?>
				<option value="<?php echo $_attribute['title']; ?>" <?php if (isset($collection) && $collection->getAttr3() == $_attribute['title']){ echo 'selected'; } ?> ><?php echo $_attribute['label']; ?></option>
			<?php } ?>
        </select>
        <p class="note" id="note_attr3"><span>Selected One Attribute</span></p>
            </td>
	</tr>

	<tr>
        <td class="label"><label for="attr3_values">Attribute 3 Values </label></td>
    	<td class="value">
        	<select multiple="multiple" size="10" class="select multiselect" name="attr3_values[]" id="attr3_values">
        		<?php if (isset($collection)) {
        			$attribute = Mage::getSingleton('eav/config')->getAttribute(Mage_Catalog_Model_Product::ENTITY, $collection->getAttr3());
        			$stored_values = explode(',', $collection->getAttr3Values());
        		}
				if (isset($attribute) && $attribute->usesSource()) {
					$options = $attribute->getSource()->getAllOptions(false);
					foreach ($options as $_option) { ?>
						<option value="<?php echo $_option['value']; ?>" <?php if(in_array($_option['value'], $stored_values)){ echo 'selected'; } ?> ><?php echo $_option['label']; ?></option>
					<?php }
				} else{ ?>
					<option value="">--- Please Select A Value Above ---</option>
				<?php } ?>
			</select>
			<p id="note_attr3_values" class="note"><span>Selected attribute values will display in frontend</span></p>
		</td>
    </tr>

	<tr>
		<td class="label"><label for="attr4">Product Attribute 4</label></td>
		<td class="value">
        <select class="select" name="attr4" id="attribute" onchange="myFunction(this)">
        	<option value="">--- Please Select ---</option>
        	<?php foreach ($attributeArray as $_attribute) { ?>
				<option value="<?php echo $_attribute['title']; ?>" <?php if (isset($collection) && $collection->getAttr4() == $_attribute['title']){ echo 'selected'; } ?> ><?php echo $_attribute['label']; ?></option>
			<?php } ?>
        </select>
        <p class="note" id="note_attr4"><span>Selected One Attribute</span></p>
            </td>
	</tr>

	<tr>
        <td class="label"><label for="attr4_values">Attribute 4 Values </label></td>
    	<td class="value">
        	<select multiple="multiple" size="10" class="select multiselect" name="attr4_values[]" id="attr4_values">
        		<?php if (isset($collection)) {
        			$attribute = Mage::getSingleton('eav/config')->getAttribute(Mage_Catalog_Model_Product::ENTITY, $collection->getAttr4());
        			$stored_values = explode(',', $collection->getAttr4Values());
        		}
				if (isset($attribute) && $attribute->usesSource()) {
					$options = $attribute->getSource()->getAllOptions(false);
					foreach ($options as $_option) { ?>
						<option value="<?php echo $_option['value']; ?>" <?php if(in_array($_option['value'], $stored_values)){ echo 'selected'; } ?> ><?php echo $_option['label']; ?></option>
					<?php }
				} else{ ?>
					<option value="">--- Please Select A Value Above ---</option>
				<?php } ?>
			</select>
			<p id="note_attr4_values" class="note"><span>Selected attribute values will display in frontend</span></p>
		</td>
    </tr>

	<tr>
		<td class="label"><label for="attr5">Product Attribute 5</label></td>
		<td class="value">
        <select class="select" name="attr5" id="attribute" onchange="myFunction(this)">
        	<option value="">--- Please Select ---</option>
        	<?php foreach ($attributeArray as $_attribute) { ?>
				<option value="<?php echo $_attribute['title']; ?>" <?php if (isset($collection) && $collection->getAttr5() == $_attribute['title']){ echo 'selected'; } ?> ><?php echo $_attribute['label']; ?></option>
			<?php } ?>
        </select>
        <p class="note" id="note_attr5"><span>Selected One Attribute</span></p>
            </td>
	</tr>

	<tr>
        <td class="label"><label for="attr5_values">Attribute 5 Values </label></td>
    	<td class="value">
        	<select multiple="multiple" size="10" class="select multiselect" name="attr5_values[]" id="attr5_values">
        		<?php if (isset($collection)) {
        			$attribute = Mage::getSingleton('eav/config')->getAttribute(Mage_Catalog_Model_Product::ENTITY, $collection->getAttr5());
        			$stored_values = explode(',', $collection->getAttr5Values());
        		}
				if (isset($attribute) && $attribute->usesSource()) {
					$options = $attribute->getSource()->getAllOptions(false);
					foreach ($options as $_option) { ?>
						<option value="<?php echo $_option['value']; ?>" <?php if(in_array($_option['value'], $stored_values)){ echo 'selected'; } ?> ><?php echo $_option['label']; ?></option>
					<?php }
				} else{ ?>
					<option value="">--- Please Select A Value Above ---</option>
				<?php } ?>
			</select>
			<p id="note_attr5_values" class="note"><span>Selected attribute values will display in frontend</span></p>
		</td>
    </tr>

</table>
<script src="https://code.jquery.com/jquery-latest.min.js" type="text/javascript"></script>
<script type="text/javascript">
	var jQuery = jQuery.noConflict();
	// jQuery(function(){
		function myFunction(a) {
			var data1 = "&attribute="+a.value+'&name='+a.name;
			var url1 = '<?php echo Mage::getBaseUrl(); ?>mycategory/index/getattributevalues';
			try {
				jQuery.ajax({
					url: url1,
					type : 'post',
					data: data1,
					success: function(response){
						if (response) {
							jQuery('#'+a.name+'_values').replaceWith(response);
						}
					}
				});
			} catch(e){ }
		}
		// jQuery('#attribute').change(function() {
		// 	alert('Hi');
			// var data1 = "&attribute="+this.value+'&name='jQuery(this).attr('name');
			// var url1 = '<?php echo Mage::getBaseUrl(); ?>styles/index/availstittypes';
			// try {
			// 	jQuery.ajax({
			// 		url: url1,
			// 		type : 'post',
			// 		data: data1,
			// 		success: function(response){
			// 			if (response) {
			// 				var string = response;
			// 			} else{
			// 				var string = '<select multiple="multiple" size="10" class="required-entry required-entry select multiselect" name="stitching_service[]" id="stitching_service"><option>--- Select Multiple Options ---</option></select>';
			// 			}
			// 			jQuery('#stitching_service').replaceWith(string);
			// 		}
			// 	});
			// } catch(e){ }
		// });
	// });
</script>