<!--<div id="footer-cat-links">

<?php $helper = $this->helper('catalog/category') ?>
<?php foreach ($helper->getStoreCategories() as $_category): ?>
<div class="footercats">
<h3><a href="<?php echo Mage::getModel('catalog/category')->setData($_category->getData())->getUrl(); ?>" title="<?php echo $_category->getName() ?>"><?php echo $_category->getName() ?></a></h3>
<ul>
<li> <a href="#"><?php echo "test";?></a></li>
<!-- loop through sub categories
</ul>
</div>
<?php endforeach ?>

</div>-->
<div class="">
  <div id="footer-cat-links">
  <h4 class="heading_four">Categories</h4>
    <ul class="sitemap-arrow">
      <li><a href="<?php echo 'http://demo.mysoresareeudyog.com/sarees-1.html'; ?>">Saree</a></li>
      <li><a href="<?php echo 'http://demo.mysoresareeudyog.com/salwar-kameez.html'; ?>">Salwar Suits</a></li>
      <li><a href="<?php echo 'http://demo.mysoresareeudyog.com/fabrics.html'; ?>">Fabric</a></li>
    </ul>
    <ul class="sitemap-arrow">
      <li><a href="<?php echo 'http://demo.mysoresareeudyog.com/accessories.html'; ?>">Accessories</a></li>
      <li><a href="<?php echo 'http://demo.mysoresareeudyog.com/lehanga-1.html'; ?>">Lahenga</a></li>
      <li><a href="<?php echo 'http://demo.mysoresareeudyog.com/lehanga-1/bridal-designer.html'; ?>">Bridal</a></li>
    </ul>
    <ul class="sitemap-arrow">
      <li><a href="<?php echo 'http://demo.mysoresareeudyog.com/more/mens-wear.html'; ?>">Men's Wear</a></li>
      <li><a href="<?php echo 'http://demo.mysoresareeudyog.com/more/home-furnishing.html' ;?>">Home Furnishing</a></li>
      <li><a href="<?php echo 'http://demo.mysoresareeudyog.com/catalogsearch/result/?q=ready+to+wear'; ?>">Garments</a></li>
    </ul>
    <ul class="sitemap-arrow">
      <li><a href="<?php echo 'http://demo.mysoresareeudyog.com/kurtis.html'; ?>">Kurti</a></li>
      <li><a href="<?php echo 'http://demo.mysoresareeudyog.com/blouses.html'; ?>">Blouses</a></li>
      <li><a href="<?php echo 'http://demo.mysoresareeudyog.com/embellishments.html'; ?>">Embellishment</a></li>
    </ul>
    <ul style="height: 68px;" class="sitemap-arrow">
      <li><a href="<?php echo $this->getBaseUrl().'customize.html';?>">Customize</a></li>
      <li><a href="<?php echo $this->getBaseUrl().'jobwork.html';?>">Jobwork</a></li>
	  <li><a href="<?php echo $this->getBaseUrl().'jobwork.html';?>"> </a></li>
    </ul>
    <ul class="sitemap-arrow">
      <h4 class="heading_four">Company Info</h4>
      <li><a href="<?php echo 'http://demo.mysoresareeudyog.com/about_us/'; ?>">About Us</a></li>
      <li><a class="grey11" href="<?php echo 'http://demo.mysoresareeudyog.com/corporate_order/'; ?>">Corporate Order</a></li>
      <li><a class="grey11" href="<?php echo 'http://demo.mysoresareeudyog.com/business_with_us/'; ?>">Business With Us</a></li>
      <li><a class="grey11" href="<?php echo 'http://demo.mysoresareeudyog.com/work_with_us/'; ?>">Work With Us</a></li>
      <li><a class="grey11" href="<?php echo 'http://demo.mysoresareeudyog.com/testimonials/'; ?>">Customer Testimonials</a></li>
    </ul>
    <ul class="sitemap-arrow">
      <h4 class="heading_four">Mysore Saree Udyog</h4>
      <li><a href="<?php echo 'http://demo.mysoresareeudyog.com/sale'; ?>">Sale</a></li>
      <li><a href="<?php echo 'http://demo.mysoresareeudyog.com/catalog/'; ?>">Catalog</a></li>
      <li><a href="<?php echo 'http://demo.mysoresareeudyog.com/season/'; ?>">Season</a></li>
	  <li><a href="<?php echo 'http://demo.mysoresareeudyog.com/library_resource/'; ?>">Library</a></li>
    </ul>
    <ul class="sitemap-arrow">
      <h4 class="heading_four">T&amp;C and Policies</h4>
      <li><a href="<?php echo 'http://demo.mysoresareeudyog.com/returns/'?>">Returns</a></li>
<li><a href="<?php echo 'http://demo.mysoresareeudyog.com/shipping/'?>">Shipping</a></li>
<li><a href="<?php echo 'http://demo.mysoresareeudyog.com/payment/'?>">Payment</a></li>
<li><a href="<?php echo 'http://demo.mysoresareeudyog.com/privacy/'?>">Privacy</a></li>
<li><a href="<?php echo 'http://demo.mysoresareeudyog.com/disclaimer/'?>">Disclaimer</a></li>
<li><a href="<?php echo 'http://demo.mysoresareeudyog.com/terms_of_use/'?>">Terms of Use</a></li>
<li><a href="<?php echo 'http://demo.mysoresareeudyog.com/Wash_and_Care/'?>">Wash & Care</a></li>
<li><a href="<?php echo 'http://demo.mysoresareeudyog.com/best-price-challenge/'?>">Best Price Challenge</a></li>
    </ul>
    <ul class="sitemap-arrow">
      <h4 class="heading_four">Account</h4>
      <li><a href="<?php echo 'https://demo.mysoresareeudyog.com/customer/account/'?>">My Account</a></li>
      <li><a href="<?php echo 'https://demo.mysoresareeudyog.com/sales/order/history/'?>">My Orders</a></li>
      <li><a href="<?php echo 'https://demo.mysoresareeudyog.com/wishlist/'?>">My Wishlist</a></li>
      <li><a href="<?php echo 'http://demo.mysoresareeudyog.com/track-your-order/'?>">Track Order</a></li>
      <?php if ($this->helper('customer')->isLoggedIn() ) { ?>
      <li><a href="<?php echo 'http://demo.mysoresareeudyog.com/customer/account/logout/'?>">Log Out</a></li>
      <?php }
else{ ?>
      <li><a href="<?php echo 'https://demo.mysoresareeudyog.com/customer/account/login/'?>">Sign In</a></li>
      <li><a href="<?php echo 'https://demo.mysoresareeudyog.com/customer/account/create'?>">Register</a></li>
      <?php } ?>
    </ul>
    <ul class="sitemap-arrow">
	 <h4 class="heading_four">Customer Care</h4>
    <li><a href="<?php echo 'http://demo.mysoresareeudyog.com/our_customer_are_talking_about_us'?>">Our Customers are Talking About Us</a></li>
    <li><a href="<?php echo 'http://demo.mysoresareeudyog.com/faq/'?>">FAQ</a></li>
    <li><a href="<?php echo 'http://demo.mysoresareeudyog.com/contactcustomer'?>">Customer Service </a></li>
	  <li><a href="<?php echo 'http://demo.mysoresareeudyog.com/feedback'?>">Give Feedback</a></li>
    </ul>
  </div>
  
</div>
