<?php
    if(Mage::helper('customer')->isLoggedIn()) {
        $_order = Mage::getResourceModel('sales/order_collection')
        ->addFieldToSelect('*')
        ->addFieldToFilter('customer_id', Mage::getSingleton('customer/session')->getCustomer()->getId())
        ->addFieldToFilter('status', array("nin" => array('canceled', 'delivered')))
        ->setOrder('created_at', 'desc'); ?>

        <div><p class="filterbyorder" id="orderstatus">Select Your Order to Know The Order Status </p><br><select class="customer_orders" id="customerdrop"><option>Choose Your Order</option>
		<?php foreach ($_order as $order) { ?>
			<option <?php if (isset($_REQUEST['order_id']) && $_REQUEST['order_id'] == $order->getRealOrderId()) {
				echo 'selected'; } ?> value="<?php echo Mage::getBaseUrl().'track_order?order_id='.$order->getRealOrderId(); ?>"><?php echo $order->getRealOrderId(); ?></option>
		<?php } ?>
		</select></div>
            <p class="trackback-link"><a href="http://demo.mysoresareeudyog.com/sales/order/history/"><small>« </small>Back To My Orders</a></p>
    		<?php if (!empty($_REQUEST['order_id'])) {
		 		$_order = Mage::getModel('sales/order')->loadByIncrementId($_REQUEST['order_id']);
                    $country_id = strtolower($order->getShippingAddress()->getCountryId());
                   $shipmentCollection = Mage::getResourceModel('sales/order_shipment_collection')
                                     ->setOrderFilter($_order)
                                     ->load();
                    foreach ($shipmentCollection as $shipment){
                         foreach($shipment->getAllTracks() as $tracknum) {
                                    echo "Tracking Number :" , $tracknum->getNumber() ;
                            if ($tracknum->getCarrierCode() == 'fedex') { 
                                ?>
                                <p>Courier Service : FEdEX</p><a href="https://www.fedex.com/apps/fedextrack/?tracknumbers=<?php echo $tracknum->getNumber(); ?>&cntry_code=<?php echo $country_id; ?>" target="_blank">Click Here To Track Your Order</a>
                            <?php } else if($tracknum->getCarrierCode() == 'custom') {
                                          $shipment->getCarrierTitle(); ?>
                           <p>Please Note  Tracking Number Before Going To The IndiaPost</p><p class="couriername">Courier  Service  : IndiaPost</p><a href="http://www.indiapost.gov.in/speednettracking.aspx/?tracknumbers=<?php echo $tracknum->getNumber(); ?>&cntry_code=<?php echo $country_id; ?>" target="_blank">Click Here To Track Your Order</a>
                          <?php }
                            }
                    }
                     ?>

			 		<div class="page-title title-buttons" id="ordernumber">
				    <h1 class="ordernumberid"><?php echo 'Order # '.$_order->getRealOrderId().'<br>Order Status: '.$_order->getStatusLabel(); ?></h1>
					</div>
				
		 	<?php } ?>
	<?php } else{ ?>
		<div class="trackorder_form"><h4 class="trackdetails">TRACK ORDER</h4><p>Registered Customer ?</p><p>Please <a href="<?php echo Mage::getUrl('customer/account/login'); ?>" ><b>Login </b></a>to Track Shipment .</p><h5>OR</h5>
         <p>If you are Un Registered Customer </p> <p>Please Enter any two fields to see the status of your order.</p> </div>      
         <form action="http://demo.mysoresareeudyog.com/track_order/" method="GET">
		     <div class="field">
				<label class="required" for="order_id">Order Number:</label>
					<input id="order_id"  class="input-text required-entry" type="text" value="" name="order_id"></div><br>
			 			<div class="field">
				<label class="required" for="email_address">Email Address:</label>
					<input id="email_address"  class="input-text required-entry" type="text" size="30" value="" name="email_address"></div><br>
				<label class="required" for="phone">Mobile Number:</label>
					<input id="phone"  class="input-text required-entry" type="text" size="30" value="" name="phone"></div><br>
		     <button class="button" type="submit" title="Submit"><span>submit</span></button>
             <?php if ( (isset($_REQUEST['order_id']) && !empty($_REQUEST['order_id'])) && (isset($_REQUEST['email_address']) && !empty($_REQUEST['email_address'])) && (isset($_REQUEST['phone']) && !empty($_REQUEST['phone'])) ) {
               $_order1 = Mage::getResourceModel('sales/order_collection')
                                ->addFieldToSelect('*')
                                ->addFieldToFilter('customer_email', $_REQUEST['email_address'])
                                ->addFieldToFilter('status', array("nin" => array('canceled', 'delivered')));
				if (sizeof($_order1) > 0) { ?>
                <select class="customer_orders" id="customerdrop">
                    <!-- <option></option> -->
                    <?php foreach ($_order1 as $order) {
                        if (isset($order)) {
                            $telephone = (string)$order->getShippingAddress()->getTelephone();
                            $telephone1 = (string)$_REQUEST['phone'];
                            if ( strcasecmp($telephone, $telephone1) > 0 || strcasecmp($telephone1,$telephone) > 0 ) { ?>
                                <option <?php if (isset($_REQUEST['order_id']) && $_REQUEST['order_id'] == $order->getRealOrderId()) { echo 'selected'; } ?> value="<?php echo Mage::getBaseUrl().'track_order?order_id='.$order->getRealOrderId(); ?>&email_address=<?php echo $_REQUEST['email_address']; ?>&phone=<?php echo $_REQUEST['phone']; ?>"><?php echo $order->getRealOrderId(); ?></option>
                            <?php }
                        }
                     ?>
                    <?php } ?>
                </select>
                <?php } ?>
             <?php } ?>
		</form>
          
		<?php $count = 0;
		    $mycount = 0;
		if ( (isset($_REQUEST['order_id']) && isset($_REQUEST['email_address'])) || (isset($_REQUEST['order_id']) && isset($_REQUEST['phone'])) || (isset($_REQUEST['phone']) && isset($_REQUEST['email_address'])) ) {

			if( isset($_REQUEST['order_id']) && isset($_REQUEST['email_address']) && !empty($_REQUEST['order_id']) && !empty($_REQUEST['email_address']) ){
				$_order = Mage::getResourceModel('sales/order_collection')
								->addFieldToSelect('*')
								->addFieldToFilter('increment_id', $_REQUEST['order_id'])
								->getFirstItem();
				if (isset($_order)) {
					$val = strcasecmp( (string)$_order->getCustomerEmail(), (string)$_REQUEST['email_address'] );
					if ((int)$val > 0) {
						$count = 1;
					}
				}
			} else if( isset($_REQUEST['phone']) && isset($_REQUEST['email_address']) && !empty($_REQUEST['phone']) && !empty($_REQUEST['email_address']) ){
				$mycount = 1;
				$_order = Mage::getResourceModel('sales/order_collection')
								->addFieldToSelect('*')
								->addFieldToFilter('customer_email', $_REQUEST['email_address'])
								->addFieldToFilter('status', array("nin" => array('canceled', 'delivered')));
				if (sizeof($_order) > 0) { ?>
					<select class="customer_orders" id="customerdrop">
	                	<option>Choose Your Order</option>
						<?php foreach ($_order as $order) {
							if (isset($order) && $mycount == 1) {
								$telephone = (string)$order->getShippingAddress()->getTelephone();
								$telephone1 = (string)$_REQUEST['phone'];
								if ( strcasecmp($telephone, $telephone1) > 0 || strcasecmp($telephone1,$telephone) > 0 ) { ?>
									<option <?php if (isset($_REQUEST['order_id']) && $_REQUEST['order_id'] == $order->getRealOrderId()) { echo 'selected'; } ?> value="<?php echo Mage::getBaseUrl().'track_order?order_id='.$order->getRealOrderId(); ?>&email_address=<?php echo $_REQUEST['email_address']; ?>&phone=<?php echo $_REQUEST['phone']; ?>"><?php echo $order->getRealOrderId(); ?></option>
								<?php }
							}
						 ?>
						<?php } ?>
					</select>
				<?php } ?>

				<?php 
			} else if(isset($_REQUEST['order_id']) && isset($_REQUEST['phone']) && !empty($_REQUEST['order_id']) && !empty($_REQUEST['phone']) ){
				$_order = Mage::getResourceModel('sales/order_collection')
								->addFieldToSelect('*')
								->addFieldToFilter('increment_id', $_REQUEST['order_id'])
								->getFirstItem();
				if (isset($_order)) {
					$telephone = (string)$_order->getShippingAddress()->getTelephone();
					$telephone1 = (string)$_REQUEST['phone'];
					if ( strcasecmp($telephone, $telephone1) > 0 || strcasecmp($telephone1,$telephone) > 0 ) {
						$count = 1;
					}
				}
			}
                    
			if (isset($_order) && $count == 0 && $mycount == 0) {  ?>
				<div class="page-title title-buttons" id="ordernumber">
			    	<h1 class="ordernumberid"><?php echo 'Order # - '.$_order->getRealOrderId().'<br>Order Status :'.$_order->getStatusLabel(); ?></h1>
				</div>
                 <?php $_order = Mage::getModel('sales/order')->loadByIncrementId($_REQUEST['order_id']);
                     $shipmentCollection = Mage::getResourceModel('sales/order_shipment_collection')
                                     ->setOrderFilter($_order)
                                     ->load();
                                      foreach ($shipmentCollection as $shipment){
                         foreach($shipment->getAllTracks() as $tracknum) {
                            echo "Tracking Number :" , $tracknum->getNumber() ;
                            if ($tracknum->getCarrierCode() == 'fedex') { ?>
                                <p>Courier  Service  : FEdEX</p><a href="https://www.fedex.com/apps/fedextrack/?tracknumbers=<?php echo $tracknum->getNumber(); ?>&cntry_code=<?php echo $country_id; ?>" target="_blank">Click Here To Track Your Order</a>
                            <?php } else if($tracknum->getCarrierCode() == 'custom') {
                                          $shipment->getCarrierTitle(); ?>
                        <p>Please Note The Tracking Number Before Going To The IndiaPost</p><p class="couriername">Courier  Service  : IndiaPost</p><a href="http://www.indiapost.gov.in/speednettracking.aspx/?tracknumbers=<?php echo $tracknum->getNumber(); ?>&cntry_code=<?php echo $country_id; ?>" target="_blank">Click Here To Track Your Order</a>
                          <?php }
                            }
                    } ?>
    		<?php } else {
			  // echo 'Please Enter Valid Two Fields';
			}
		} else if(isset($_REQUEST['order_id']) || isset($_REQUEST['email_address']) || isset($_REQUEST['phone'])){
			echo 'Please Enter Valid Two Fields';
		} ?>
    <?php } ?>
<script type="text/javascript">
	var jQuery = jQuery.noConflict();
	jQuery('select.customer_orders').change(function(){
		window.location = this.value;
	});
</script>
<style type="text/css">
.ordernumberid {font-family: "Lucida Grande";font-size: 20px;}
#email_address , #order_id , #phone{width: 33%;}
.filterby {float: left;margin-left: -63px; }
#orderstatus { color: #004250;font-family: "Lucida Grande";font-size: 20px;}
#customerdrop {font-family: "Lucida Grande";font-size: 16px;}
.header-wrapper .header-container .main-header .right-header-menu .search-container { border-left: 1px solid #cfcfcf;}
@media (max-width: 720px) {
	.main-breadcrumbs {margin-top: 49px !important;}
	#email_address, #order_id, #phone{width: 50%;}
}
</style>