<?php
/**
 * This file is part of The Official Amazon Payments Magento Extension
 * (c) Pay with Amazon
 * All rights reserved
 *
 * Reuse or modification of this source code is not allowed
 * without written permission from Pwatech
 *
 * @category   Pwa
 * @package    Pwa_PaywithAmazon
 * @copyright  Pay with Amazon
 * @author     Pay with Amazon
 */
?>
<button type="submit" title="<?php echo $this->helper('checkout')->__('Place Order') ?>" class="button btn-checkout" onclick="checkout.saveOrder();"><span><span><?php echo $this->helper('checkout')->__('Place Order') ?></span></span></button>
