<?php $measurement = Mage::getSingleton('measurementremember/measurementremember')->load($_REQUEST['id']);
// print_r($measurement->getData());
$name = Mage::getSingleton('customer/customer')->load($measurement->getCId())->getName();
$attribute = Mage::getSingleton('eav/config')->getAttribute('catalog_product', 'a27');
?>
<div class="main-wrapper" style="border: 10px solid; margin: 0pt auto; width: 651px; padding: 10px;">
	<div class="header">
		<div class="lft-div" style="width:300px;">
			<span><img src="/skin/frontend/default/default/images/logo_email.gif" /></span><br/>
				<span>#10/A, 2nd Floor, Chandrakiran Building, <br> Kasturba Road,</span> <span>Bangalore - 560001.</span><br/>
				<span>Phone : +91 8722 8023 03/17</span><br/>
				Email: ecommerce@mysoresareeudyog.com<br/> URL: www.mysoresareeudyog.com <br />
		</div>
		<div class="rht-div">
			<span><b>Customer Name : </b><?php echo $name; ?></span><br />
			<?php if($measurement->getOrderId() > 0){ ?>
				<span><b>Order # : </b><?php echo Mage::getSingleton('sales/order')->load($measurement->getOrderId())->getIncrementId(); ?></span><br />
			<?php } ?>
			<span><b>Item Code : </b><?php echo $measurement->getSku(); ?></span><br />
			<?php if($attribute->usesSource()){ ?>
				<span><b>Stitching Name : </b><?php echo $attribute->getSource()->getOptionText($measurement->getStitchingServiceId()); ?></span>
			<?php } ?>
		</div>
	</div>
	<div class="clr"></div><br />
	<div class="body">
		<p class="des">Your Current Measurements under "<b><?php echo $measurement->getTitle(); ?></b>" are as below</p>
		<?php $flatrates = Mage::getSingleton('measurementremember/flatrates')->getCollection()->addFieldToFilter('measurementremember_id',$measurement->getMeasurementrememberId())->getFirstItem();
		echo '<div class=review_selected_style><ul class=ul_review_selected_style>';
			if ($flatrates->getFrontId() > 0) {
				$details = Mage::getSingleton('styles/styles')->getCollection()->addFieldToSelect('*')->addFieldToFilter('style_id',$flatrates->getFrontId())->addFieldToFilter('status',1)->getFirstItem(); ?>
				<li>
					<div class="details">
						<div class="title">
							<label>Front Style & Measurements</label>
						</div>
						<div class="more_details">
							<div class="image"><img width="300" height="400" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$details->getImage(); ?>"></div>
							<div class="info">
								<?php $attr = explode(',', $details->getMeasurementAttr());
								foreach ($attr as $value) {
									$b = $flatrates->{'get' .$value}();
									if (isset($b) && $b > 0) {
										$measurement = Mage::getSingleton('measurement/measurement')->getCollection()->addFieldToSelect('*')->addFieldToFilter('measurement_id',$value)->addFieldToFilter('status',1)->getFirstItem(); ?>
										<div class="review_your_measurements1">
											<label class="label"><b><?php echo $measurement->getTitle().' : '; ?></b></label>
											<?php if($measurement->getDropdownType() == 'custom'){
												$customtitles = Mage::getModel('measurement/customtitles')->load($flatrates->{'get' .$value}());
												$final_value = $customtitles->getTitle();
											}else{
												if($measurement->getFieldType() == 'text_area'){
													$final_value = $flatrates->{'get' .$value}();
												}else{
													$final_value = $flatrates->{'get' .$value}().' '.$flatrates->getMeasurmentUnits();
												}
											} ?>
											<label class="value"><?php echo $final_value; ?></label>
										</div>
									<?php }
								} ?>
							</div>
						</div>
					</div>
					<div class="clearer"></div>
				</li>
			<?php }
			if ($flatrates->getBackId() > 0) {
				$details = Mage::getSingleton('back/back')->getCollection()->addFieldToSelect('*')->addFieldToFilter('back_id',$flatrates->getBackId())->addFieldToFilter('status',1)->getFirstItem(); ?>
				<li>
					<div class="details">
						<div class="title">
							<label>Back Style & Measurements</label>
						</div>
						<div class="more_details">
							<div class="image"><img width="300" height="400" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$details->getImage(); ?>"></div>
							<div class="info">
								<?php $attr = explode(',', $details->getMeasurementAttr());
								foreach ($attr as $value) {
									$b = $flatrates->{'get' .$value}();
									if (isset($b) && $b > 0) {
										$measurement = Mage::getSingleton('measurement/measurement')->getCollection()->addFieldToSelect('*')->addFieldToFilter('measurement_id',$value)->addFieldToFilter('status',1)->getFirstItem(); ?>
										<div class="review_your_measurements1">
											<label class="label"><b><?php echo $measurement->getTitle().' : '; ?></b></label>
											<?php if($measurement->getDropdownType() == 'custom'){
												$customtitles = Mage::getModel('measurement/customtitles')->load($flatrates->{'get' .$value}());
												$final_value = $customtitles->getTitle();
											}else{
												if($measurement->getFieldType() == 'text_area'){
													$final_value = $flatrates->{'get' .$value}();
												}else{
													$final_value = $flatrates->{'get' .$value}().' '.$flatrates->getMeasurmentUnits();
												}
											} ?>
											<label class="value"><?php echo $final_value; ?></label>
										</div>
									<?php }
								} ?>
							</div>
						</div>
					</div>
					<div class="clearer"></div>
				</li>
			<?php }
			if ($flatrates->getSleeveId() > 0) {
				$details = Mage::getSingleton('sleeves/sleeves')->getCollection()->addFieldToSelect('*')->addFieldToFilter('sleeves_id',$flatrates->getSleeveId())->addFieldToFilter('status',1)->getFirstItem(); ?>
				<li>
					<div class="details">
						<div class="title">
							<label>Sleeve Style & Measurements</label>
						</div>
						<div class="more_details">
							<div class="image"><img width="300" height="400" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$details->getImage(); ?>"></div>
							<div class="info">
								<?php $attr = explode(',', $details->getMeasurementAttr());
								foreach ($attr as $value) {
									$b = $flatrates->{'get' .$value}();
									if (isset($b) && $b > 0) {
										$measurement = Mage::getSingleton('measurement/measurement')->getCollection()->addFieldToSelect('*')->addFieldToFilter('measurement_id',$value)->addFieldToFilter('status',1)->getFirstItem(); ?>
										<div class="review_your_measurements1">
											<label class="label"><b><?php echo $measurement->getTitle().' : '; ?></b></label>
											<?php if($measurement->getDropdownType() == 'custom'){
												$customtitles = Mage::getModel('measurement/customtitles')->load($flatrates->{'get' .$value}());
												$final_value = $customtitles->getTitle();
											}else{
												if($measurement->getFieldType() == 'text_area'){
													$final_value = $flatrates->{'get' .$value}();
												}else{
													$final_value = $flatrates->{'get' .$value}().' '.$flatrates->getMeasurmentUnits();
												}
											} ?>
											<label class="value"><?php echo $final_value; ?></label>
										</div>
									<?php }
								} ?>
							</div>
						</div>
					</div>
					<div class="clearer"></div>
				</li>
			<?php }
			if ($flatrates->getLehangaId() > 0) {
				$details = Mage::getSingleton('lehanga/lehanga')->getCollection()->addFieldToSelect('*')->addFieldToFilter('lehanga_id',$flatrates->getLehangaId())->addFieldToFilter('status',1)->getFirstItem(); ?>
				<li>
					<div class="details">
						<div class="title">
							<label>Lehanga/Skert Style & Measurements</label>
						</div>
						<div class="more_details">
							<div class="image"><img width="300" height="400" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$details->getImage(); ?>"></div>
							<div class="info">
								<?php $attr = explode(',', $details->getMeasurementAttr());
								foreach ($attr as $value) {
									$b = $flatrates->{'get' .$value}();
									if (isset($b) && $b > 0) {
										$measurement = Mage::getSingleton('measurement/measurement')->getCollection()->addFieldToSelect('*')->addFieldToFilter('measurement_id',$value)->addFieldToFilter('status',1)->getFirstItem(); ?>
										<div class="review_your_measurements1">
											<label class="label"><b><?php echo $measurement->getTitle().' : '; ?></b></label>
											<?php if($measurement->getDropdownType() == 'custom'){
												$customtitles = Mage::getModel('measurement/customtitles')->load($flatrates->{'get' .$value}());
												$final_value = $customtitles->getTitle();
											}else{
												if($measurement->getFieldType() == 'text_area'){
													$final_value = $flatrates->{'get' .$value}();
												}else{
													$final_value = $flatrates->{'get' .$value}().' '.$flatrates->getMeasurmentUnits();
												}
											} ?>
											<label class="value"><?php echo $final_value; ?></label>
										</div>
									<?php }
								} ?>
							</div>
						</div>
					</div>
					<div class="clearer"></div>
				</li>
			<?php }
			if ($flatrates->getSalwarId() > 0) {
				$details = Mage::getSingleton('salwar/salwar')->getCollection()->addFieldToSelect('*')->addFieldToFilter('salwar_id',$flatrates->getSalwarId())->addFieldToFilter('status',1)->getFirstItem(); ?>
				<li>
					<div class="details">
						<div class="title">
							<label>Salwar Style & Measurements</label>
						</div>
						<div class="more_details">
							<div class="image"><img width="300" height="400" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$details->getImage(); ?>"></div>
							<div class="info">
								<?php $attr = explode(',', $details->getMeasurementAttr());
								foreach ($attr as $value) {
									$b = $flatrates->{'get' .$value}();
									if (isset($b) && $b > 0) {
										$measurement = Mage::getSingleton('measurement/measurement')->getCollection()->addFieldToSelect('*')->addFieldToFilter('measurement_id',$value)->addFieldToFilter('status',1)->getFirstItem(); ?>
										<div class="review_your_measurements1">
											<label class="label"><b><?php echo $measurement->getTitle().' : '; ?></b></label>
											<?php if($measurement->getDropdownType() == 'custom'){
												$customtitles = Mage::getModel('measurement/customtitles')->load($flatrates->{'get' .$value}());
												$final_value = $customtitles->getTitle();
											}else{
												if($measurement->getFieldType() == 'text_area'){
													$final_value = $flatrates->{'get' .$value}();
												}else{
													$final_value = $flatrates->{'get' .$value}().' '.$flatrates->getMeasurmentUnits();
												}
											} ?>
											<label class="value"><?php echo $final_value; ?></label>
										</div>
									<?php }
								} ?>
							</div>
						</div>
					</div>
					<div class="clearer"></div>
				</li>
			<?php }
			if ($flatrates->getTasselId() > 0) {
				$details = Mage::getSingleton('tassel/tassel')->getCollection()->addFieldToSelect('*')->addFieldToFilter('tassel_id',$flatrates->getTasselId())->addFieldToFilter('status',1)->getFirstItem(); ?>
				<li>
					<div class="details">
						<div class="title">
							<label>Tassel Style & Measurements</label>
						</div>
						<div class="more_details">
							<div class="image"><img width="300" height="400" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$details->getImage(); ?>"></div>
							<div class="info">
								<?php $attr = explode(',', $details->getMeasurementAttr());
								foreach ($attr as $value) {
									$b = $flatrates->{'get' .$value}();
									if (isset($b) && $b > 0) {
										$measurement = Mage::getSingleton('measurement/measurement')->getCollection()->addFieldToSelect('*')->addFieldToFilter('measurement_id',$value)->addFieldToFilter('status',1)->getFirstItem(); ?>
										<div class="review_your_measurements1">
											<label class="label"><b><?php echo $measurement->getTitle().' : '; ?></b></label>
											<?php if($measurement->getDropdownType() == 'custom'){
												$customtitles = Mage::getModel('measurement/customtitles')->load($flatrates->{'get' .$value}());
												$final_value = $customtitles->getTitle();
											}else{
												if($measurement->getFieldType() == 'text_area'){
													$final_value = $flatrates->{'get' .$value}();
												}else{
													$final_value = $flatrates->{'get' .$value}().' '.$flatrates->getMeasurmentUnits();
												}
											} ?>
											<label class="value"><?php echo $final_value; ?></label>
										</div>
									<?php }
								} ?>
							</div>
						</div>
					</div>
					<div class="clearer"></div>
				</li>
			<?php }
		echo '</ul/></div>';
		?>
	</div>
</div>
<style type="text/css">	
.details .title {
    background: #cfcfcf none repeat scroll 0 0;
    padding: 7px;
    text-align: center;
    margin: 10px 0;
    font-size: 14px;
    font-weight: bold;
}
.body p.des {
    padding: 20px;
}
.info {
    min-height: 400px;
}
.image {
    float: left;
    padding: 0 3%;
    width: 44%;
}
.review_your_measurements1 {
    line-height: 22px;
}
.label {
    padding: 0 5px;
}
body{font:normal 12px Arial; color:#000; text-align:left;}
body, ul, li, tr, th, td, table, h1, p{margin: 0; padding: 0; border: 0; outline: 0; text-decoration: none; }
th{ border-bottom:1px solid #000; border-top:1px solid #000; padding:3px 0;}
ol, ul {list-style: none}
.main-wrapper{margin:0 auto; width:900px; overflow:hidden; clear:both; border:1px solid #ccc; padding:10px;}
.header .lft-div{ width:200px; float:left}
.header .rht-div{ width:200px; float:right}
.clr{clear:both; margin:0; padding:0; line-height:0; overflow:hidden}
ul.para li{list-style-type:none; line-height:20px;}
ul.para li span{display:block; float:left; width:10px;}
ul.para li label{float:left; padding-left:10px; width:625px;}
.grand_total { border-top: 1px solid #000; }
</style>