<?php 
	$lehangacollection = Mage::getModel('lehanga/lehanga')
											->getCollection()
											->addFieldToFilter('stitching_service', array('like' => '%'.$_REQUEST['stitching_type'].'%'))
											->addFieldToFilter('status',1);
?>
<div class="lehanga">
	<?php if(sizeof($lehangacollection) > 0) { ?>
		<div class="label_title1"><label>Lehanga/Skirt/Petticoat Styles</label></div>
		<div class="sleeve_style_details">
			<ul class="back_style" id="item_style4">
				<?php $i = 0; foreach ($lehangacollection as $key => $_lehanga) { ?>
					<li class="lehanga_style_li" data="<?php echo $i; ?>">
					<div class="title"><label><?php echo $_lehanga->getTitle(); ?></label></div>
					<div class="image"><img width="130" height="180" alt="<?php echo $_lehanga->getTitle(); ?>" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$_lehanga->getImage(); ?>"></div>
					<div class="select_option"><input id="<?php echo $_REQUEST['service']; ?>" class="lehanga_id" name="lehanga_id" type="radio" value="<?php echo $_lehanga->getLehangaId(); ?>" /></div>
					</li>
				<?php $i++; } ?>
			</ul>
		</div>
	<?php } ?>
	<script type="text/javascript">
		var jQuery = jQuery.noConflict();
		jQuery(function(){
			jQuery("#item_style4").flexisel();
		    jQuery('.lehanga_id').click(function() {
		    	var tassel_size = parseInt(jQuery('.tassel_size').val());
		    	var service = parseInt(jQuery('.service').val());
		    	var stitching_type = parseInt(jQuery('.stitching_type').val());
		    	if(tassel_size > 0) {
		    		var data1 = "&stitching_type="+stitching_type+"&service="+service;
		            var url1 = '<?php echo Mage::getBaseUrl(); ?>measurement/measure/gettasselstyles';
		            try {
						jQuery.ajax({
							url: url1,
							type : 'post',
							data: data1,
							success: function(response){
								if (response) {
									var string = response;
								} else{
									var string = '<div class="tassel"><p>Currently the Measurements are Unavailable for this product</p></div>';
								}
								jQuery('.tassel').replaceWith(string);
							}
						});
					} catch(e){ }
		    	} else{
	        		var lehanga_size = parseInt(jQuery('.lehanga').val());
	        		var salwar_size = parseInt(jQuery('.salwar').val());
	    			var front_id = 0;
		        	var back_id = 0;
		        	var sleeve_id = 0;
		        	var lehanga_id = 0;
		        	var salwar_id = 0;
		        	var tassel_id = 0;
			    	jQuery(".front_id").each(function() {
						if( jQuery(this).prop("checked")== true) {
							front_id = jQuery(this).attr("value");
						}
					});
			    	jQuery(".back_id").each(function() {
						if( jQuery(this).prop("checked")== true) {
							back_id = jQuery(this).attr("value");
						}
					});
			    	jQuery(".sleeve_id").each(function() {
						if( jQuery(this).prop("checked")== true) {
							sleeve_id = jQuery(this).attr("value");
						}
					});
					jQuery(".lehanga_id").each(function() {
						if( jQuery(this).prop("checked")== true) {
							lehanga_id = jQuery(this).attr("value");
						}
					});
					jQuery(".salwar_id").each(function() {
						if( jQuery(this).prop("checked")== true) {
							salwar_id = jQuery(this).attr("value");
						}
					});
					jQuery(".tassel_id").each(function() {
						if( jQuery(this).prop("checked")== true) {
							tassel_id = jQuery(this).attr("value");
						}
					});
					var data1 = "&front_id="+front_id+"&back_id="+back_id+"&sleeve_id="+sleeve_id+"&lehanga_id="+lehanga_id+"&salwar_id="+salwar_id+"&tassel_id="+tassel_id+"&service="+service;
		            var url1 = '<?php echo Mage::getBaseUrl(); ?>measurement/measure/getmeasurements';
		            try {
						jQuery.ajax({
							url: url1,
							type : 'post',
							data: data1,
							success: function(response){
								if (response) {
									var string = response;
								} else{
									var string = '<div id="measurement_step" class="measurement_details"><p>Currently the Measurements are Unavailable for this product</p></div>';
								}
								jQuery('.measurement_details').replaceWith(string);
							}
						});
					} catch(e){ }
		    	}
			});
		});
	</script>
</div>