<?php
    $url = $_SERVER['REQUEST_URI'];
    $urlarr =explode('/id/',$url);
    $myid = explode('/',$urlarr[1]);
    $attrid = $myid[0];
    if(!empty($attrid)){
    	$sleevescollection = Mage::getModel('sleeves/sleeves')->getCollection()->addFieldToFilter('sleeves_id',$attrid)->getFirstItem();
    	$collection = Mage::getModel('styles/styles')->getCollection()->addFieldToFilter('stitching_service_id',$sleevescollection->getStitchingServiceId());
    }
    $attribute = Mage::getSingleton('eav/config')->getAttribute('catalog_product', 'a27');
	if ($attribute->usesSource()) {
		$stitching_services = $attribute->getSource()->getAllOptions(false);
	}
?>
<table cellspacing="0" class="form-list">
	<tbody>
		<tr>
			<td class="label"><label for="stitching_service_id">Stitching Service<span class="required">*</span></label></td>
			<td class="value">
				<select class="required-entry select" name="stitching_service_id" id="stitching_service_id">
					<?php foreach ($stitching_services as $key => $value) { 
						if (!empty($attrid) && $sleevescollection->getStitchingServiceId() == $value['value']) {
							echo '<option value="'.$value['value'].'" selected="selected" >'.$value['label'].'</option>';	
						}else {
							echo '<option value="'.$value['value'].'" >'.$value['label'].'</option>';
						}
						?>
					<?php } ?>
				</select>
			</td>
		</tr>
		<tr>
			<td class="label"><label for="front_id">Available Front Styles<span class="required">*</span></label></td>
			<td class="value">
				<select class="required-entry select front" <?php if(empty($attrid)){ echo 'disabled="disabled"'; } ?> name="front_id" id="front_id">
				<?php if(!empty($attrid)){
					foreach ($collection as $value) {
    		 			if ($sleevescollection->getFrontId() == $value->getStyleId()) {
							echo '<option value="'.$value->getStyleId().'" selected="selected" >'.$value->getTitle().'</option>';	
						}else {
							echo '<option value="'.$value->getStyleId().'" >'.$value->getTitle().'</option>';
						}
    				}
				} ?>
				</select>
			</td>
		</tr>
		<tr>
			<td class="label"><label for="back_id">Available Back Styles<span class="required">*</span></label></td>
			<td class="value">
				<select class="required-entry select back" <?php if(empty($attrid)){ echo 'disabled="disabled"'; } ?> name="back_id" id="back_id">
				<?php if(!empty($attrid)){
					foreach ($collection as $value) {
    		 			if ($sleevescollection->getFrontId() == $value->getStyleId()) {
							echo '<option value="'.$value->getStyleId().'" selected="selected" >'.$value->getTitle().'</option>';	
						}else {
							echo '<option value="'.$value->getStyleId().'" >'.$value->getTitle().'</option>';
						}
    				}
				} ?>
				</select>
			</td>
		</tr>
	</tbody>
</table>

<script src="http://code.jquery.com/jquery-latest.min.js" type="text/javascript"></script>
<script type="text/javascript">
	var jQuery = jQuery.noConflict();
	jQuery("select#stitching_service_id").change(function () {
		var data = "stitching_service_id="+this.value; 
		jQuery.ajax({
			url: '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB);?>back/index/index',
			type : 'post',
			data: data,
			success: function(data){
					jQuery('#front_id:last').replaceWith(data);
			}
		});
	});

	// jQuery(".front").change(function () {
	// 	alert('Hi');
	// 	var data = "front="+this.value;
	// 	jQuery.ajax({
	// 		url: '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB);?>sleeves/index/index',
	// 		type : 'post',
	// 		data: data,
	// 		success: function(data){
	// 				jQuery('.back:last').replaceWith(data);
	// 		}
	// 	});
	// 	return false;
	// });
</script>