<?php
	
	if (is_ajax()) {
		if (isset($_POST["front"]) && !empty($_POST["front"])) { //Checks if action value exists
			$read = Mage::getSingleton('core/resource')->getConnection('core_read');
			$response = $read->fetchAll('SELECT `back_id`,`title` FROM `measurement_back_styles` WHERE `front_id` = '.$_POST['front']); ?>
			<select id="back_id" name="back_id" class="required-entry select">
			<option>--- Please Select ---</option>
				<?php foreach ($response as $key => $value) { ?>
					<option value="<?php echo $value['back_id']; ?>"><?php echo $value['title']; ?></option>
				<?php } ?>
			</select>
		<?php }
	}

	function is_ajax() {
		return isset($_SERVER['HTTP_X_REQUESTED_WITH']) && strtolower($_SERVER['HTTP_X_REQUESTED_WITH']) == 'xmlhttprequest';
	}	
?>