<div class="edit_measurements">
	<div class="page-title">
        <h1>Edit Stored Measurement</h1>
    </div>
    <div class="edit_measurement">
    	<?php $storedCollection = Mage::getModel('measurementremember/measurementremember')->load($_REQUEST['id']);
        if (isset($storedCollection)) {
            $flatrateCollection = Mage::getModel('measurementremember/flatrates')->load($storedCollection->getFlatrateId()); ?>
            <form action="<?php echo Mage::getBaseUrl(); ?>measurement/stored/saveedit" method="post" id="measurement">
                <input type="hidden" name="service" class="service" value="<?php echo $storedCollection->getStitchingServiceId(); ?>" />
                <input type="hidden" name="stitching_type" class="stitching_type" value="<?php echo $storedCollection->getStitchingType(); ?>" />
                <input type="hidden" name="customer_id" class="customer_id" value="<?php echo Mage::getSingleton('customer/session')->getId(); ?>" />
                <input type="hidden" name="measurement_id" class="measurement_id" value="<?php echo $storedCollection->getMeasurementrememberId(); ?>" />
                <div class="measure_details">
                    <div class="measurement_block" id="measurement_step">
                        <div class="measuring_units"><p>
                            <input <?php if($flatrateCollection->getMeasurmentUnits() == 'in'){ echo 'checked'; } ?> class="measuring_unit" type="radio" name="measurment_units" value="in"> Inchs
                            <input <?php if($flatrateCollection->getMeasurmentUnits() == 'cm'){ echo 'checked'; } ?> class="measuring_unit" type="radio" name="measurment_units" value="cm"> Centemeters
                        </p></div>
                        <div class="m_attr">
                            <label id="label" class="required"><?php echo "<em>*</em>"; ?><b>Measurements For </b></label>
                            <label class="value"><input type="text" name="storing_for" class="measurement_textfield" value="<?php echo $storedCollection->getTitle(); ?>" /></label>
                        </div>
                        <div class="custom_measurements">
                            <?php $front = Mage::getModel('styles/styles')->getCollection()->addFieldToSelect('measurement_attr')->addFieldToFilter('style_id',$flatrateCollection->getFrontId())->addFieldToFilter('status',1)->getFirstItem();
                            $back = Mage::getModel('back/back')->getCollection()->addFieldToSelect('measurement_attr')->addFieldToFilter('back_id',$flatrateCollection->getBackId())->addFieldToFilter('status',1)->getFirstItem();
                            $sleeve = Mage::getModel('sleeves/sleeves')->getCollection()->addFieldToSelect('measurement_attr')->addFieldToFilter('sleeves_id',$flatrateCollection->getSleeveId())->addFieldToFilter('status',1)->getFirstItem();
                            $lehanga = Mage::getModel('lehanga/lehanga')->getCollection()->addFieldToSelect('measurement_attr')->addFieldToFilter('lehanga_id',$flatrateCollection->getLehangaId())->addFieldToFilter('status',1)->getFirstItem();
                            $salwar = Mage::getModel('salwar/salwar')->getCollection()->addFieldToSelect('measurement_attr')->addFieldToFilter('salwar_id',$flatrateCollection->getSalwarId())->addFieldToFilter('status',1)->getFirstItem();
                            $tassel = Mage::getModel('tassel/tassel')->getCollection()->addFieldToSelect('measurement_attr')->addFieldToFilter('tassel_id',$flatrateCollection->getTasselId())->addFieldToFilter('status',1)->getFirstItem();
                            if(strlen($front['measurement_attr']) > 0) {
                                $front_attr = explode(',', $front['measurement_attr']); ?>
                                <div class="front_measurements">
                                    <div class="title">Front Measurements</div>
                                    <div class="front_measurement_details">
                                        <?php foreach ($front_attr as $key => $_front) {
                                            $_front1 = Mage::getModel('measurement/measurement')->load($_front);
                                            $customtitles = Mage::getModel('measurement/customtitles')->getCollection()->addFieldToFilter('measurement_id',$_front1->getMeasurementId());
                                            $min = $_front1->getMinVal();
                                            $max = $_front1->getMaxVal();
                                            if($flatrateCollection->getMeasurmentUnits() == 'cm'){ 
                                                $unit = 2.54;
                                                $min = round( ($min*$unit), 2);
                                                $min = 5 * round($min / 5, 2);
                                                $max = round( ($max*$unit), 2);
                                                $max = 5 * round($max / 5, 2);
                                            }
                                            $b = $flatrateCollection->{'get' .$_front1->getMeasurementId()}();
                                            $difference = $_front1->getDifference(); ?>
                                            <div class="m_attr"><label id="label" class="<?php if($_front1->getIsRequired() == 1){ echo "required"; } ?>"><?php if($_front1->getIsRequired() == 1){ echo "<em>*</em>"; } ?><?php echo $_front1->getTitle(); ?></label>
                                                <label class="value">
                                                    <?php if($_front1->getFieldType() == 'radio') { ?>
                                                        <?php foreach ($customtitles as $key => $_customtitle) { ?>
                                                            <label class="radio_button"><input <?php if(abs(($_customtitle->getCustomTitleId()-$b)/$b) < 0.00001) { echo 'checked'; } ?> name="<?php echo $storedCollection->getStitchingServiceId(); ?>[<?php echo $_front1->getMeasurementId(); ?>]" type="radio" value="<?php echo $_customtitle->getCustomTitleId(); ?>" /><?php echo $_customtitle->getTitle(); ?></label>
                                                        <?php } ?>
                                                    <?php } elseif($_front1->getFieldType() == 'text_area') { ?>
                                                        <label class="value">
                                                            <textarea name="<?php echo $storedCollection->getStitchingServiceId(); ?>[<?php echo $_front1->getMeasurementId(); ?>]" cols="45" rows="3" style="resize: none;"><?php echo $flatrateCollection->{'get' .$_front1->getMeasurementId()}(); ?></textarea>
                                                        </label>
                                                    <?php }elseif($_front1->getFieldType() == 'text_field') { ?>
                                                        <input value="<?php echo $flatrateCollection->{'get' .$_front1->getMeasurementId()}(); ?>" class="measurement_textfield" type="number" step="<?php echo $difference; ?>" name="<?php echo $storedCollection->getStitchingServiceId(); ?>[<?php echo $_front1->getMeasurementId(); ?>]" min="<?php echo $min; ?>" max="<?php echo $max; ?>" >
                                                        <span><span><?php echo '('.$min.' - '.$max.')'; ?></span><span><?php echo $flatrateCollection->getMeasurmentUnits(); ?></span></span>
                                                    <?php }elseif($_front1->getFieldType() == 'dropdown') {
                                                        if($_front1->getDropdownType() == 'standard') { ?>
                                                            <select name="<?php echo $storedCollection->getStitchingServiceId(); ?>[<?php echo $_front1->getMeasurementId(); ?>]">
                                                                <option></option>
                                                                <?php while($min <= $max) { ?>
                                                                    <option <?php if(abs(($min-$b)/$b) < 0.00001) { echo 'selected'; } ?> ><?php echo $min; ?></option>
                                                                    <?php $min += $difference;
                                                                } ?>
                                                            </select>
                                                            <span><span><?php echo '('.$min.' - '.$max.')'; ?></span><span><?php echo $flatrateCollection->getMeasurmentUnits(); ?></span></span>
                                                         <?php }else if($_front1->getDropdownType() == 'custom'){ ?>
                                                            <select name="<?php echo $storedCollection->getStitchingServiceId(); ?>[<?php echo $_front1->getMeasurementId(); ?>]">
                                                                <option></option>
                                                                <?php foreach ($customtitles as $key => $_customtitle) { ?>
                                                                    <option <?php if (abs(($_customtitle->getCustomTitleId()-$b)/$b) < 0.00001) { echo 'selected'; } ?> value="<?php echo $_customtitle->getCustomTitleId(); ?>"><?php echo $_customtitle->getTitle(); ?></option>
                                                                <?php } ?>
                                                            </select>
                                                         <?php } ?>
                                                    <?php } ?>
                                                </label>
                                                <?php if (!empty($_front1->getImage())) { ?>
                                                    <label class="image"><img width="150" height="200" title="Image" alt="Image" src="<?php echo Mage::getBaseUrl('media').$_front1->getImage(); ?>"></label>
                                                <?php } ?>
                                                <label class="content">
                                                    <h5>Ho to Measure</h5>
                                                    <h3><?php echo strtoupper($_front1->getTitle()); ?></h3>
                                                    <?php echo $_front1->getContent(); ?>
                                                </label>
                                            </div>

                                        <?php } ?>
                                    </div>
                                </div>
                            <?php } if(strlen($back['measurement_attr']) > 0) {
                                $back_attr = explode(',', $back['measurement_attr']); ?>
                                <div class="back_measurements">
                                    <div class="title">Back Measurements</div>
                                    <div class="back_measurement_details">
                                        <?php foreach ($back_attr as $key => $_back) {
                                            $_back1 = Mage::getModel('measurement/measurement')->load($_back);
                                            $customtitles = Mage::getModel('measurement/customtitles')->getCollection()->addFieldToFilter('measurement_id',$_back1->getMeasurementId());
                                            $min = $_back1->getMinVal();
                                            $max = $_back1->getMaxVal();
                                            if($flatrateCollection->getMeasurmentUnits() == 'cm'){ 
                                                $unit = 2.54;
                                                $min = round( ($min*$unit), 2);
                                                $min = 5 * round($min / 5, 2);
                                                $max = round( ($max*$unit), 2);
                                                $max = 5 * round($max / 5, 2);
                                            }
                                            $b = $flatrateCollection->{'get' .$_back1->getMeasurementId()}();
                                            $difference = $_back1->getDifference(); ?>
                                            <div class="m_attr"><label id="label" class="<?php if($_back1->getIsRequired() == 1){ echo "required"; } ?>"><?php if($_back1->getIsRequired() == 1){ echo "<em>*</em>"; } ?><?php echo $_back1->getTitle(); ?></label>
                                                <label class="value">
                                                    <?php if($_back1->getFieldType() == 'radio') { ?>
                                                        <?php foreach ($customtitles as $key => $_customtitle) { ?>
                                                            <label class="radio_button"><input <?php if(abs(($_customtitle->getCustomTitleId()-$b)/$b) < 0.00001) { echo 'checked'; } ?> name="<?php echo $storedCollection->getStitchingServiceId(); ?>[<?php echo $_back1->getMeasurementId(); ?>]" type="radio" value="<?php echo $_customtitle->getCustomTitleId(); ?>" /><?php echo $_customtitle->getTitle(); ?></label>
                                                        <?php } ?>
                                                    <?php } elseif($_back1->getFieldType() == 'text_area') { ?>
                                                        <label class="value">
                                                            <textarea name="<?php echo $storedCollection->getStitchingServiceId(); ?>[<?php echo $_back1->getMeasurementId(); ?>]" class="" cols="45" rows="3" style="resize: none;"><?php echo $flatrateCollection->{'get' .$_back1->getMeasurementId()}(); ?></textarea>
                                                        </label>
                                                    <?php }elseif($_back1->getFieldType() == 'text_field') { ?>
                                                        <input value="<?php echo $flatrateCollection->{'get' .$_back1->getMeasurementId()}(); ?>" class="measurement_textfield" type="number" step="<?php echo $difference; ?>" name="<?php echo $storedCollection->getStitchingServiceId(); ?>[<?php echo $_back1->getMeasurementId(); ?>]" min="<?php echo $min; ?>" max="<?php echo $max; ?>" >
                                                        <span><span><?php echo '('.$min.' - '.$max.')'; ?></span><span><?php echo $flatrateCollection->getMeasurmentUnits(); ?></span></span>
                                                    <?php }elseif($_back1->getFieldType() == 'dropdown') {
                                                        if($_back1->getDropdownType() == 'standard') { ?>
                                                            <select name="<?php echo $storedCollection->getStitchingServiceId(); ?>[<?php echo $_back1->getMeasurementId(); ?>]">
                                                                <option></option>
                                                                <?php while($min <= $max) { ?>
                                                                    <option <?php if(abs(($min-$b)/$b) < 0.00001) { echo 'selected'; } ?> ><?php echo $min; ?></option>
                                                                    <?php $min += $difference;
                                                                } ?>
                                                            </select>
                                                            <span><span><?php echo '('.$min.' - '.$max.')'; ?></span><span><?php echo $flatrateCollection->getMeasurmentUnits(); ?></span></span>
                                                        <?php }else if($_back1->getDropdownType() == 'custom'){ ?>
                                                            <select name="<?php echo $storedCollection->getStitchingServiceId(); ?>[<?php echo $_back1->getMeasurementId(); ?>]">
                                                                <option></option>
                                                                <?php foreach ($customtitles as $key => $_customtitle) { ?>
                                                                    <option <?php if (abs(($_customtitle->getCustomTitleId()-$b)/$b) < 0.00001) { echo 'selected'; } ?> value="<?php echo $_customtitle->getCustomTitleId(); ?>"><?php echo $_customtitle->getTitle(); ?></option>
                                                                <?php } ?>
                                                            </select>
                                                        <?php } ?>
                                                    <?php } ?>
                                                </label>
                                                <?php if (!empty($_back1->getImage())) { ?>
                                                    <label class="image"><img width="150" height="200" title="Image" alt="Image" src="<?php echo Mage::getBaseUrl('media').$_back1->getImage(); ?>"></label>
                                                <?php } ?>
                                                <label class="content">
                                                    <h5>Ho to Measure</h5>
                                                    <h3><?php echo strtoupper($_back1->getTitle()); ?></h3>
                                                    <?php echo $_back1->getContent(); ?>
                                                </label>
                                            </div>

                                        <?php } ?>
                                    </div>
                                </div>
                            <?php }
                            if(strlen($sleeve['measurement_attr']) > 0) {
                                // print_r($sleeve['measurement_attr']);
                                $sleeve_attr = explode(',', $sleeve['measurement_attr']); ?>
                                <div class="sleeve_measurements">
                                    <div class="title">Sleeve Measurements</div>
                                    <div class="sleeve_measurement_details">
                                        <?php foreach ($sleeve_attr as $key => $_sleeve) {
                                            $_sleeve1 = Mage::getModel('measurement/measurement')->load($_sleeve);
                                            $customtitles = Mage::getModel('measurement/customtitles')->getCollection()->addFieldToFilter('measurement_id',$_sleeve1->getMeasurementId());
                                            $min = $_sleeve1->getMinVal();
                                            $max = $_sleeve1->getMaxVal();
                                            if($flatrateCollection->getMeasurmentUnits() == 'cm'){ 
                                                $unit = 2.54;
                                                $min = round( ($min*$unit), 2);
                                                $min = 5 * round($min / 5, 2);
                                                $max = round( ($max*$unit), 2);
                                                $max = 5 * round($max / 5, 2);
                                            }
                                            $b = $flatrateCollection->{'get' .$_sleeve1->getMeasurementId()}();
                                            $difference = $_sleeve1->getDifference(); ?>
                                            <div class="m_attr"><label id="label" class="<?php if($_sleeve1->getIsRequired() == 1){ echo "required"; } ?>"><?php if($_sleeve1->getIsRequired() == 1){ echo "<em>*</em>"; } ?><?php echo $_sleeve1->getTitle(); ?></label>
                                                <label class="value">
                                                    <?php if($_sleeve1->getFieldType() == 'radio') { ?>
                                                        <?php foreach ($customtitles as $key => $_customtitle) { ?>
                                                            <label class="radio_button"><input <?php if(abs(($_customtitle->getCustomTitleId()-$b)/$b) < 0.00001) { echo 'checked'; } ?> name="<?php echo $storedCollection->getStitchingServiceId(); ?>[<?php echo $_sleeve1->getMeasurementId(); ?>]" type="radio" value="<?php echo $_customtitle->getCustomTitleId(); ?>" /><?php echo $_customtitle->getTitle(); ?></label>
                                                        <?php } ?>
                                                    <?php } elseif($_sleeve1->getFieldType() == 'text_area') { ?>
                                                        <label class="value">
                                                            <textarea name="<?php echo $storedCollection->getStitchingServiceId(); ?>[<?php echo $_sleeve1->getMeasurementId(); ?>]" cols="45" rows="3" style="resize: none;"><?php echo $flatrateCollection->{'get' .$_sleeve1->getMeasurementId()}(); ?></textarea>
                                                        </label>
                                                    <?php }elseif($_sleeve1->getFieldType() == 'text_field') { ?>
                                                        <input value="<?php echo $flatrateCollection->{'get' .$_sleeve1->getMeasurementId()}(); ?>" class="measurement_textfield" type="number" step="<?php echo $difference; ?>" name="<?php echo $_sleeve1->getMeasurementId(); ?>" min="<?php echo $min; ?>" max="<?php echo $max; ?>" >
                                                        <span><span><?php echo '('.$min.' - '.$max.')'; ?></span><span><?php echo $flatrateCollection->getMeasurmentUnits(); ?></span></span>
                                                    <?php }elseif($_sleeve1->getFieldType() == 'dropdown') {
                                                        if($_sleeve1->getDropdownType() == 'standard') { ?>
                                                            <select name="<?php echo $storedCollection->getStitchingServiceId(); ?>[<?php echo $_sleeve1->getMeasurementId(); ?>]">
                                                                <option></option>
                                                                <?php while($min <= $max) { ?>
                                                                    <option <?php if(abs(($min-$b)/$b) < 0.00001) { echo 'selected'; } ?> ><?php echo $min; ?></option>
                                                                    <?php $min += $difference;
                                                                } ?>
                                                            </select>
                                                            <span><span><?php echo '('.$min.' - '.$max.')'; ?></span><span><?php echo $flatrateCollection->getMeasurmentUnits(); ?></span></span>
                                                         <?php }else if($_sleeve1->getDropdownType() == 'custom'){ ?>
                                                            <select name="<?php echo $storedCollection->getStitchingServiceId(); ?>[<?php echo $_sleeve1->getMeasurementId(); ?>]">
                                                                <option></option>
                                                                <?php foreach ($customtitles as $key => $_customtitle) { ?>
                                                                    <option <?php if (abs(($_customtitle->getCustomTitleId()-$b)/$b) < 0.00001) { echo 'selected'; } ?> value="<?php echo $_customtitle->getCustomTitleId(); ?>"><?php echo $_customtitle->getTitle(); ?></option>
                                                                <?php } ?>
                                                            </select>
                                                         <?php } ?>
                                                    <?php } ?>
                                                </label>
                                                <?php if (!empty($_sleeve1->getImage())) { ?>
                                                    <label class="image"><img width="150" height="200" title="Image" alt="Image" src="<?php echo Mage::getBaseUrl('media').$_sleeve1->getImage(); ?>"></label>
                                                <?php } ?>
                                                <label class="content">
                                                    <h5>Ho to Measure</h5>
                                                    <h3><?php echo strtoupper($_sleeve1->getTitle()); ?></h3>
                                                    <?php echo $_sleeve1->getContent(); ?>
                                                </label>
                                            </div>

                                        <?php } ?>
                                    </div>
                                </div>
                            <?php }
                            if(strlen($lehanga['measurement_attr']) > 0) {
                                $lehanga_attr = explode(',', $lehanga['measurement_attr']); ?>
                                <div class="lehanga_measurements">
                                    <div class="title">lehanga Measurements</div>
                                    <div class="lehanga_measurement_details">
                                        <?php foreach ($lehanga_attr as $key => $_lehanga) {
                                            $_lehanga1 = Mage::getModel('measurement/measurement')->load($_lehanga);
                                            $customtitles = Mage::getModel('measurement/customtitles')->getCollection()->addFieldToFilter('measurement_id',$_lehanga1->getMeasurementId());
                                            $min = $_lehanga1->getMinVal();
                                            $max = $_lehanga1->getMaxVal();
                                            if($flatrateCollection->getMeasurmentUnits() == 'cm'){ 
                                                $unit = 2.54;
                                                $min = round( ($min*$unit), 2);
                                                $min = 5 * round($min / 5, 2);
                                                $max = round( ($max*$unit), 2);
                                                $max = 5 * round($max / 5, 2);
                                            }
                                            $b = $flatrateCollection->{'get' .$_lehanga1->getMeasurementId()}();
                                            $difference = $_lehanga1->getDifference(); ?>
                                            <div class="m_attr"><label id="label" class="<?php if($_lehanga1->getIsRequired() == 1){ echo "required"; } ?>"><?php if($_lehanga1->getIsRequired() == 1){ echo "<em>*</em>"; } ?><?php echo $_lehanga1->getTitle(); ?></label>
                                                <label class="value">
                                                    <?php if($_lehanga1->getFieldType() == 'radio') { ?>
                                                        <?php foreach ($customtitles as $key => $_customtitle) { ?>
                                                            <label class="radio_button"><input <?php if(abs(($_customtitle->getCustomTitleId()-$b)/$b) < 0.00001) { echo 'checked'; } ?> name="<?php echo $storedCollection->getStitchingServiceId(); ?>[<?php echo $_lehanga1->getMeasurementId(); ?>]" type="radio" value="<?php echo $_customtitle->getCustomTitleId(); ?>" /><?php echo $_customtitle->getTitle(); ?></label>
                                                        <?php } ?>
                                                    <?php } elseif($_lehanga1->getFieldType() == 'text_area') { ?>
                                                        <label class="value">
                                                            <textarea name="<?php echo $storedCollection->getStitchingServiceId(); ?>[<?php echo $_lehanga1->getMeasurementId(); ?>]" cols="45" rows="3" style="resize: none;"><?php echo $flatrateCollection->{'get' .$_lehanga1->getMeasurementId()}(); ?></textarea>
                                                        </label>
                                                    <?php }elseif($_lehanga1->getFieldType() == 'text_field') { ?>
                                                        <input value="<?php echo $flatrateCollection->{'get' .$_lehanga1->getMeasurementId()}(); ?>" class="measurement_textfield" type="number" step="<?php echo $difference; ?>" name="<?php echo $storedCollection->getStitchingServiceId(); ?>[<?php echo $_lehanga1->getMeasurementId(); ?>]" min="<?php echo $min; ?>" max="<?php echo $max; ?>" >
                                                        <span><span><?php echo '('.$min.' - '.$max.')'; ?></span><span><?php echo $flatrateCollection->getMeasurmentUnits(); ?></span></span>
                                                    <?php }elseif($_lehanga1->getFieldType() == 'dropdown') {
                                                        if($_lehanga1->getDropdownType() == 'standard') { ?>
                                                            <select name="<?php echo $storedCollection->getStitchingServiceId(); ?>[<?php echo $_lehanga1->getMeasurementId(); ?>]">
                                                                <option></option>
                                                                <?php while($min <= $max) { ?>
                                                                    <option <?php if(abs(($min-$b)/$b) < 0.00001) { echo 'selected'; } ?> ><?php echo $min; ?></option>
                                                                    <?php $min += $difference;
                                                                } ?>
                                                            </select>
                                                            <span><span><?php echo '('.$min.' - '.$max.')'; ?></span><span><?php echo $flatrateCollection->getMeasurmentUnits(); ?></span></span>
                                                         <?php }else if($_lehanga1->getDropdownType() == 'custom'){ ?>
                                                            <select name="<?php echo $storedCollection->getStitchingServiceId(); ?>[<?php echo $_lehanga1->getMeasurementId(); ?>]">
                                                                <option></option>
                                                                <?php foreach ($customtitles as $key => $_customtitle) { ?>
                                                                    <option <?php if (abs(($_customtitle->getCustomTitleId()-$b)/$b) < 0.00001) { echo 'selected'; } ?> value="<?php echo $_customtitle->getCustomTitleId(); ?>"><?php echo $_customtitle->getTitle(); ?></option>
                                                                <?php } ?>
                                                            </select>
                                                         <?php } ?>
                                                    <?php } ?>
                                                </label>
                                                <?php if (!empty($_lehanga1->getImage())) { ?>
                                                    <label class="image"><img width="150" height="200" title="Image" alt="Image" src="<?php echo Mage::getBaseUrl('media').$_lehanga1->getImage(); ?>"></label>
                                                <?php } ?>
                                                <label class="content">
                                                    <h5>Ho to Measure</h5>
                                                    <h3><?php echo strtoupper($_lehanga1->getTitle()); ?></h3>
                                                    <?php echo $_lehanga1->getContent(); ?>
                                                </label>
                                            </div>

                                        <?php } ?>
                                    </div>
                                </div>
                            <?php } if(strlen($salwar['measurement_attr']) > 0) {
                                $salwar_attr = explode(',', $salwar['measurement_attr']); ?>
                                <div class="salwar_measurements">
                                    <div class="title">salwar Measurements</div>
                                    <div class="salwar_measurement_details">
                                        <?php foreach ($salwar_attr as $key => $_salwar) {
                                            $_salwar1 = Mage::getModel('measurement/measurement')->load($_salwar);
                                            $customtitles = Mage::getModel('measurement/customtitles')->getCollection()->addFieldToFilter('measurement_id',$_salwar1->getMeasurementId());
                                            $min = $_salwar1->getMinVal();
                                            $max = $_salwar1->getMaxVal();
                                            if($flatrateCollection->getMeasurmentUnits() == 'cm'){ 
                                                $unit = 2.54;
                                                $min = round( ($min*$unit), 2);
                                                $min = 5 * round($min / 5, 2);
                                                $max = round( ($max*$unit), 2);
                                                $max = 5 * round($max / 5, 2);
                                            }
                                            $b = $flatrateCollection->{'get' .$_salwar1->getMeasurementId()}();
                                            $difference = $_salwar1->getDifference(); ?>
                                            <div class="m_attr"><label id="label" class="<?php if($_salwar1->getIsRequired() == 1){ echo "required"; } ?>"><?php if($_salwar1->getIsRequired() == 1){ echo "<em>*</em>"; } ?><?php echo $_salwar1->getTitle(); ?></label>
                                                <label class="value">
                                                    <?php if($_salwar1->getFieldType() == 'radio') { ?>
                                                        <?php foreach ($customtitles as $key => $_customtitle) { ?>
                                                            <label class="radio_button"><input <?php if(abs(($_customtitle->getCustomTitleId()-$b)/$b) < 0.00001) { echo 'checked'; } ?> name="<?php echo $storedCollection->getStitchingServiceId(); ?>[<?php echo $_salwar1->getMeasurementId(); ?>]" type="radio" value="<?php echo $_customtitle->getCustomTitleId(); ?>" /><?php echo $_customtitle->getTitle(); ?></label>
                                                        <?php } ?>
                                                    <?php } elseif($_salwar1->getFieldType() == 'text_area') { ?>
                                                        <label class="value">
                                                            <textarea name="<?php echo $storedCollection->getStitchingServiceId(); ?>[<?php echo $_salwar1->getMeasurementId(); ?>]" class="" cols="45" rows="3" style="resize: none;"><?php echo $flatrateCollection->{'get' .$_salwar1->getMeasurementId()}(); ?></textarea>
                                                        </label>
                                                    <?php }elseif($_salwar1->getFieldType() == 'text_field') { ?>
                                                        <input value="<?php echo $flatrateCollection->{'get' .$_salwar1->getMeasurementId()}(); ?>" class="measurement_textfield" type="number" step="<?php echo $difference; ?>" name="<?php echo $storedCollection->getStitchingServiceId(); ?>[<?php echo $_salwar1->getMeasurementId(); ?>]" min="<?php echo $min; ?>" max="<?php echo $max; ?>" >
                                                        <span><span><?php echo '('.$min.' - '.$max.')'; ?></span><span><?php echo $flatrateCollection->getMeasurmentUnits(); ?></span></span>
                                                    <?php }elseif($_salwar1->getFieldType() == 'dropdown') {
                                                        if($_salwar1->getDropdownType() == 'standard') { ?>
                                                            <select name="<?php echo $storedCollection->getStitchingServiceId(); ?>[<?php echo $_salwar1->getMeasurementId(); ?>]">
                                                                <option></option>
                                                                <?php while($min <= $max) { ?>
                                                                    <option <?php if(abs(($min-$b)/$b) < 0.00001) { echo 'selected'; } ?> ><?php echo $min; ?></option>
                                                                    <?php $min += $difference;
                                                                } ?>
                                                            </select>
                                                            <span><span><?php echo '('.$min.' - '.$max.')'; ?></span><span><?php echo $flatrateCollection->getMeasurmentUnits(); ?></span></span>
                                                        <?php }else if($_salwar1->getDropdownType() == 'custom'){ ?>
                                                            <select name="<?php echo $storedCollection->getStitchingServiceId(); ?>[<?php echo $_salwar1->getMeasurementId(); ?>]">
                                                                <option></option>
                                                                <?php foreach ($customtitles as $key => $_customtitle) { ?>
                                                                    <option <?php if (abs(($_customtitle->getCustomTitleId()-$b)/$b) < 0.00001) { echo 'selected'; } ?> value="<?php echo $_customtitle->getCustomTitleId(); ?>"><?php echo $_customtitle->getTitle(); ?></option>
                                                                <?php } ?>
                                                            </select>
                                                        <?php } ?>
                                                    <?php } ?>
                                                </label>
                                                <?php if (!empty($_salwar1->getImage())) { ?>
                                                    <label class="image"><img width="150" height="200" title="Image" alt="Image" src="<?php echo Mage::getBaseUrl('media').$_salwar1->getImage(); ?>"></label>
                                                <?php } ?>
                                                <label class="content">
                                                    <h5>Ho to Measure</h5>
                                                    <h3><?php echo strtoupper($_salwar1->getTitle()); ?></h3>
                                                    <?php echo $_salwar1->getContent(); ?>
                                                </label>
                                            </div>

                                        <?php } ?>
                                    </div>
                                </div>
                            <?php }
                            if(strlen($tassel['measurement_attr']) > 0) {
                                // print_r($tassel['measurement_attr']);
                                $tassel_attr = explode(',', $tassel['measurement_attr']); ?>
                                <div class="tassel_measurements">
                                    <div class="title">tassel Measurements</div>
                                    <div class="tassel_measurement_details">
                                        <?php foreach ($tassel_attr as $key => $_tassel) {
                                            $_tassel1 = Mage::getModel('measurement/measurement')->load($_tassel);
                                            $customtitles = Mage::getModel('measurement/customtitles')->getCollection()->addFieldToFilter('measurement_id',$_tassel1->getMeasurementId());
                                            $min = $_tassel1->getMinVal();
                                            $max = $_tassel1->getMaxVal();
                                            if($flatrateCollection->getMeasurmentUnits() == 'cm'){ 
                                                $unit = 2.54;
                                                $min = round( ($min*$unit), 2);
                                                $min = 5 * round($min / 5, 2);
                                                $max = round( ($max*$unit), 2);
                                                $max = 5 * round($max / 5, 2);
                                            }
                                            $b = $flatrateCollection->{'get' .$_tassel1->getMeasurementId()}();
                                            $difference = $_tassel1->getDifference(); ?>
                                            <div class="m_attr"><label id="label" class="<?php if($_tassel1->getIsRequired() == 1){ echo "required"; } ?>"><?php if($_tassel1->getIsRequired() == 1){ echo "<em>*</em>"; } ?><?php echo $_tassel1->getTitle(); ?></label>
                                                <label class="value">
                                                    <?php if($_tassel1->getFieldType() == 'radio') { ?>
                                                        <?php foreach ($customtitles as $key => $_customtitle) { ?>
                                                            <label class="radio_button"><input <?php if(abs(($_customtitle->getCustomTitleId()-$b)/$b) < 0.00001) { echo 'checked'; } ?> name="<?php echo $storedCollection->getStitchingServiceId(); ?>[<?php echo $_tassel1->getMeasurementId(); ?>]" type="radio" value="<?php echo $_customtitle->getCustomTitleId(); ?>" /><?php echo $_customtitle->getTitle(); ?></label>
                                                        <?php } ?>
                                                    <?php } elseif($_tassel1->getFieldType() == 'text_area') { ?>
                                                        <label class="value">
                                                            <textarea name="<?php echo $storedCollection->getStitchingServiceId(); ?>[<?php echo $_tassel1->getMeasurementId(); ?>]" cols="45" rows="3" style="resize: none;"><?php echo $flatrateCollection->{'get' .$_tassel1->getMeasurementId()}(); ?></textarea>
                                                        </label>
                                                    <?php }elseif($_tassel1->getFieldType() == 'text_field') { ?>
                                                        <input value="<?php echo $flatrateCollection->{'get' .$_tassel1->getMeasurementId()}(); ?>" class="measurement_textfield" type="number" step="<?php echo $difference; ?>" name="<?php echo $_tassel1->getMeasurementId(); ?>" min="<?php echo $min; ?>" max="<?php echo $max; ?>" >
                                                        <span><span><?php echo '('.$min.' - '.$max.')'; ?></span><span><?php echo $flatrateCollection->getMeasurmentUnits(); ?></span></span>
                                                    <?php }elseif($_tassel1->getFieldType() == 'dropdown') {
                                                        if($_tassel1->getDropdownType() == 'standard') { ?>
                                                            <select name="<?php echo $storedCollection->getStitchingServiceId(); ?>[<?php echo $_tassel1->getMeasurementId(); ?>]">
                                                                <option></option>
                                                                <?php while($min <= $max) { ?>
                                                                    <option <?php if(abs(($min-$b)/$b) < 0.00001) { echo 'selected'; } ?> ><?php echo $min; ?></option>
                                                                    <?php $min += $difference;
                                                                } ?>
                                                            </select>
                                                            <span><span><?php echo '('.$min.' - '.$max.')'; ?></span><span><?php echo $flatrateCollection->getMeasurmentUnits(); ?></span></span>
                                                         <?php }else if($_tassel1->getDropdownType() == 'custom'){ ?>
                                                            <select name="<?php echo $storedCollection->getStitchingServiceId(); ?>[<?php echo $_tassel1->getMeasurementId(); ?>]">
                                                                <option></option>
                                                                <?php foreach ($customtitles as $key => $_customtitle) { ?>
                                                                    <option <?php if (abs(($_customtitle->getCustomTitleId()-$b)/$b) < 0.00001) { echo 'selected'; } ?> value="<?php echo $_customtitle->getCustomTitleId(); ?>"><?php echo $_customtitle->getTitle(); ?></option>
                                                                <?php } ?>
                                                            </select>
                                                         <?php } ?>
                                                    <?php } ?>
                                                </label>
                                                <?php if (!empty($_tassel1->getImage())) { ?>
                                                    <label class="image"><img width="150" height="200" title="Image" alt="Image" src="<?php echo Mage::getBaseUrl('media').$_tassel1->getImage(); ?>"></label>
                                                <?php } ?>
                                                <label class="content">
                                                    <h5>Ho to Measure</h5>
                                                    <h3><?php echo strtoupper($_tassel1->getTitle()); ?></h3>
                                                    <?php echo $_tassel1->getContent(); ?>
                                                </label>
                                            </div>

                                        <?php } ?>
                                    </div>
                                </div>
                            <?php } ?>
                        </div>
                        <div><button type="submit">Submit</button></div>
                    </div>
                </div>
            </form>
        <?php } ?>
    </div>
</div>
<style type="text/css">
    .edit_measurement { padding: 0 20px; }
    .edit_measurement .measuring_units{line-height:30px;margin-bottom: 5px;text-align:center;}
    .edit_measurement .m_attr{line-height:30px;margin-bottom: 5px;}
    .edit_measurement .m_attr .label{float:left;width:40%;}
    .edit_measurement .m_attr .value select{min-width:150px;}
    .edit_measurement .m_attr .value .measurement_textfield {line-height: 30px;min-width: 150px;padding-left: 5px;}
    /*.edit_measurement .measurement_block {padding-left: 10%;}*/
    .title {color: red;}
    .m_attr .image {
        display: none;
        float: right;
    }
    .m_attr .content {
        border: 1px solid #a2a2a2;
        border-radius: 5px;
        display: none;
        float: right;
        margin-right: 10px;
        padding: 10px;
        width: 150px;
    }
    .m_attr > #label {
        float: left;
        min-height: 35px;
        width: 25% !important;
    }
</style>
<script type="text/javascript">
    var jQuery = jQuery.noConflict();
    jQuery(function(){
        jQuery('.measuring_unit').click(function() {
            var data1 = "&units="+this.value+"&measurement_id="+jQuery('.measurement_id').val()+"&customer_id="+jQuery('.customer_id').val()+"&service="+jQuery('.service').val();
            var url1 = '<?php echo Mage::getBaseUrl(); ?>measurement/stored/getcustommeasurements';
            try {
                jQuery('#ajax_loader').show();
                jQuery.ajax({
                    url: url1,
                    type : 'post',
                    data: data1,
                    success: function(response){
                        jQuery('#ajax_loader').hide();
                        if (response) {
                            var string = response;
                        } else{
                            var string = '<div class="custom_measurements"></div>';
                        }
                        jQuery('.custom_measurements').replaceWith(string);
                    }
                });
            } catch(e){ }
        });
        jQuery('label.value input').focus( function() {
            jQuery(jQuery(this).parent().parent()).find('label.content:first').show();
            jQuery(jQuery(this).parent().parent()).find('label.image:first').show();
        });
        jQuery('label.value input').blur( function() {
            jQuery(jQuery(this).parent().parent()).find('label.content:first').hide();
            jQuery(jQuery(this).parent().parent()).find('label.image:first').hide();
        });
        jQuery('label.value select').focus( function() {
            jQuery(jQuery(this).parent().parent()).find('label.content:first').show();
            jQuery(jQuery(this).parent().parent()).find('label.image:first').show();
        });
        jQuery('label.value select').blur( function() {
            jQuery(jQuery(this).parent().parent()).find('label.content:first').hide();
            jQuery(jQuery(this).parent().parent()).find('label.image:first').hide();
        });
        jQuery("label.value input").hover(
            function(){
                jQuery(jQuery(this).parent().parent()).find('label.content:first').toggle();
                jQuery(jQuery(this).parent().parent()).find('label.image:first').toggle();
            },
            function(){
                jQuery(jQuery(this).parent().parent()).find('label.content:first').toggle();
                jQuery(jQuery(this).parent().parent()).find('label.image:first').toggle();
            }
        );
        jQuery("label.value select").hover(
            function(){
                jQuery(jQuery(this).parent().parent()).find('label.content:first').toggle();
                jQuery(jQuery(this).parent().parent()).find('label.image:first').toggle();
            },
            function(){
                jQuery(jQuery(this).parent().parent()).find('label.content:first').toggle();
                jQuery(jQuery(this).parent().parent()).find('label.image:first').toggle();
            }
        );
    });
</script>