<?php 
	$tasselcollection = Mage::getModel('tassel/tassel')->getCollection()
											->addFieldToFilter('stitching_service', array('like' => '%'.$_REQUEST['stitching_type'].'%'))
											->addFieldToFilter('status',1)
											->addFieldToFilter('stitching_service_id',$_REQUEST['service']);
?>
<div class="tassel">
	<?php if(sizeof($tasselcollection) > 0) { ?>
		<div class="label_title1"><label>Tassel Styles</label></div>
		<div class="add_tassel_style_details" id="style_details">
			<ul class="tassel_style" id="item_style6">
				<?php $i = 0; foreach ($tasselcollection as $key => $_tassel) { ?>
					<li class="tassel_style_li" data="<?php echo $i; ?>">
					<div class="title"><label><?php echo $_tassel->getTitle(); ?></label></div>
					<div class="image"><img width="130" height="180" alt="<?php echo $_tassel->getTitle(); ?>" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$_tassel->getImage(); ?>"></div>
					<div class="select_option"><input id="<?php echo $_REQUEST['service']; ?>" class="tassel_id" name="tassel_id" type="radio" value="<?php echo $_tassel->getTasselId(); ?>" /></div>
					</li>
				<?php $i++; } ?>
			</ul>
		</div>
	<?php } ?>
	<script type="text/javascript">
		var jQuery = jQuery.noConflict();
		jQuery(function(){
			jQuery("#item_style6").flexisel();
		    jQuery('.tassel_id').click(function() {
		    	var data1 = '';
		        var url1 = '<?php echo Mage::getBaseUrl(); ?>measurement/stored/units';
				try {
					jQuery('#ajax_loader').show();
					jQuery.ajax({
						url: url1,
						type : 'post',
						data: data1,
						success: function(response){
							jQuery('#ajax_loader').hide();
							if (response) {
								var string = response;
							} else{
								var string = '<div class="add_measuring_units"></div>';
							}
							jQuery('.add_measuring_units').replaceWith(string);
						}
					});
				} catch(e){ }
			});
		});
	</script>
</div>