<div class="my_measurements">
	<div class="page-title">
        <h1>My Measurements</h1>
    </div>
    <div class="pending_measurements_to_submit"></div>
    <div class="add_new_measurements"><a class="add_new" href="<?php echo Mage::getBaseUrl(); ?>measurement/stored/add">Add New Measurements</a></div>
    <div class="pstored_measurements">
    	<?php $customer = Mage::getSingleton('customer/session')->getCustomer();
    	$storedCollection = Mage::getModel('measurementremember/measurementremember')->getCollection()
    													->addFieldToFilter('c_id', $customer->getId())
    													->addFieldToFilter('account', 1)
    													->setOrder('created_time','desc');
        if (sizeof($storedCollection) > 0) { ?>
            <table id="my-measurements-table" class="data-table">
                <thead>
                    <tr class="first last">
                        <th>Name</th>
                        <th>Created/Modified On</th>
                        <th style="text-align:center;">Action</th>
                    </tr>
                </thead>
                <tbody>
                    <?php $i = 1;
                    foreach ($storedCollection as $_measurement) { ?>
                        <tr class="<?php if ($i == 1) {echo 'first'; } ?> <?php if ($i == sizeof($storedCollection)) {echo 'last'; } ?> <?php if($i % 2 == 0){ echo 'even'; } else{ echo 'odd'; } ?>" ><td><?php echo $_measurement->getTitle(); ?></td><td><?php echo $_measurement->getUpdateTime(); ?></td><td><label class="left"><button onclick="popup('<?php echo Mage::getBaseUrl(); ?>measurementremember/index/preview?id=<?php echo $_measurement->getMeasurementrememberId(); ?>')" id="preview" title="Preview" type="button" class="scalable"><span><span><span>Preview</span></span></span></button></label><label class="left"><a href="<?php echo Mage::getBaseUrl(); ?>measurement/stored/edit?id=<?php echo $_measurement->getMeasurementrememberId(); ?>">Edit</a></label><label class="left"><a href="<?php echo Mage::getBaseUrl(); ?>measurement/stored/delete?id=<?php echo $_measurement->getMeasurementrememberId(); ?>">Delete</a></label></td></tr>
                    <?php $i++; } ?>
                </tbody>
            </table>
        <?php } else{ ?>
            <p>There no measurements stored in your account</p>
        <?php } ?>
    </div>
</div>
<script>
    function popup(url) {
        window.open(url, "_blank", "toolbar=no, scrollbars=yes, resizable=no, top=50, left=50, width=900");
    }
</script>