<?php 
	$sleevecollection = Mage::getModel('sleeves/sleeves')
											->getCollection()
											->addFieldToFilter('status',1)
											->addFieldToFilter('front_id',$_REQUEST['front_id'])
											->addFieldToFilter('back_id',$_REQUEST['back_id']);
?>
<div class="sleeve">
	<div class="label_title1"><label>Sleeve Styles</label></div>
	<div class="add_sleeve_style_details" id="style_details">
		<?php if(sizeof($sleevecollection) > 0) { ?>
			<ul class="sleeve_style" id="item_style22">
				<?php $i = 0; foreach ($sleevecollection as $key => $_sleeve) { ?>
					<li class="sleeve_style_li" data="<?php echo $i; ?>">
					<div class="title"><label><?php echo $_sleeve->getTitle(); ?></label></div>
					<div class="image"><img width="130" height="180" alt="<?php echo $_sleeve->getTitle(); ?>" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$_sleeve->getImage(); ?>"></div>
					<div class="select_option"><input class="sleeve_id" name="sleeve_id" type="radio" value="<?php echo $_sleeve->getSleevesId(); ?>" /></div>
					</li>
				<?php $i++; } ?>
			</ul>
		<?php } else { ?>
			<p>Currently the Sleeve Styles are Unavailable for this product</p>
		<?php }?>
	</div>
	<script type="text/javascript">
		var jQuery = jQuery.noConflict();
		jQuery(function(){
			jQuery("#item_style22").flexisel();
			jQuery('.sleeve_id').click(function() {
        		var service = parseInt(jQuery('select.add_avail_stitching_services').val());
        		var lehanga_size = parseInt(jQuery('.lehanga_size').val());
        		var salwar_size = parseInt(jQuery('.salwar_size').val());
        		var tassel_size = parseInt(jQuery('.tassel_size').val());
        		var stitching_type = parseInt(jQuery('select.add_stitching_services_types').val());
        		var data1 = "&stitching_type="+stitching_type+"&service="+service;
        		if (lehanga_size > 0) {
		            var url1 = '<?php echo Mage::getBaseUrl(); ?>measurement/stored/getlehangastyles';
		            try {
		            	jQuery('#ajax_loader').show();
						jQuery.ajax({
							url: url1,
							type : 'post',
							data: data1,
							success: function(response){
								jQuery('#ajax_loader').hide();
								if (response) {
									var string = response;
								} else{
									var string = '<div class="lehanga"><p>Currently the Measurements are Unavailable for this product</p></div>';
								}
								jQuery('.lehanga').replaceWith(string);
							}
						});
					} catch(e){ }
        		} else if(salwar_size > 0){
		            var url1 = '<?php echo Mage::getBaseUrl(); ?>measurement/stored/getsalwarstyles';
		            try {
		            	jQuery('#ajax_loader').show();
						jQuery.ajax({
							url: url1,
							type : 'post',
							data: data1,
							success: function(response){
								jQuery('#ajax_loader').hide();
								if (response) {
									var string = response;
								} else{
									var string = '<div class="salwar"><p>Currently the Measurements are Unavailable for this product</p></div>';
								}
								jQuery('.salwar').replaceWith(string);
							}
						});
					} catch(e){ }
        		} else if(tassel_size > 0 && salwar_size == 0 & lehanga_size == 0){
		            var url1 = '<?php echo Mage::getBaseUrl(); ?>measurement/stored/gettasselstyles';
		            try {
		            	jQuery('#ajax_loader').show();
						jQuery.ajax({
							url: url1,
							type : 'post',
							data: data1,
							success: function(response){
								jQuery('#ajax_loader').hide();
								if (response) {
									var string = response;
								} else{
									var string = '<div class="tassel"><p>Currently the Measurements are Unavailable for this product</p></div>';
								}
								jQuery('.tassel').replaceWith(string);
							}
						});
					} catch(e){ }
        		} else {
        			var data1 = '';
			        var url1 = '<?php echo Mage::getBaseUrl(); ?>measurement/stored/units';
					try {
						jQuery('#ajax_loader').show();
						jQuery.ajax({
							url: url1,
							type : 'post',
							data: data1,
							success: function(response){
								jQuery('#ajax_loader').hide();
								if (response) {
									var string = response;
								} else{
									var string = '<div class="add_measuring_units"></div>';
								}
								jQuery('.add_measuring_units').replaceWith(string);
							}
						});
					} catch(e){ }
        		}
			});
		});
	</script>
</div>